PRODUCT_TYPE_THANH_PHAM = 'thanh_pham'
PRODUCT_TYPE_HANG_HOA = 'hang_hoa'

PRODUCT_TYPE_CHOICES = [
    (PRODUCT_TYPE_THANH_PHAM, 'Thành phẩm'),
    (PRODUCT_TYPE_HANG_HOA, 'Hàng hoá'),
]

PRODUCT_TYPE_LABELS = dict(PRODUCT_TYPE_CHOICES)

SYNC_SOURCE_MANUAL = 'manual'
SYNC_SOURCE_KIOTVIET = 'kiotviet'

SYNC_SOURCE_CHOICES = [
    (SYNC_SOURCE_MANUAL, 'Nhập tay'),
    (SYNC_SOURCE_KIOTVIET, 'KiotViet'),
]
