# Generated by Django 5.2.7 on 2026-10-05 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TienDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('portal', 'Tiến độ Portal'), ('wholesale_retail', 'Tiến độ Website sỉ/lẻ')], db_index=True, max_length=20, verbose_name='Nền tảng')),
                ('feature', models.CharField(blank=True, max_length=255, verbose_name='Tính năng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('user_flow', models.TextField(blank=True, verbose_name='User flow')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_tested', models.BooleanField(default=False, verbose_name='Đã test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tien_do_items_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Dòng tiến độ',
                'verbose_name_plural': 'Dòng tiến độ',
                'ordering': ['-created_at'],
            },
        ),
    ]
