# Generated by Django 5.2.7 on 2026-09-18 06:46

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0105_add_company_trip_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Số')),
                ('lucky', models.BooleanField(default=False, verbose_name='Lucky')),
                ('shown', models.BooleanField(default=False, verbose_name='Đã quay')),
            ],
            options={
                'verbose_name': 'Số quay thưởng',
                'verbose_name_plural': 'Số quay thưởng',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TripEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Thư mời {{ gender_prefix }} {{ fullname }} tham gia Company Trip 2026 — Vĩnh Hy', max_length=255, verbose_name='Tiêu đề')),
                ('body', ckeditor.fields.RichTextField(blank=True, help_text='Biến: {{ fullname }}, {{ gender_prefix }}, {{ dates }}, {{ destination }}, {{ register_url }}', verbose_name='Nội dung HTML')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mẫu email Company Trip',
                'verbose_name_plural': 'Mẫu email Company Trip',
            },
        ),
        migrations.CreateModel(
            name='TripSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Company Trip 2026 — Vĩnh Hy', max_length=255, verbose_name='Tên sự kiện')),
                ('destination', models.CharField(default='Vịnh Vĩnh Hy', max_length=255, verbose_name='Điểm đến')),
                ('start_date', models.DateField(default=datetime.date(2026, 11, 22), verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(default=datetime.date(2026, 11, 23), verbose_name='Ngày kết thúc')),
                ('registration_open', models.BooleanField(default=True, verbose_name='Mở đăng ký')),
                ('dates_display', models.CharField(default='22–23/11/2026', max_length=64, verbose_name='Chuỗi ngày hiển thị')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Company Trip',
                'verbose_name_plural': 'Cấu hình Company Trip',
            },
        ),
        migrations.CreateModel(
            name='TripRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('department_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('Ban tổ chức sắp xếp', 'Ban tổ chức sắp xếp'), ('Phòng 2', 'Phòng 2'), ('Phòng 3', 'Phòng 3')], default='Ban tổ chức sắp xếp', max_length=64, verbose_name='Loại phòng')),
                ('companion1_name', models.CharField(blank=True, max_length=255)),
                ('companion2_name', models.CharField(blank=True, max_length=255)),
                ('room_key', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Mã phòng')),
                ('vegetarian', models.CharField(choices=[('Ăn chay', 'Ăn chay'), ('Không ăn chay', 'Không ăn chay')], default='Không ăn chay', max_length=32, verbose_name='Ăn chay')),
                ('allergy_note', models.TextField(blank=True, verbose_name='Dị ứng')),
                ('pickup_point', models.CharField(blank=True, max_length=255, verbose_name='Điểm đón')),
                ('breakfast_choice', models.CharField(choices=[('Bánh canh', 'Bánh canh'), ('Mì gói', 'Mì gói'), ('Bún bò', 'Bún bò'), ('Bánh mì ốp-la', 'Bánh mì ốp-la'), ('Không ăn sáng', 'Không ăn sáng')], default='Không ăn sáng', max_length=64, verbose_name='Ăn sáng')),
                ('route', models.CharField(blank=True, choices=[('Tham quan Vịnh Vĩnh Hy', 'Tham quan Vịnh Vĩnh Hy'), ('Tham quan Hang Rái', 'Tham quan Hang Rái'), ('Tham quan Vịnh Vĩnh Hy - Tham quan Hang Rái', 'Tham quan Vịnh Vĩnh Hy - Tham quan Hang Rái'), ('Không tham quan - Đợi tại vườn nho hoặc nhà hàng bến tàu', 'Không tham quan - Đợi tại vườn nho hoặc nhà hàng bến tàu')], max_length=255, verbose_name='Lộ trình')),
                ('detail_route', models.TextField(blank=True, verbose_name='Chi tiết lộ trình')),
                ('shopping', models.CharField(choices=[('Tham gia', 'Tham gia'), ('Không tham gia', 'Không tham gia')], default='Tham gia', max_length=32, verbose_name='Mua sắm chợ Đầm Nại')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('organized_committee', models.BooleanField(default=False, verbose_name='BTC sắp xếp phòng')),
                ('status', models.CharField(choices=[('registered', 'Đã đăng ký'), ('cancelled', 'Đã hủy')], db_index=True, default='registered', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companion1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_companion1_of', to='hrm.profile', verbose_name='Người cùng phòng 1')),
                ('companion2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_companion2_of', to='hrm.profile', verbose_name='Người cùng phòng 2')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_trip_registration', to='hrm.profile', verbose_name='Nhân viên')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_trip_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Đăng ký Company Trip',
                'verbose_name_plural': 'Đăng ký Company Trip',
                'ordering': ['-created_at'],
            },
        ),
    ]
