# Generated by Django 5.2.7 on 2026-09-23 01:58

from django.db import migrations, models


def remap_room_types(apps, schema_editor):
    TripRegistration = apps.get_model('company_trip', 'TripRegistration')
    TripRegistration.objects.filter(room_type='Ban tổ chức sắp xếp').update(
        room_type='Ban tổ chức tự sắp xếp',
    )
    for reg in TripRegistration.objects.filter(room_type__in=['Phòng 2', 'Phòng 3']):
        if reg.companion1_id:
            reg.room_type = 'Đăng ký với đồng nghiệp'
            reg.companion2_id = None
            reg.companion2_name = ''
        else:
            reg.room_type = 'Ban tổ chức tự sắp xếp'
            reg.companion1_id = None
            reg.companion2_id = None
            reg.companion1_name = ''
            reg.companion2_name = ''
        reg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company_trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripregistration',
            name='companion_confirmed',
            field=models.BooleanField(default=False, verbose_name='Đồng nghiệp đã xác nhận'),
        ),
        migrations.AddField(
            model_name='tripregistration',
            name='companion_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xác nhận'),
        ),
        migrations.AddField(
            model_name='tripregistration',
            name='relative_cccd',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số CCCD người thân'),
        ),
        migrations.AddField(
            model_name='tripregistration',
            name='relative_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh người thân'),
        ),
        migrations.AddField(
            model_name='tripregistration',
            name='relative_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Họ tên người thân'),
        ),
        migrations.AddField(
            model_name='tripregistration',
            name='relative_gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='Giới tính người thân'),
        ),
        migrations.AddField(
            model_name='tripregistration',
            name='relative_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='SĐT người thân'),
        ),
        migrations.AlterField(
            model_name='tripregistration',
            name='room_type',
            field=models.CharField(choices=[('Ban tổ chức tự sắp xếp', 'Ban tổ chức tự sắp xếp'), ('Đăng ký chung với người thân', 'Đăng ký chung với người thân'), ('Đăng ký với đồng nghiệp', 'Đăng ký với đồng nghiệp')], default='Ban tổ chức tự sắp xếp', max_length=64, verbose_name='Loại phòng'),
        ),
        migrations.RunPython(remap_room_types, migrations.RunPython.noop),
    ]
