# Generated by Django 5.2.7 on 2026-09-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_trip', '0002_room_types_relative_colleague'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripregistration',
            name='companion_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email đồng nghiệp'),
        ),
    ]
