# Generated by Django 5.2.7 on 2026-09-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_trip', '0003_companion_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpinNumber',
        ),
    ]
