# Generated by Django 5.2.7 on 2026-09-23 03:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_trip', '0004_remove_lucky_spin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripemailtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Biến: {{ fullname }}, {{ gender_prefix }}, {{ dates }}, {{ destination }}, {{ location }}, {{ resort }}, {{ pickup }}, {{ gather_time }}, {{ itinerary }}, {{ register_url }}, {{ title }}, {{ year }}, {{ room_type }}, {{ companions }}, {{ phone }}, {{ department }}', verbose_name='Nội dung HTML'),
        ),
        migrations.AlterField(
            model_name='tripemailtemplate',
            name='subject',
            field=models.CharField(default='Thư mời tham gia Kế hoạch du lịch nghỉ mát {{ year }} - Just Play', max_length=255, verbose_name='Tiêu đề'),
        ),
    ]
