# Generated by Django 5.2.7 on 2026-09-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_trip', '0007_trip_relatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripregistration',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('Phòng giường đôi (double)', 'Phòng giường đôi (double)'), ('Phòng giường đơn (twin)', 'Phòng giường đơn (twin)')], max_length=64, verbose_name='Loại phòng'),
        ),
        migrations.AlterField(
            model_name='tripregistration',
            name='room_type',
            field=models.CharField(choices=[('Ban tổ chức tự sắp xếp', 'Ban tổ chức tự sắp xếp'), ('Đăng ký chung với người thân', 'Đăng ký chung với người thân'), ('Đăng ký với đồng nghiệp', 'Đăng ký với đồng nghiệp')], default='Ban tổ chức tự sắp xếp', max_length=64, verbose_name='Đăng ký với'),
        ),
    ]
