# Generated by Django 5.2.7 on 2026-05-29 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0022_add_service_requests_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã loại')),
                ('name', models.CharField(max_length=200, verbose_name='Tên loại')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Loại yêu cầu',
                'verbose_name_plural': 'Loại yêu cầu',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestTypeStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(verbose_name='Thứ tự bước')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bước')),
                ('step_kind', models.CharField(choices=[('approval', 'Duyệt'), ('execution', 'Thực hiện')], default='approval', max_length=20, verbose_name='Loại bước')),
                ('assignee_rule', models.CharField(choices=[('direct_manager', 'Cấp trên trực tiếp'), ('department_queue', 'Hàng đợi phòng ban')], max_length=30, verbose_name='Quy tắc gán người xử lý')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_templates', to='service_requests.requesttype', verbose_name='Loại yêu cầu')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_step_templates', to='hrm.department', verbose_name='Phòng ban xử lý')),
            ],
            options={
                'verbose_name': 'Bước quy trình mẫu',
                'verbose_name_plural': 'Bước quy trình mẫu',
                'ordering': ['step_order'],
                'unique_together': {('request_type', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Nội dung')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Dự toán (VNĐ)')),
                ('status', models.CharField(choices=[('in_progress', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], db_index=True, default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='service_requests.requesttype', verbose_name='Loại yêu cầu')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Yêu cầu nội bộ',
                'verbose_name_plural': 'Yêu cầu nội bộ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(verbose_name='Thứ tự')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bước')),
                ('step_kind', models.CharField(max_length=20, verbose_name='Loại bước')),
                ('assignee_rule', models.CharField(max_length=30, verbose_name='Quy tắc gán')),
                ('status', models.CharField(choices=[('blocked', 'Chờ bước trước'), ('pending', 'Chờ xử lý'), ('in_progress', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('rejected', 'Từ chối'), ('skipped', 'Bỏ qua')], db_index=True, default='blocked', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú / kết quả')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn xử lý')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_steps', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_steps', to='service_requests.servicerequeststep', verbose_name='Phụ thuộc bước')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='service_requests.servicerequest', verbose_name='Yêu cầu')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_steps', to='hrm.department', verbose_name='Phòng ban')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='service_requests.requesttypesteptemplate', verbose_name='Mẫu bước')),
            ],
            options={
                'verbose_name': 'Bước yêu cầu',
                'verbose_name_plural': 'Bước yêu cầu',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_logs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='service_requests.servicerequest')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='service_requests.servicerequeststep')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_requests/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(choices=[('request', 'Khi gửi'), ('result', 'Kết quả xử lý')], default='request', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_requests.servicerequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request_uploads', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_requests.servicerequeststep')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
