# Generated by Django 5.2.7 on 2026-06-01 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('service_requests', '0004_it_repair_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='equipment.device', verbose_name='Thiết bị liên kết'),
        ),
    ]
