# Generated by Django 5.2.7 on 2026-06-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0007_servicerequest_repair_equipment_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('hw', 'Phần cứng'), ('sw', 'Phần mềm'), ('network', 'Mạng / Internet'), ('account', 'Tài khoản / quyền truy cập'), ('other', 'Khác'), ('m_stop', 'Máy ngừng / không chạy'), ('m_mech', 'Cơ khí / truyền động'), ('m_elec', 'Điện / khí nén / PLC'), ('m_parts', 'Phụ tùng / vật tư'), ('m_quality', 'Chất lượng sản phẩm / lỗi may'), ('m_safety', 'An toàn lao động'), ('m_other', 'Khác')], max_length=20, verbose_name='Loại sự cố'),
        ),
    ]
