# Generated by Django 5.2.7 on 2026-10-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0008_alter_servicerequest_incident_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung theo loại'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Số tiền (VNĐ)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_subtype',
            field=models.CharField(choices=[('purchase', 'Mua vật tư, thiết bị, văn phòng phẩm'), ('payment', 'Thanh toán, tạm ứng, hoàn ứng'), ('hr', 'Tuyển dụng và điều chuyển nhân sự'), ('repair', 'Sửa chữa máy móc, IT, cơ sở vật chất'), ('account', 'Cấp phát tài khoản, máy tính, email')], db_index=True, default='purchase', max_length=20, verbose_name='Loại đề xuất'),
        ),
    ]
