# Generated by Django 5.2.7 on 2026-10-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0011_general_execution_step_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_subtype',
            field=models.CharField(choices=[('purchase', 'Mua vật tư, thiết bị, văn phòng phẩm'), ('payment', 'Thanh toán, tạm ứng, hoàn ứng'), ('candidate', 'Yêu cầu ứng viên (tuyển dụng)'), ('hr', 'Điều chuyển nhân sự'), ('repair', 'Sửa chữa máy móc, IT, cơ sở vật chất'), ('account', 'Cấp phát tài khoản, máy tính, email')], db_index=True, default='purchase', max_length=20, verbose_name='Loại đề xuất'),
        ),
    ]
