# Generated by Django 5.2.7 on 2026-06-05 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiotviet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KvSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=64, unique=True)),
                ('interval_hours', models.PositiveSmallIntegerField(default=2)),
                ('schedule_enabled', models.BooleanField(default=True)),
                ('enabled_entities', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kv_sync_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cấu hình đồng bộ KiotViet',
                'verbose_name_plural': 'Cấu hình đồng bộ KiotViet',
                'db_table': 'kv_sync_config',
            },
        ),
        migrations.CreateModel(
            name='KvSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', 'Thủ công'), ('scheduled', 'Tự động')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Chờ'), ('running', 'Đang chạy'), ('success', 'Thành công'), ('failed', 'Thất bại')], db_index=True, default='pending', max_length=16)),
                ('full_sync', models.BooleanField(default=False)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('current_entity', models.CharField(blank=True, default='', max_length=32)),
                ('rows_synced', models.BigIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('entity_results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kv_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job đồng bộ KiotViet',
                'verbose_name_plural': 'Job đồng bộ KiotViet',
                'db_table': 'kv_sync_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
