# Generated by Django 5.2.7 on 2026-06-05 03:30

from django.db import migrations, models


def _hours_to_minutes(hours: int) -> int:
    mapping = {1: 30, 2: 30, 3: 30, 6: 360, 12: 720, 24: 1440}
    return mapping.get(hours, 30)


def convert_interval_hours_to_minutes(apps, schema_editor):
    KvSyncConfig = apps.get_model('kiotviet', 'KvSyncConfig')
    for config in KvSyncConfig.objects.all():
        hours = getattr(config, 'interval_hours', 2) or 2
        config.interval_minutes = _hours_to_minutes(int(hours))
        config.save(update_fields=['interval_minutes'])


class Migration(migrations.Migration):

    dependencies = [
        ('kiotviet', '0002_sync_config_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvproduct',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='kvsyncconfig',
            name='interval_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.RunPython(convert_interval_hours_to_minutes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='kvsyncconfig',
            name='interval_hours',
        ),
    ]
