# Generated by Django 5.2.7 on 2026-04-15 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên được chỉ định'),
        ),
    ]
