# Generated by Django 5.2.7 on 2026-04-15 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'verbose_name_plural': 'Danh mục năng lực'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên dự thi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả kỳ thi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', to='assessment.question', verbose_name='Ngân hàng câu hỏi trong đề'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='auto_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm máy chấm'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='manual_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm Admin chấm'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_hint',
            field=models.ImageField(blank=True, null=True, upload_to='question_hints/', verbose_name='Ảnh minh họa'),
        ),
    ]
