# Generated by Django 5.2.7 on 2026-04-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_competency_options_alter_exam_assigned_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('Bác Sĩ', 'Bác Sĩ'), ('Điều Dưỡng', 'Điều Dưỡng'), ('Dược Sĩ', 'Dược Sĩ'), ('Kỹ Thuật viên', 'Kỹ Thuật viên'), ('Khối Hỗ trợ', 'Khối Hỗ trợ')], max_length=50, verbose_name='Chức danh'),
        ),
    ]
