# Generated by Django 5.2.7 on 2026-04-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='exams', to='assessment.question', verbose_name='Câu hỏi trong đề'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('single', 'Trắc nghiệm 1 đáp án'), ('multiple', 'Trắc nghiệm nhiều đáp án'), ('essay', 'Tự luận (Văn bản)'), ('image_upload', 'Trả lời bằng hình ảnh')], max_length=20, verbose_name='Loại câu hỏi'),
        ),
    ]
