# Generated by Django 5.2.7 on 2026-04-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_exam_questions_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
