# Generated by Django 5.2.7 on 2026-09-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsubmission',
            options={'ordering': ['-submitted_at', '-id'], 'verbose_name': 'Kết quả bài thi', 'verbose_name_plural': 'Kết quả bài thi'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Câu trả lời', 'verbose_name_plural': 'Câu trả lời'},
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='body_text',
            field=models.TextField(default='Chứng nhận đã hoàn thành chương trình «{exam_title}» với kết quả {score} điểm. Cấp tại JustPlay ngày {date}.', help_text='Có thể dùng {name}, {exam_title}, {score}, {date}, {code}.', verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='presented_label',
            field=models.CharField(default='This certificate is proudly presented to', max_length=160, verbose_name='Dòng giới thiệu'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='ribbon_text',
            field=models.CharField(default='OF COMPLETION', max_length=80, verbose_name='Dòng phụ'),
        ),
    ]
