# Generated by Django 5.2.7 on 2026-09-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_examsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='company_name',
            field=models.CharField(default='CÔNG TY TNHH JUST PLAY', max_length=160, verbose_name='Tên công ty'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='tax_code',
            field=models.CharField(default='0316184836', max_length=32, verbose_name='Mã số thuế'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='thank_you_text',
            field=models.TextField(default='JustPlay trân trọng cảm ơn Anh/Chị đã hoàn thành chương trình đào tạo và đóng góp cho sự phát triển của công ty.', verbose_name='Lời cảm ơn'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='hr_signer_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Tên trưởng phòng HCNS'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='hr_signer_title',
            field=models.CharField(default='Trưởng phòng HCNS', max_length=120, verbose_name='Chức danh HCNS'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='hr_signature',
            field=models.ImageField(blank=True, help_text='Ảnh PNG nền trong suốt, chữ ký đỏ/đen.', null=True, upload_to='certificates/signatures/', verbose_name='Chữ ký PNG — Trưởng phòng HCNS'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='director_signer_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Tên giám đốc'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='director_signer_title',
            field=models.CharField(default='Giám đốc', max_length=120, verbose_name='Chức danh giám đốc'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='director_signature',
            field=models.ImageField(blank=True, help_text='Ảnh PNG nền trong suốt, chữ ký đỏ/đen.', null=True, upload_to='certificates/signatures/', verbose_name='Chữ ký PNG — Giám đốc'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='body_text',
            field=models.TextField(default='Chứng nhận đã hoàn thành chương trình «{exam_title}» với kết quả {score} điểm. Cấp tại JustPlay ngày {date}.', help_text='Có thể dùng {name}, {exam_title}, {score}, {date}, {code}.', verbose_name='Mô tả khóa học'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='presented_label',
            field=models.CharField(default='đã hoàn thành chương trình đào tạo nội bộ', max_length=160, verbose_name='Dòng giới thiệu'),
        ),
    ]
