# Generated by Django 5.2.7 on 2026-09-19 13:00

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F, Max


def scale_scores_to_100(apps, schema_editor):
    Question = apps.get_model('assessment', 'Question')
    Exam = apps.get_model('assessment', 'Exam')
    ExamSubmission = apps.get_model('assessment', 'ExamSubmission')
    UserAnswer = apps.get_model('assessment', 'UserAnswer')
    Certificate = apps.get_model('assessment', 'Certificate')

    max_pts = Question.objects.aggregate(m=Max('points'))['m'] or 0
    if max_pts > 10:
        Exam.objects.filter(pass_score__lt=10).update(pass_score=50)
        return

    Question.objects.update(points=F('points') * 10)
    Exam.objects.update(pass_score=F('pass_score') * 10)
    Exam.objects.filter(pass_score=0).update(pass_score=50)
    ExamSubmission.objects.update(
        auto_score=F('auto_score') * 10,
        manual_score=F('manual_score') * 10,
    )
    UserAnswer.objects.update(graded_score=F('graded_score') * 10)
    Certificate.objects.update(score=F('score') * 10)


def unscale_scores(apps, schema_editor):
    Question = apps.get_model('assessment', 'Question')
    Exam = apps.get_model('assessment', 'Exam')
    ExamSubmission = apps.get_model('assessment', 'ExamSubmission')
    UserAnswer = apps.get_model('assessment', 'UserAnswer')
    Certificate = apps.get_model('assessment', 'Certificate')
    max_pts = Question.objects.aggregate(m=Max('points'))['m'] or 0
    if max_pts <= 10:
        return
    Question.objects.update(points=F('points') / 10)
    Exam.objects.update(pass_score=F('pass_score') / 10)
    ExamSubmission.objects.update(
        auto_score=F('auto_score') / 10,
        manual_score=F('manual_score') / 10,
    )
    UserAnswer.objects.update(graded_score=F('graded_score') / 10)
    Certificate.objects.update(score=F('score') / 10)


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_certificatetemplate_coursera_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='retry_of',
            field=models.ForeignKey(
                blank=True,
                help_text='Để trống nếu đây là đề chính. Đề thi lại dùng khi học viên dưới 50 điểm.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='retry_exams',
                to='assessment.exam',
                verbose_name='Đề thi lại của',
            ),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pass_score',
            field=models.FloatField(
                default=50.0,
                help_text='Thang 100. Từ 50 điểm trở lên thì cấp chứng chỉ. Dưới 50 thì học lại và làm bài thi lại.',
                verbose_name='Điểm đạt (cấp chứng chỉ)',
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(default=4.0, verbose_name='Điểm số'),
        ),
        migrations.RunPython(scale_scores_to_100, unscale_scores),
    ]
