# Generated by Django 5.2.7 on 2026-09-19 13:20

import django.db.models.deletion
from django.db import migrations, models


def seed_course_descriptions(apps, schema_editor):
    Course = apps.get_model('training', 'Course')
    CertificateTemplate = apps.get_model('assessment', 'CertificateTemplate')
    Desc = apps.get_model('assessment', 'CertificateTemplateDescription')
    tmpl = (
        CertificateTemplate.objects.filter(is_default=True).first()
        or CertificateTemplate.objects.order_by('id').first()
    )
    if tmpl is None:
        return
    for course in Course.objects.exclude(description='').iterator():
        text = (course.description or '').strip()
        if not text:
            continue
        Desc.objects.get_or_create(
            template=tmpl,
            course_id=course.id,
            defaults={'description': text},
        )


def unseed_course_descriptions(apps, schema_editor):
    Desc = apps.get_model('assessment', 'CertificateTemplateDescription')
    Desc.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_score_scale_100_retry_exam'),
        ('training', '0007_lesson_type_default_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='body_text',
            field=models.TextField(
                default='Chứng nhận đã hoàn thành chương trình «{exam_title}» với kết quả {score} điểm. Cấp tại JustPlay ngày {date}.',
                help_text='Dùng khi khóa/kỳ thi chưa có mô tả riêng. Có thể dùng {name}, {exam_title}, {score}, {date}, {code}.',
                verbose_name='Mô tả mặc định',
            ),
        ),
        migrations.CreateModel(
            name='CertificateTemplateDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(
                    help_text='Hiện trên chứng chỉ của khóa/kỳ thi này. Có thể dùng {name}, {exam_title}, {score}, {date}, {code}.',
                    verbose_name='Mô tả khóa học',
                )),
                ('course', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='certificate_descriptions',
                    to='training.course',
                    verbose_name='Khóa học',
                )),
                ('exam', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='certificate_descriptions',
                    to='assessment.exam',
                    verbose_name='Kỳ thi',
                )),
                ('template', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='course_descriptions',
                    to='assessment.certificatetemplate',
                    verbose_name='Mẫu chứng chỉ',
                )),
            ],
            options={
                'verbose_name': 'Mô tả khóa trên chứng chỉ',
                'verbose_name_plural': 'Mô tả khóa trên chứng chỉ',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatedescription',
            constraint=models.UniqueConstraint(
                condition=models.Q(('course__isnull', False)),
                fields=('template', 'course'),
                name='uniq_cert_desc_template_course',
            ),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplatedescription',
            constraint=models.UniqueConstraint(
                condition=models.Q(('exam__isnull', False)),
                fields=('template', 'exam'),
                name='uniq_cert_desc_template_exam',
            ),
        ),
        migrations.RunPython(seed_course_descriptions, unseed_course_descriptions),
    ]
