# Generated by Django 5.2.7 on 2026-04-16 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('cv_file', models.FileField(upload_to='candidate_cvs/', verbose_name='Hồ sơ CV (PDF/Word)')),
                ('status', models.CharField(choices=[('new', 'Mới nộp'), ('reviewing', 'Đang xem xét'), ('interviewing', 'Đang phỏng vấn'), ('offered', 'Trúng tuyển (Chờ nhận việc)'), ('hired', 'Đã nhận việc (Onboard)'), ('rejected', 'Từ chối')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('hr_note', models.TextField(blank=True, verbose_name='Ghi chú của HR')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nộp')),
            ],
            options={
                'verbose_name': 'Ứng viên',
                'verbose_name_plural': 'Ứng viên',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề tuyển dụng')),
                ('department', models.CharField(max_length=100, verbose_name='Khoa/Phòng ban')),
                ('position', models.CharField(choices=[('Bác Sĩ', 'Bác Sĩ'), ('Điều Dưỡng', 'Điều Dưỡng'), ('Dược Sĩ', 'Dược Sĩ'), ('Kỹ Thuật viên', 'Kỹ Thuật viên'), ('Khối Hỗ trợ', 'Khối Hỗ trợ')], max_length=50, verbose_name='Chức danh')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng cần tuyển')),
                ('description', models.TextField(verbose_name='Mô tả công việc')),
                ('requirements', models.TextField(blank=True, verbose_name='Yêu cầu ứng viên')),
                ('deadline', models.DateField(verbose_name='Hạn nộp hồ sơ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang mở tuyển')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vị trí tuyển dụng',
                'verbose_name_plural': 'Vị trí tuyển dụng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_time', models.DateTimeField(verbose_name='Thời gian phỏng vấn')),
                ('location', models.CharField(default='Phòng Họp Nhân sự', max_length=255, verbose_name='Địa điểm / Link Online')),
                ('result_notes', models.TextField(blank=True, verbose_name='Đánh giá sau phỏng vấn')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Kết quả (Đạt/Không Đạt)')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='recruitment.candidate', verbose_name='Ứng viên')),
                ('interviewers', models.ManyToManyField(related_name='interviews_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Hội đồng phỏng vấn')),
            ],
            options={
                'verbose_name': 'Lịch phỏng vấn',
                'verbose_name_plural': 'Lịch phỏng vấn',
                'ordering': ['interview_time'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.jobposting', verbose_name='Ứng tuyển vị trí'),
        ),
    ]
