# Generated by Django 5.2.7 on 2026-04-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('new', 'Mới nộp'), ('reviewing', 'Đang xem xét'), ('interviewing', 'Đang phỏng vấn'), ('offered', 'Trúng tuyển (Chờ nhận việc)'), ('hired', 'Đã nhận việc (Onboard)'), ('not_onboarded', 'Không Onboard (Boom job)'), ('rejected', 'Từ chối')], default='new', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
