# Generated by Django 5.2.7 on 2026-05-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='license_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú CCHN'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='new_license_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số GPHN/CCHN điều chỉnh'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='new_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí chuyên môn điều chỉnh'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='new_scope',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phạm vi hành nghề điều chỉnh'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='old_license_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số GPHN/CCHN cũ'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='old_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí chuyên môn cũ'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='old_scope',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phạm vi hành nghề cũ'),
        ),
    ]
