# Generated by Django 5.2.7 on 2026-05-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate_license_note_candidate_new_license_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='new_license_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='new_position',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='new_scope',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='old_license_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='old_position',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='old_scope',
        ),
        migrations.AddField(
            model_name='candidate',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số GPHN/CCHN'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_practice_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TG hành nghề tại CS khác'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='practice_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TG hành nghề tại CS KBCB'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='professional_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí chuyên môn'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='scope_of_practice',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phạm vi hành nghề'),
        ),
    ]
