# Generated by Django 5.2.7 on 2026-05-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_remove_candidate_new_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='position',
            field=models.CharField(choices=[('Công nhân may', 'Công nhân may'), ('Công nhân cắt', 'Công nhân cắt'), ('Thợ in/thêu', 'Thợ in/thêu'), ('Nhân viên QC', 'Nhân viên QC'), ('Đóng gói', 'Đóng gói'), ('KHSX', 'KHSX'), ('Kho vận', 'Kho vận'), ('Kỹ thuật rập', 'Kỹ thuật rập'), ('Thiết kế mẫu', 'Thiết kế mẫu'), ('Tổ trưởng', 'Tổ trưởng'), ('HR / HCNS', 'HR / HCNS'), ('Kế toán', 'Kế toán'), ('Kinh doanh', 'Kinh doanh'), ('IT', 'IT')], max_length=50, verbose_name='Chức danh'),
        ),
    ]
