# Generated by Django 5.2.7 on 2026-10-06 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0118_recruitment_under_hrm'),
        ('recruitment', '0006_update_position_choices'),
        ('service_requests', '0011_general_execution_step_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_candidate', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản nhân viên'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Người đề xuất'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='Lý do loại / không nhận việc'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('hr', 'HR nhập hồ sơ'), ('referral', 'Quản lý đề xuất'), ('walk_in', 'Ứng viên tự đến'), ('online', 'Kênh online')], default='hr', max_length=20, verbose_name='Nguồn hồ sơ'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Đổi trạng thái lúc'),
        ),
        migrations.AddField(
            model_name='interview',
            name='result',
            field=models.CharField(choices=[('pending', 'Chưa có kết quả'), ('pass', 'Đạt'), ('fail', 'Không đạt')], default='pending', max_length=10, verbose_name='Kết quả'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày đóng'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='service_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posting', to='service_requests.servicerequest', verbose_name='Đề xuất tuyển dụng'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('open', 'Đang tuyển'), ('paused', 'Tạm dừng'), ('closed', 'Đã đóng')], db_index=True, default='draft', max_length=10, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='hrm.department', verbose_name='Phòng ban'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_file',
            field=models.FileField(blank=True, upload_to='candidate_cvs/', verbose_name='Hồ sơ CV'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='recruitment.jobposting', verbose_name='Ứng tuyển vị trí'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='license_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='other_practice_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='practice_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='professional_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='scope_of_practice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('new', 'Mới'), ('reviewing', 'Chờ quản lý đánh giá'), ('interviewing', 'Phỏng vấn'), ('offered', 'Trúng tuyển'), ('hired', 'Đã nhận việc'), ('not_onboarded', 'Không nhận việc'), ('rejected', 'Loại')], db_index=True, default='new', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(blank=True, related_name='interviews_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Người phỏng vấn'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='result_notes',
            field=models.TextField(blank=True, verbose_name='Nhận xét phỏng vấn'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn nộp hồ sơ'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phòng ban (cũ)'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả công việc'),
        ),
        migrations.CreateModel(
            name='CandidateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Tạo hồ sơ'), ('status', 'Đổi trạng thái'), ('note', 'Ghi chú'), ('review', 'Đánh giá hồ sơ'), ('interview', 'Phỏng vấn'), ('onboard', 'Onboard')], max_length=20, verbose_name='Loại')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_events', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recruitment.candidate', verbose_name='Ứng viên')),
            ],
            options={
                'verbose_name': 'Lịch sử ứng viên',
                'verbose_name_plural': 'Lịch sử ứng viên',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('recommend', 'Đề xuất phỏng vấn'), ('consider', 'Cân nhắc'), ('not_suitable', 'Không phù hợp')], max_length=20, verbose_name='Kết luận')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Điểm hồ sơ (1–5)')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recruitment.candidate', verbose_name='Ứng viên')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
            ],
            options={
                'verbose_name': 'Đánh giá ứng viên',
                'verbose_name_plural': 'Đánh giá ứng viên',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'reviewer'), name='uniq_candidate_reviewer')],
            },
        ),
    ]
