# Generated by Django 5.2.7 on 2026-10-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_redesign_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='hr_note',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='license_note',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='other_practice_time',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='practice_time',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='professional_position',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='scope_of_practice',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='is_active',
        ),
    ]
