# Generated by Django 5.2.7 on 2026-10-07 01:53

import django.db.models.deletion
import django.utils.timezone
import recruitment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_remove_legacy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cv', 'CV / Hồ sơ xin việc'), ('other', 'Giấy tờ khác')], default='cv', max_length=10, verbose_name='Loại')),
                ('file', models.FileField(max_length=255, storage=recruitment.models.candidate_file_storage, upload_to=recruitment.models.candidate_file_upload_to, verbose_name='File')),
                ('original_name', models.CharField(max_length=255, verbose_name='Tên file gốc')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Dung lượng')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tải lên lúc')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='recruitment.candidate', verbose_name='Ứng viên')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_files_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Hồ sơ đính kèm',
                'verbose_name_plural': 'Hồ sơ đính kèm',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
