# Generated by Django 5.2.7 on 2026-10-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_move_cv_to_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cv_file',
        ),
        migrations.AlterField(
            model_name='candidateevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Tạo hồ sơ'), ('status', 'Đổi trạng thái'), ('note', 'Ghi chú'), ('review', 'Đánh giá hồ sơ'), ('interview', 'Phỏng vấn'), ('onboard', 'Onboard'), ('file', 'Hồ sơ đính kèm')], max_length=20, verbose_name='Loại'),
        ),
    ]
