# Generated by Django 5.2.7 on 2026-10-07 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0118_recruitment_under_hrm'),
        ('recruitment', '0012_remove_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='target_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='hrm.division', verbose_name='Bộ phận'),
        ),
    ]
