# Generated by Django 5.2.7 on 2026-10-07 03:25

from datetime import timedelta

from django.db import migrations, models
from django.db.models import F

DEFAULT_DURATION = timedelta(minutes=60)


def fill_end_time(apps, schema_editor):
    Interview = apps.get_model('recruitment', 'Interview')
    Interview.objects.filter(end_time__isnull=True).update(end_time=F('interview_time') + DEFAULT_DURATION)


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_candidate_gender_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_time',
            field=models.DateTimeField(verbose_name='Bắt đầu'),
        ),
        migrations.RunPython(fill_end_time, migrations.RunPython.noop),
    ]
