# Generated by Django 5.2.7 on 2026-10-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_interview_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFileKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='Mã')),
                ('is_cv', models.BooleanField(default=False, verbose_name='Là CV')),
                ('is_system', models.BooleanField(default=False, verbose_name='Hệ thống')),
            ],
            options={
                'verbose_name': 'Loại hồ sơ',
                'verbose_name_plural': 'Loại hồ sơ',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='Mã')),
                ('is_system', models.BooleanField(default=False, verbose_name='Hệ thống')),
            ],
            options={
                'verbose_name': 'Nguồn hồ sơ',
                'verbose_name_plural': 'Nguồn hồ sơ',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(default='hr', max_length=20, verbose_name='Nguồn hồ sơ'),
        ),
        migrations.AlterField(
            model_name='candidatefile',
            name='kind',
            field=models.CharField(default='cv', max_length=20, verbose_name='Loại'),
        ),
        migrations.CreateModel(
            name='InterviewLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ / ghi chú')),
            ],
            options={
                'verbose_name': 'Địa điểm họp',
                'verbose_name_plural': 'Địa điểm họp',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_interview_location_name')],
            },
        ),
    ]
