# Generated by Django 5.2.7 on 2026-10-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_seed_recruitment_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatereview',
            name='decision',
            field=models.CharField(choices=[('recommend', 'Đạt'), ('consider', 'Cân nhắc'), ('not_suitable', 'Không đạt')], max_length=20, verbose_name='Kết luận'),
        ),
    ]
