# Generated by Django 5.2.7 on 2026-10-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_review_decision_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lương đến (VNĐ/tháng)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lương từ (VNĐ/tháng)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_negotiable',
            field=models.BooleanField(default=False, verbose_name='Lương thỏa thuận'),
        ),
    ]
