# Generated by Django 5.2.7 on 2026-10-08 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_job_salary_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='final_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm duyệt'),
        ),
        migrations.AddField(
            model_name='interview',
            name='final_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_final_approved', to=settings.AUTH_USER_MODEL, verbose_name='Giám đốc duyệt'),
        ),
        migrations.AddField(
            model_name='interview',
            name='final_notes',
            field=models.TextField(blank=True, verbose_name='Nhận xét giám đốc'),
        ),
        migrations.AddField(
            model_name='interview',
            name='final_result',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending', 'Chờ giám đốc duyệt'), ('pass', 'Giám đốc duyệt Đạt'), ('fail', 'Giám đốc duyệt Không đạt')], db_index=True, default='', max_length=10, verbose_name='Duyệt cấp 2'),
        ),
    ]
