# Generated by Django 5.2.7 on 2026-07-16 03:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kho_npl', '0026_material_base_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BomVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(default='v1', max_length=40, verbose_name='Phiên bản')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang dùng'), ('archived', 'Lưu trữ')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái')),
                ('overhead_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Phần trăm cộng thêm trên (NVL + nhân công).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Phụ phí (%)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_xuat_bom_versions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiên bản BOM',
                'verbose_name_plural': 'Phiên bản BOM',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Định mức')),
                ('scrap_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Hao hụt (%)')),
                ('size_code', models.CharField(blank=True, default='', help_text='Để trống = áp dụng mọi size.', max_length=20, verbose_name='Size')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='san_xuat_bom_lines', to='kho_npl.material', verbose_name='Nguyên phụ liệu')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='san_xuat.bomversion', verbose_name='BOM')),
            ],
            options={
                'verbose_name': 'Dòng BOM',
                'verbose_name_plural': 'Dòng BOM',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CostingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costing_snapshots', to='san_xuat.bomversion', verbose_name='BOM')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_xuat_costing_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bản chốt costing',
                'verbose_name_plural': 'Bản chốt costing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=10, verbose_name='Thứ tự')),
                ('process_name', models.CharField(max_length=120, verbose_name='Tên công đoạn')),
                ('norm_per_hour', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Định mức (cái/giờ)')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Chi phí giờ (VNĐ)')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='san_xuat.bomversion', verbose_name='BOM')),
            ],
            options={
                'verbose_name': 'Công đoạn',
                'verbose_name_plural': 'Công đoạn',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductTechDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên sản phẩm (snapshot)')),
                ('product_image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Ảnh sản phẩm')),
                ('kv_product_id', models.BigIntegerField(blank=True, null=True, verbose_name='KiotViet product id')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_xuat_tech_docs', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Hồ sơ tài liệu SX',
                'verbose_name_plural': 'Hồ sơ tài liệu SX',
                'ordering': ['product_code'],
            },
        ),
        migrations.AddField(
            model_name='bomversion',
            name='tech_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_versions', to='san_xuat.producttechdoc', verbose_name='Hồ sơ SX'),
        ),
        migrations.AddConstraint(
            model_name='bomversion',
            constraint=models.UniqueConstraint(fields=('tech_doc', 'version_label'), name='san_xuat_bom_unique_label_per_doc'),
        ),
    ]
