# Generated by Django 5.2.7 on 2026-07-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0026_material_base_price'),
        ('san_xuat', '0002_hub_demo_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxmaterialissuerequest',
            name='stock_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issue_requests', to='kho_npl.stockissue', verbose_name='Phiếu xuất NPL'),
        ),
    ]
