# Generated by Django 5.2.7 on 2026-07-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0003_sxmaterialissuerequest_stock_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxproductionstat',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận')], db_index=True, default='draft', max_length=20),
        ),
    ]
