# Generated by Django 5.2.7 on 2026-07-16 09:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0004_sxproductionstat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxqcrequest',
            name='production_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_requests', to='san_xuat.sxproductionstat', verbose_name='TKSX nguồn'),
        ),
        migrations.AddField(
            model_name='sxqcstandardset',
            name='defect_tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6, verbose_name='Ngưỡng lỗi cho phép (%)'),
        ),
        migrations.AddField(
            model_name='sxqcstandardset',
            name='stage_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Công đoạn'),
        ),
        migrations.CreateModel(
            name='SxQcAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã cảnh báo')),
                ('alert_type', models.CharField(choices=[('defect_rate_exceeded', 'Tỷ lệ lỗi vượt ngưỡng'), ('qc_inspection_fail', 'Phiếu kiểm tra không đạt')], db_index=True, max_length=30)),
                ('process_name', models.CharField(blank=True, default='', max_length=120)),
                ('defect_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('tolerance_limit', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=6)),
                ('qty_good', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('qty_defect', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Mở'), ('acknowledged', 'Đã xử lý'), ('closed', 'Đóng')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_alerts', to='san_xuat.sxproductionorder')),
                ('production_stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_alerts', to='san_xuat.sxproductionstat')),
                ('qc_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='san_xuat.sxqcinspection')),
                ('qc_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='san_xuat.sxqcrequest')),
            ],
            options={
                'verbose_name': 'Cảnh báo QC',
                'verbose_name_plural': 'Cảnh báo QC',
                'ordering': ['-created_at'],
            },
        ),
    ]
