# Generated by Django 5.2.7 on 2026-07-16 09:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0005_qc_q4_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxfgreceiptrequest',
            name='kv_purchase_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Mã phiếu nhập KV'),
        ),
        migrations.AddField(
            model_name='sxfgreceiptrequest',
            name='kv_purchase_kiotviet_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='KV purchase id'),
        ),
        migrations.AddField(
            model_name='sxfgreceiptrequest',
            name='production_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_receipt_requests', to='san_xuat.sxproductionstat', verbose_name='TKSX nguồn'),
        ),
        migrations.AlterField(
            model_name='sxfgreceiptrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Đã gửi'), ('done', 'Hoàn thành'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SxQcInspectionDefectLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_lines', to='san_xuat.sxqcdefect')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_lines', to='san_xuat.sxqcinspection')),
            ],
            options={
                'verbose_name': 'Dòng lỗi PKT',
                'verbose_name_plural': 'Dòng lỗi PKT',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SxQcInspectionCriteriaLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, default='', max_length=255)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('is_pass', models.BooleanField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_lines', to='san_xuat.sxqccriteria')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_lines', to='san_xuat.sxqcinspection')),
            ],
            options={
                'verbose_name': 'Dòng tiêu chí PKT',
                'verbose_name_plural': 'Dòng tiêu chí PKT',
                'ordering': ['id'],
                'unique_together': {('inspection', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='SxQcStandardCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_links', to='san_xuat.sxqccriteria')),
                ('standard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_links', to='san_xuat.sxqcstandardset')),
            ],
            options={
                'verbose_name': 'Tiêu chí trong bộ TC',
                'verbose_name_plural': 'Tiêu chí trong bộ TC',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('standard_set', 'criteria')},
            },
        ),
    ]
