# Generated by Django 5.2.7 on 2026-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0006_d3_q3_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxoverallplan',
            name='source',
            field=models.CharField(choices=[('forecast', 'Dự báo / nhập tay'), ('sales_order', 'Từ đơn KV')], default='forecast', max_length=20),
        ),
        migrations.AddField(
            model_name='sxoverallplanline',
            name='kv_order_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Mã đơn KV'),
        ),
        migrations.AddField(
            model_name='sxoverallplanline',
            name='kv_order_kiotviet_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='KV order id'),
        ),
    ]
