# Generated by Django 5.2.7 on 2026-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0007_p0_p2_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxnplpurchaserequest',
            name='request_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày YC'),
        ),
        migrations.AlterField(
            model_name='sxnplpurchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Đã gửi'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='draft', max_length=20),
        ),
    ]
