# Generated by Django 5.2.7 on 2026-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0008_p3_npl_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxpurchaseorder',
            name='kv_purchase_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Mã phiếu nhập KV'),
        ),
        migrations.AddField(
            model_name='sxpurchaseorder',
            name='kv_purchase_kiotviet_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='KV purchase id'),
        ),
        migrations.AlterField(
            model_name='sxpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('received', 'Đã nhập')], db_index=True, default='draft', max_length=20),
        ),
    ]
