# Generated by Django 5.2.7 on 2026-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0009_p5_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxstandardcostsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã chốt')], db_index=True, default='draft', max_length=20),
        ),
    ]
