# Generated by Django 5.2.7 on 2026-07-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0010_c1_standard_cost_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxorderplancost',
            name='kv_order_kiotviet_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='KV order id'),
        ),
        migrations.AlterField(
            model_name='sxorderplancost',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã chốt')], db_index=True, default='draft', max_length=20),
        ),
    ]
