# Generated by Django 5.2.7 on 2026-07-16 10:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0011_c2_order_plan_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxorderplancostline',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
