# Generated by Django 5.2.7 on 2026-07-16 10:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0026_material_base_price'),
        ('san_xuat', '0012_c3_extra_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SxCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã loại CP')),
                ('name', models.CharField(max_length=120, verbose_name='Tên loại CP')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loại chi phí thêm',
                'verbose_name_plural': 'Loại chi phí thêm',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='sxdisassemblyorder',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disassembly_orders', to='san_xuat.sxproductionorder', verbose_name='LSX nguồn'),
        ),
        migrations.AddField(
            model_name='sxnplsurplus',
            name='disassembly_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_records', to='san_xuat.sxdisassemblyorder', verbose_name='LTD nguồn'),
        ),
        migrations.AddField(
            model_name='sxnplsurplus',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã nhập kho'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='sxnplsurplus',
            name='stock_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_surplus_records', to='kho_npl.stockadjustment', verbose_name='Phiếu ĐC kho'),
        ),
        migrations.AlterField(
            model_name='sxdisassemblyorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SxDisassemblyOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=60)),
                ('material_name', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='san_xuat.sxdisassemblyorder')),
            ],
            options={
                'verbose_name': 'Dòng tháo dỡ',
                'verbose_name_plural': 'Dòng tháo dỡ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SxOrderPlanCostLineExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_line_extras', to='san_xuat.sxcosttype')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typed_extras', to='san_xuat.sxorderplancostline')),
            ],
            options={
                'verbose_name': 'CP thêm theo loại',
                'verbose_name_plural': 'CP thêm theo loại',
                'ordering': ['cost_type__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('line', 'cost_type'), name='uniq_order_line_cost_type')],
            },
        ),
    ]
