# Generated by Django 5.2.7 on 2026-07-17 01:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0013_c4_c6_cost_types_disassembly_surplus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SxWorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã tổ/chuyền')),
                ('name', models.CharField(max_length=120)),
                ('capacity_per_day', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Năng lực/ngày')),
                ('uom_label', models.CharField(blank=True, default='SP', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Năng lực SX',
                'verbose_name_plural': 'Năng lực SX',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SxPackingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã ĐG')),
                ('pack_date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('carton_count', models.PositiveIntegerField(default=0, verbose_name='Số thùng/kiện')),
                ('lot_code', models.CharField(blank=True, default='', max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fg_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_records', to='san_xuat.sxfgreceiptrequest')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_records', to='san_xuat.sxproductionorder')),
            ],
            options={
                'verbose_name': 'Đóng gói',
                'verbose_name_plural': 'Đóng gói',
                'ordering': ['-pack_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SxSubcontractOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã GC')),
                ('vendor_name', models.CharField(max_length=200, verbose_name='Đơn vị gia công')),
                ('product_code', models.CharField(db_index=True, max_length=60)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('process_name', models.CharField(blank=True, default='', max_length=120)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('order_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('sent', 'Đã gửi GC'), ('done', 'Hoàn thành'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontract_orders', to='san_xuat.sxproductionorder')),
            ],
            options={
                'verbose_name': 'Thuê gia công',
                'verbose_name_plural': 'Thuê gia công',
                'ordering': ['-order_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SxWorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã giao việc')),
                ('process_name', models.CharField(blank=True, default='', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('assignee_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Người/tổ nhận')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Đang giao'), ('done', 'Hoàn thành'), ('cancelled', 'Hủy')], db_index=True, default='open', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to='san_xuat.sxproductionorder')),
            ],
            options={
                'verbose_name': 'Giao việc SX',
                'verbose_name_plural': 'Giao việc SX',
                'ordering': ['-created_at'],
            },
        ),
    ]
