# Generated by Django 5.2.7 on 2026-07-17 01:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0014_phase3_ops_extensions'),
        ('tasks', '0007_phase3_ops_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sxpackingrecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sxsubcontractorder',
            name='qty_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='SL nhận lại'),
        ),
        migrations.AddField(
            model_name='sxsubcontractorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sxsubcontractorder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sxworkassignment',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_work_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận (portal)'),
        ),
        migrations.AddField(
            model_name='sxworkassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sxworkassignment',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='san_xuat.sxworkcenter', verbose_name='Tổ/chuyền'),
        ),
        migrations.AddField(
            model_name='sxworkassignment',
            name='work_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_assignments', to='tasks.worktask', verbose_name='Công việc'),
        ),
        migrations.AddField(
            model_name='sxworkcenter',
            name='team_label',
            field=models.CharField(blank=True, default='', help_text='Khớp field team_label trên TKSX để tính tải thực tế.', max_length=80, verbose_name='Nhãn tổ (khớp TKSX)'),
        ),
        migrations.AlterField(
            model_name='sxsubcontractorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('sent', 'Đã gửi GC'), ('received', 'Đã nhận lại'), ('done', 'Hoàn thành'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SxPackingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, default='', max_length=60, verbose_name='SKU')),
                ('size_label', models.CharField(blank=True, default='', max_length=40, verbose_name='Size')),
                ('color_label', models.CharField(blank=True, default='', max_length=40, verbose_name='Màu')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('carton_count', models.PositiveIntegerField(default=0)),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='san_xuat.sxpackingrecord')),
            ],
            options={
                'verbose_name': 'Dòng đóng gói',
                'verbose_name_plural': 'Dòng đóng gói',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SxSubcontractMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Xuất đi GC'), ('in', 'Nhận về')], db_index=True, default='out', max_length=10)),
                ('material_code', models.CharField(max_length=60, verbose_name='Mã NVL/BTP')),
                ('material_name', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('uom_label', models.CharField(blank=True, default='SP', max_length=40)),
                ('lot_code', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='san_xuat.sxsubcontractorder')),
            ],
            options={
                'verbose_name': 'Dòng NVL/BTP GC',
                'verbose_name_plural': 'Dòng NVL/BTP GC',
                'ordering': ['direction', 'pk'],
            },
        ),
    ]
