# Generated by Django 5.2.7 on 2026-07-17 02:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0026_material_base_price'),
        ('san_xuat', '0015_phase3_thicken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomline',
            name='substitute_material',
            field=models.ForeignKey(blank=True, help_text='Khi tồn NVL chính thiếu, YCX có thể dùng mã này.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_xuat_bom_substitutes', to='kho_npl.material', verbose_name='NVL thay thế'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='piece_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Lương sản phẩm = SL đạt TKSX × đơn giá.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá SP (VNĐ/cái)'),
        ),
        migrations.AddField(
            model_name='sxdetailplanline',
            name='team_label',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Tổ/chuyền'),
        ),
        migrations.AddField(
            model_name='sxdetailplanline',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_plan_lines', to='san_xuat.sxworkcenter', verbose_name='Năng lực SX'),
        ),
        migrations.AddField(
            model_name='sxmaterialplanline',
            name='qty_expected_inbound',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Dự kiến về (PO mở)'),
        ),
        migrations.AddField(
            model_name='sxproductionstat',
            name='color_label',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Màu'),
        ),
        migrations.AddField(
            model_name='sxproductionstat',
            name='size_label',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='sxproductionstat',
            name='sku_code',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='sxqcrequest',
            name='color_label',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Màu'),
        ),
        migrations.AddField(
            model_name='sxqcrequest',
            name='size_label',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='sxqcrequest',
            name='sku_code',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='sxsubcontractorder',
            name='stock_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_subcontract_orders', to='kho_npl.stockadjustment', verbose_name='Phiếu ĐC kho (nhận về)'),
        ),
        migrations.AddField(
            model_name='sxsubcontractorder',
            name='stock_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_subcontract_orders', to='kho_npl.stockissue', verbose_name='Phiếu xuất kho (gửi GC)'),
        ),
        migrations.AddField(
            model_name='sxwipreturn',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sxwipreturn',
            name='from_process',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Từ CĐ (đang giữ)'),
        ),
        migrations.AddField(
            model_name='sxwipreturn',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='sxwipreturn',
            name='to_process',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Về CĐ (sửa)'),
        ),
        migrations.CreateModel(
            name='SxDowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã dừng')),
                ('team_label', models.CharField(blank=True, default='', max_length=80)),
                ('event_date', models.DateField()),
                ('reason', models.CharField(max_length=200, verbose_name='Lý do dừng')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='Số phút')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_events', to='san_xuat.sxproductionorder')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_events', to='san_xuat.sxworkcenter')),
            ],
            options={
                'verbose_name': 'Dừng chuyền',
                'verbose_name_plural': 'Dừng chuyền',
                'ordering': ['-event_date', '-pk'],
            },
        ),
    ]
