# Generated by Django 5.2.7 on 2026-07-17 02:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0016_ops_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SxProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã nhóm')),
                ('name', models.CharField(max_length=120, verbose_name='Tên nhóm')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Nhóm sản phẩm',
                'verbose_name_plural': 'Nhóm sản phẩm',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='processstep',
            name='std_time_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Thời gian chuẩn một sản phẩm ở công đoạn này.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Chuẩn giờ (phút/cái)'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_steps', to='san_xuat.sxworkcenter', verbose_name='Tổ / máy (NL)'),
        ),
        migrations.AddField(
            model_name='sxproductionorder',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='Tách khỏi LSX đại trà (không tính capacity/MRP cứng nếu filter).', verbose_name='LSX mẫu / prototype'),
        ),
        migrations.AddField(
            model_name='sxsubcontractorder',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Chi phí GC đưa vào giá thành thực tế.', max_digits=14, verbose_name='Phí gia công (VNĐ)'),
        ),
        migrations.CreateModel(
            name='SxActualCostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã GT thực')),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('subcontract_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('qty_basis', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='SL cơ sở (qty_done)')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('closed', 'Đã chốt')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_cost_sheets', to='san_xuat.sxproductionorder')),
            ],
            options={
                'verbose_name': 'Giá thành thực tế',
                'verbose_name_plural': 'Giá thành thực tế',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SxNcrCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã NCR')),
                ('disposition', models.CharField(choices=[('rework', 'Sửa hàng (rework)'), ('scrap', 'Phế'), ('remake', 'Tái sản xuất'), ('use_as_is', 'Chấp nhận dùng')], default='rework', max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('process_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('done', 'Hoàn tất'), ('cancelled', 'Hủy')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_cases', to='san_xuat.sxqcalert')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncr_cases', to='san_xuat.sxproductionorder')),
                ('remake_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_remake_sources', to='san_xuat.sxproductionorder', verbose_name='LSX tái SX')),
                ('rework_stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_reworks', to='san_xuat.sxproductionstat', verbose_name='TKSX rework')),
            ],
            options={
                'verbose_name': 'NCR / xử lý QC',
                'verbose_name_plural': 'NCR / xử lý QC',
                'ordering': ['-created_at'],
            },
        ),
    ]
