# Generated by Django 5.2.7 on 2026-07-17 03:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0028_thicken_ops_wip_ycx_hr'),
        ('san_xuat', '0017_factory_ops_gaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='SxTeamHrMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('team_label', models.CharField(max_length=80, unique=True, verbose_name='Nhãn tổ (TKSX)')),
                ('employee_code', models.CharField(blank=True, default='', max_length=40, verbose_name='Mã NV')),
                ('employee_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Tên NV / tổ')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Map tổ → nhân sự',
                'verbose_name_plural': 'Map tổ → nhân sự',
                'ordering': ['team_label'],
            },
        ),
        migrations.AlterModelOptions(
            name='sxfgreceiptrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'Yêu cầu nhập thành phẩm', 'verbose_name_plural': 'Yêu cầu nhập thành phẩm'},
        ),
        migrations.AlterModelOptions(
            name='sxmaterialplanline',
            options={'ordering': ['id'], 'verbose_name': 'Dòng kế hoạch nguyên phụ liệu', 'verbose_name_plural': 'Dòng kế hoạch nguyên phụ liệu'},
        ),
        migrations.AlterModelOptions(
            name='sxncrcase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Xử lý hàng không đạt', 'verbose_name_plural': 'Xử lý hàng không đạt'},
        ),
        migrations.AlterModelOptions(
            name='sxwiphandover',
            options={'ordering': ['-handover_date'], 'verbose_name': 'Bàn giao bán thành phẩm', 'verbose_name_plural': 'Bàn giao bán thành phẩm'},
        ),
        migrations.AlterModelOptions(
            name='sxwipreturn',
            options={'ordering': ['-return_date'], 'verbose_name': 'Trả lại bán thành phẩm', 'verbose_name_plural': 'Trả lại bán thành phẩm'},
        ),
        migrations.AddField(
            model_name='sxmaterialissuerequestline',
            name='preferred_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ycx_preferred_lines', to='kho_npl.warehouselocation', verbose_name='Vị trí ưu tiên'),
        ),
        migrations.AlterField(
            model_name='sxdisassemblyorder',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disassembly_orders', to='san_xuat.sxproductionorder', verbose_name='Lệnh sản xuất nguồn'),
        ),
        migrations.AlterField(
            model_name='sxfgreceiptrequest',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Mã yêu cầu nhập thành phẩm'),
        ),
        migrations.AlterField(
            model_name='sxfgreceiptrequest',
            name='production_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_receipt_requests', to='san_xuat.sxproductionstat', verbose_name='Thống kê sản xuất nguồn'),
        ),
        migrations.AlterField(
            model_name='sxmaterialissuerequest',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Mã yêu cầu xuất'),
        ),
        migrations.AlterField(
            model_name='sxmaterialplan',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Mã kế hoạch nguyên phụ liệu'),
        ),
        migrations.AlterField(
            model_name='sxncrcase',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Mã xử lý không đạt'),
        ),
        migrations.AlterField(
            model_name='sxncrcase',
            name='disposition',
            field=models.CharField(choices=[('rework', 'Sửa hàng'), ('scrap', 'Phế'), ('remake', 'Tái sản xuất'), ('use_as_is', 'Chấp nhận dùng')], default='rework', max_length=20),
        ),
        migrations.AlterField(
            model_name='sxncrcase',
            name='remake_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_remake_sources', to='san_xuat.sxproductionorder', verbose_name='Lệnh tái sản xuất'),
        ),
        migrations.AlterField(
            model_name='sxncrcase',
            name='rework_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncr_reworks', to='san_xuat.sxproductionstat', verbose_name='Thống kê sản xuất (sửa hàng)'),
        ),
        migrations.AlterField(
            model_name='sxproductionorder',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Mã lệnh sản xuất'),
        ),
        migrations.AlterField(
            model_name='sxproductionorder',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='Tách khỏi lệnh sản xuất đại trà (có thể lọc khi tính năng lực).', verbose_name='Lệnh sản xuất mẫu'),
        ),
        migrations.AlterField(
            model_name='sxproductionstat',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Mã thống kê sản xuất'),
        ),
        migrations.AlterField(
            model_name='sxqcrequest',
            name='production_stat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_requests', to='san_xuat.sxproductionstat', verbose_name='Thống kê sản xuất nguồn'),
        ),
        migrations.AlterField(
            model_name='sxsubcontractmaterialline',
            name='material_code',
            field=models.CharField(max_length=60, verbose_name='Mã nguyên phụ liệu / bán thành phẩm'),
        ),
        migrations.AlterField(
            model_name='sxwipreturn',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Mã trả bán thành phẩm'),
        ),
        migrations.AlterField(
            model_name='sxwipreturn',
            name='from_process',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Từ công đoạn (đang giữ)'),
        ),
        migrations.AlterField(
            model_name='sxwipreturn',
            name='to_process',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Về công đoạn (sửa)'),
        ),
        migrations.AlterField(
            model_name='sxworkcenter',
            name='team_label',
            field=models.CharField(blank=True, default='', help_text='Khớp field team_label trên TKSX để tính tải thực tế.', max_length=80, verbose_name='Nhãn tổ (khớp thống kê sản xuất)'),
        ),
        migrations.CreateModel(
            name='SxWipBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('process_name', models.CharField(max_length=120, verbose_name='Công đoạn')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_balances', to='san_xuat.sxproductionorder')),
            ],
            options={
                'verbose_name': 'Tồn bán thành phẩm theo công đoạn',
                'verbose_name_plural': 'Tồn bán thành phẩm theo công đoạn',
                'ordering': ['production_order_id', 'process_name'],
                'constraints': [models.UniqueConstraint(fields=('production_order', 'process_name'), name='uniq_sx_wip_balance_mo_process')],
            },
        ),
    ]
