# Generated by Django 5.2.7 on 2026-07-22 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0022_sxgeneralsettings_ops_prefixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechDocDesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='san_xuat/design/%Y/%m/', verbose_name='Tệp')),
                ('title', models.CharField(blank=True, default='', help_text='Để trống = dùng tên file.', max_length=200, verbose_name='Tiêu đề')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tech_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_files', to='san_xuat.producttechdoc', verbose_name='Hồ sơ SX')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_xuat_design_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Tài liệu thiết kế',
                'verbose_name_plural': 'Tài liệu thiết kế',
                'ordering': ['-uploaded_at', '-pk'],
            },
        ),
    ]
