# Generated by Django 5.2.7 on 2026-07-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0023_tech_doc_design_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttechdoc',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Mô tả kỹ thuật, yêu cầu sản xuất, lưu ý…', verbose_name='Mô tả chi tiết'),
        ),
    ]
