# Generated by Django 5.x

from django.db import migrations, models


DEFAULT_PROCESS_NAMES = [
    ("Ủi", 10),
    ("Kiểm", 20),
    ("Gấp xếp", 30),
    ("Cắt chỉ", 40),
    ("Kiểm lỗi", 50),
    ("Kiểm hàng", 60),
    ("Diễu đáy sau", 70),
    ("Diễu đáy trước", 80),
    ("Diễu dây", 90),
    ("Tra tay", 100),
    ("Tra bo cổ", 110),
    ("Tra bo tay", 120),
    ("Ép logo", 130),
    ("Ép nhãn size", 140),
    ("Ép lai", 150),
    ("Vắt sườn", 160),
    ("Vắt vai", 170),
    ("Ráp đáy", 180),
    ("Ráp sườn", 190),
    ("Ráp vai", 200),
    ("May dây cổ", 210),
    ("Nối bo cổ", 220),
    ("Nhiễu cổ trước", 230),
    ("Dán tem gấp xếp", 240),
    ("Bấm mạc", 250),
    ("Vô thun quần", 260),
    ("Dập lưng quần", 270),
    ("Lấy dấu đóng nút", 280),
    ("Chạy phi", 290),
    ("In chuyển nhiệt", 300),
    ("Cắt vải theo rập", 310),
    ("In / thêu logo", 320),
    ("May thân áo", 330),
    ("QC thành phẩm", 340),
    ("Ủi — đóng gói", 350),
    ("Đóng gói", 360),
]


def seed_processes(apps, schema_editor):
    SxProcessName = apps.get_model("san_xuat", "SxProcessName")
    for name, order in DEFAULT_PROCESS_NAMES:
        SxProcessName.objects.get_or_create(
            name=name,
            defaults={"sort_order": order, "is_active": True},
        )


def unseed_processes(apps, schema_editor):
    SxProcessName = apps.get_model("san_xuat", "SxProcessName")
    names = [n for n, _ in DEFAULT_PROCESS_NAMES]
    SxProcessName.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("san_xuat", "0026_mo_process_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SxProcessName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="Tên công đoạn")),
                ("sort_order", models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name="Thứ tự")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Đang dùng")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Danh mục công đoạn",
                "verbose_name_plural": "Danh mục công đoạn",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RunPython(seed_processes, unseed_processes),
    ]
