# Generated by Django 5.2.7 on 2026-07-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0027_sxprocessname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxgeneralsettings',
            name='list_default_date_range_days',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Số ngày lọc danh sách mặc định'),
        ),
    ]
