# Generated by Django 5.2.7 on 2026-07-24 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0030_sxmachine_sxprocessstage_sxskilllevel_sxsmvsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomversion',
            name='routing',
            field=models.ForeignKey(blank=True, help_text='Quy trình công đoạn IE gắn với BOM này.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_versions', to='san_xuat.sxrouting', verbose_name='Routing mã hàng'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='op_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Mã công đoạn'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_process_steps', to='san_xuat.sxoperation', verbose_name='Công đoạn chuẩn (IE)'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='routing_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_process_steps', to='san_xuat.sxroutingline', verbose_name='Dòng routing'),
        ),
        migrations.AddField(
            model_name='sxproductionorder',
            name='routing',
            field=models.ForeignKey(blank=True, help_text='Snapshot routing IE khi tạo lệnh (ưu tiên lấy từ BOM).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='san_xuat.sxrouting', verbose_name='Routing mã hàng'),
        ),
    ]
