# Generated by Django 5.2.7 on 2026-07-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0031_ie_routing_bom_mo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxoperation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt'),
        ),
        migrations.AddField(
            model_name='sxrouting',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='approved', max_length=20, verbose_name='Trạng thái duyệt'),
        ),
        migrations.AddField(
            model_name='sxrouting',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt'),
        ),
        migrations.AddField(
            model_name='sxrouting',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='sxroutingline',
            name='variance_explanation',
            field=models.CharField(blank=True, default='', help_text='Bắt buộc khi |chênh lệch| > 15% trước khi duyệt phát hành.', max_length=500, verbose_name='Giải trình lệch SMV'),
        ),
        migrations.AddField(
            model_name='sxtimestudy',
            name='variance_explanation',
            field=models.CharField(blank=True, default='', help_text='Bắt buộc khi |chênh lệch| > 15% lúc duyệt cập nhật routing.', max_length=500, verbose_name='Giải trình lệch SMV'),
        ),
    ]
