# Generated by Django 5.2.7 on 2026-07-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0032_ie_release_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxrouting',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái duyệt'),
        ),
    ]
