# Generated by Django 5.2.7 on 2026-07-27 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_time_studies(apps, schema_editor):
    from san_xuat.ie_models import SxIeAuditLog
    from san_xuat.services.ie_audit import log_ie_event
    from san_xuat.services.ie_ops import link_time_studies_to_operations

    stats = link_time_studies_to_operations(only_unlinked=True)
    if stats.get('linked'):
        log_ie_event(
            action=SxIeAuditLog.ACTION_LINK,
            summary=f"Migration 0035: gắn FK time study → operation ({stats['linked']})",
            object_type='SxTimeStudy',
            object_repr='migration_link',
            changes=stats,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0034_ie_approver_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SxIeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Import'), ('export', 'Xuất Excel'), ('approve', 'Duyệt'), ('reject', 'Từ chối'), ('smv_change', 'Đổi SMV'), ('update', 'Cập nhật'), ('create', 'Tạo mới'), ('link', 'Gắn liên kết')], db_index=True, max_length=20)),
                ('object_type', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_ie_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký IE',
                'verbose_name_plural': 'Nhật ký IE',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(link_time_studies, noop_reverse),
    ]
