# Generated by Django 5.2.7 on 2026-07-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0036_link_time_studies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxgeneralsettings',
            name='gate_sku_on_stat',
            field=models.CharField(choices=[('off', 'Tắt — không kiểm tra'), ('warn', 'Cảnh báo — cho phép nhưng nhắc'), ('block', 'Chặn — bắt buộc đúng bước')], default='warn', help_text='SKU = Mã SX + Màu + Size. Mã SX lấy từ mã SP trên lệnh.', max_length=10, verbose_name='Bắt buộc SKU (màu + size) khi ghi thống kê sản xuất'),
        ),
        migrations.AlterField(
            model_name='sxsku',
            name='style_code',
            field=models.CharField(db_index=True, help_text='Mã SX = product_code hồ sơ / lệnh sản xuất.', max_length=60, verbose_name='Mã SX'),
        ),
    ]
