# Generated by Django 5.2.7 on 2026-07-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0037_rename_style_labels_to_ma_sx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxproductionorder',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Mã lệnh sản xuất'),
        ),
    ]
