# Generated by Django 5.2.7 on 2026-07-28 10:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0038_mo_code_from_product_maxlen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SxProductionOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, default='', max_length=100, verbose_name='SKU')),
                ('size_label', models.CharField(blank=True, default='', max_length=40, verbose_name='Size')),
                ('color_label', models.CharField(blank=True, default='', max_length=40, verbose_name='Màu')),
                ('color_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Mã màu')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='san_xuat.sxproductionorder', verbose_name='Lệnh sản xuất')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_lines', to='san_xuat.sxsku', verbose_name='SKU (master)')),
            ],
            options={
                'verbose_name': 'Dòng lệnh sản xuất',
                'verbose_name_plural': 'Dòng lệnh sản xuất',
                'ordering': ['color_code', 'size_label', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('production_order', 'color_code', 'size_label'), name='sx_mo_line_color_size_uniq')],
            },
        ),
    ]
