# Generated by Django 5.2.7 on 2026-07-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0039_mo_sku_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Sẵn sàng'), ('active', 'Sẵn sàng'), ('archived', 'Sẵn sàng')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='bomversion',
            name='version_label',
            field=models.CharField(default='v1', help_text='Tên bản BOM ngang hàng, vd. v1, Nội bộ, Gia công.', max_length=40, verbose_name='Phiên bản'),
        ),
    ]
