# Generated by Django 5.2.7 on 2026-07-29 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0040_bom_versions_peer_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='work_center',
            field=models.ForeignKey(blank=True, help_text='Bộ phận / tổ thuộc phòng Sản xuất phụ trách công đoạn này.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_steps', to='san_xuat.sxworkcenter', verbose_name='Bộ phận chịu trách nhiệm'),
        ),
    ]
