# Generated by Django 5.2.7 on 2026-07-29 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0041_process_step_work_center_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxoperationgroup',
            name='default_work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_groups', to='san_xuat.sxworkcenter', verbose_name='Bộ phận mặc định'),
        ),
        migrations.AlterField(
            model_name='sxoperationgroup',
            name='default_work_center_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Bộ phận mặc định (mã)'),
        ),
        migrations.AlterField(
            model_name='sxroutingline',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_lines', to='san_xuat.sxworkcenter', verbose_name='Bộ phận chịu trách nhiệm'),
        ),
        migrations.AlterField(
            model_name='sxroutingline',
            name='work_center_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Bộ phận (mã)'),
        ),
    ]
