# Generated by Django 5.2.7 on 2026-07-31 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_mo_process_steps(apps, schema_editor):
    SxProductionOrder = apps.get_model('san_xuat', 'SxProductionOrder')
    SxMoProcessStep = apps.get_model('san_xuat', 'SxMoProcessStep')
    ProcessStep = apps.get_model('san_xuat', 'ProcessStep')
    for mo in SxProductionOrder.objects.exclude(bom_version_id=None).iterator():
        if SxMoProcessStep.objects.filter(production_order_id=mo.pk).exists():
            continue
        bom_steps = list(
            ProcessStep.objects.filter(bom_id=mo.bom_version_id).order_by('sequence', 'id')
        )
        for i, step in enumerate(bom_steps):
            seq = step.sequence or ((i + 1) * 10)
            while SxMoProcessStep.objects.filter(production_order_id=mo.pk, sequence=seq).exists():
                seq += 1
            SxMoProcessStep.objects.create(
                production_order_id=mo.pk,
                sequence=seq,
                process_name=step.process_name or '',
                work_center_id=step.work_center_id,
                bom_process_step_id=step.pk,
                manager_id=None,
            )


def unseed_mo_process_steps(apps, schema_editor):
    SxMoProcessStep = apps.get_model('san_xuat', 'SxMoProcessStep')
    SxMoProcessStep.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0042_ie_work_center_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SxMoProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=10, verbose_name='Thứ tự')),
                ('process_name', models.CharField(max_length=120, verbose_name='Công đoạn')),
                ('bom_process_step_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID công đoạn BOM nguồn')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_managed_mo_steps', to=settings.AUTH_USER_MODEL, verbose_name='Quản lý công đoạn')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mo_process_steps', to='san_xuat.sxproductionorder', verbose_name='Lệnh sản xuất')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mo_process_steps', to='san_xuat.sxworkcenter', verbose_name='Tổ / bộ phận')),
            ],
            options={
                'verbose_name': 'Công đoạn LSX',
                'verbose_name_plural': 'Công đoạn LSX',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SxMoProcessAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_mo_process_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Người phân')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sx_mo_process_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
                ('mo_process_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='san_xuat.sxmoprocessstep', verbose_name='Công đoạn LSX')),
            ],
            options={
                'verbose_name': 'Phân công ghi TKSX',
                'verbose_name_plural': 'Phân công ghi TKSX',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sxmoprocessstep',
            constraint=models.UniqueConstraint(fields=('production_order', 'sequence'), name='sx_mo_process_step_seq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sxmoprocessassignee',
            constraint=models.UniqueConstraint(fields=('mo_process_step', 'user'), name='sx_mo_process_assignee_uniq'),
        ),
        migrations.RunPython(seed_mo_process_steps, unseed_mo_process_steps),
    ]
