# Generated by Django 5.2.7 on 2026-08-03 04:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0043_mo_process_step_manager_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SxHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField(unique=True, verbose_name='Ngày nghỉ')),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ngày nghỉ sản xuất',
                'verbose_name_plural': 'Ngày nghỉ sản xuất',
                'ordering': ['holiday_date'],
            },
        ),
        migrations.AddField(
            model_name='sxgeneralsettings',
            name='plan_block_over_capacity',
            field=models.BooleanField(default=True, help_text='Tắt = chỉ ghi cảnh báo vào ghi chú kế hoạch.', verbose_name='Chặn xác nhận kế hoạch chi tiết khi vượt năng lực'),
        ),
        migrations.AddField(
            model_name='sxgeneralsettings',
            name='plan_capacity_mode',
            field=models.CharField(choices=[('bottleneck', 'Công đoạn hẹp nhất (đúng dây chuyền) — khuyến nghị'), ('total', 'Tổng năng lực các tổ (chỉ khi các tổ chạy độc lập)')], default='bottleneck', help_text='Sản phẩm đi tuần tự qua các công đoạn nên năng lực dây chuyền bằng công đoạn hẹp nhất, không phải tổng các tổ.', max_length=20, verbose_name='Cách tính năng lực khi lập kế hoạch'),
        ),
        migrations.AddField(
            model_name='sxgeneralsettings',
            name='plan_workdays',
            field=models.CharField(default='1111110', help_text='7 ký tự 0/1 theo Thứ 2 → Chủ nhật. Mặc định 1111110 = nghỉ Chủ nhật.', max_length=7, verbose_name='Ngày làm việc trong tuần'),
        ),
        migrations.AddField(
            model_name='sxmaterialplanline',
            name='qty_reserved',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Số lượng thực tế giữ được trong kho khi xác nhận kế hoạch.', max_digits=14, verbose_name='Đã giữ chỗ'),
        ),
    ]
