# Generated by Django 5.2.7 on 2026-08-03 05:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0044_sxholiday_sxgeneralsettings_plan_block_over_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sxoverallplan',
            name='apply_netting',
            field=models.BooleanField(default=True, help_text='Nhu cầu thực = nhu cầu gộp − tồn khả dụng − SL đang sản xuất.', verbose_name='Trừ tồn thành phẩm & hàng đang SX'),
        ),
        migrations.AddField(
            model_name='sxoverallplan',
            name='frozen_until',
            field=models.DateField(blank=True, help_text='MPS: không cho sửa sản lượng trong vùng đã đóng băng.', null=True, verbose_name='Đóng băng đến ngày'),
        ),
        migrations.AddField(
            model_name='sxoverallplan',
            name='mps_bucket',
            field=models.CharField(choices=[('day', 'Theo ngày'), ('week', 'Theo tuần'), ('month', 'Theo tháng')], default='week', help_text='Đơn vị chia kỳ khi lập lịch trình chủ.', max_length=10, verbose_name='Chu kỳ lịch trình (MPS)'),
        ),
        migrations.AddField(
            model_name='sxoverallplan',
            name='plan_method',
            field=models.CharField(choices=[('mto', 'MTO — Sản xuất theo đơn đặt hàng'), ('mts', 'MTS — Sản xuất theo nhu cầu lưu trữ (tồn kho)'), ('mps', 'MPS — Sản xuất theo lịch trình chủ')], db_index=True, default='mto', max_length=10, verbose_name='Phương án sản xuất'),
        ),
        migrations.AddField(
            model_name='sxoverallplanline',
            name='bucket_start',
            field=models.DateField(blank=True, db_index=True, help_text='MPS: mốc đầu tuần/tháng của dòng.', null=True, verbose_name='Đầu kỳ lịch trình'),
        ),
        migrations.AddField(
            model_name='sxoverallplanline',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn giao'),
        ),
        migrations.AddField(
            model_name='sxoverallplanline',
            name='qty_gross',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tổng nhu cầu trước khi trừ tồn / hàng đang SX.', max_digits=14, verbose_name='Nhu cầu gộp'),
        ),
        migrations.AddField(
            model_name='sxoverallplanline',
            name='qty_on_hand',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Tồn TP khả dụng'),
        ),
        migrations.AddField(
            model_name='sxoverallplanline',
            name='qty_wip',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='SL còn lại trên các lệnh sản xuất chưa hoàn thành.', max_digits=14, verbose_name='Đang sản xuất'),
        ),
        migrations.CreateModel(
            name='SxProductStockPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('product_code', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên SP')),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Xuống dưới mức này thì đề xuất sản xuất bù.', max_digits=14, verbose_name='Tồn tối thiểu')),
                ('max_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sản xuất bù lên tới mức này. Để 0 = bù đúng bằng tồn tối thiểu.', max_digits=14, verbose_name='Tồn mục tiêu')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0, help_text='Số ngày cần để có hàng — dùng tính hạn cần NVL.', verbose_name='Thời gian chờ (ngày)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang áp dụng')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Chính sách tồn thành phẩm',
                'verbose_name_plural': 'Chính sách tồn thành phẩm',
                'ordering': ['product_code'],
            },
        ),
    ]
