# Generated by Django 5.2.7 on 2026-08-03 06:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0046_p2_backfill_plan_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxworkcenter',
            name='efficiency_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('85'), help_text='Tỷ lệ thời gian thực sự tạo ra sản phẩm — dùng khi xếp lịch theo SMV.', max_digits=5, verbose_name='Hiệu suất (%)'),
        ),
        migrations.AddField(
            model_name='sxworkcenter',
            name='headcount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Đồng bộ từ cơ cấu HR phòng Sản xuất.', verbose_name='Số nhân sự'),
        ),
        migrations.AddField(
            model_name='sxworkcenter',
            name='shift_minutes_per_head',
            field=models.PositiveSmallIntegerField(default=480, help_text='Mặc định 480 phút = 8 giờ một ca.', verbose_name='Phút làm việc / người / ngày'),
        ),
    ]
