# Generated by Django 5.2.7 on 2026-08-03 07:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0028_thicken_ops_wip_ycx_hr'),
        ('san_xuat', '0047_p3_work_center_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sxgeneralsettings',
            name='mo_late_alert_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Hiện nhắc việc ở trang chủ khi lệnh còn ít hơn số ngày này mà chưa xong.', verbose_name='Cảnh báo lệnh sản xuất sắp tới hạn (ngày)'),
        ),
        migrations.AddField(
            model_name='sxgeneralsettings',
            name='npl_prep_days',
            field=models.PositiveSmallIntegerField(default=2, help_text='Ngày cần NPL = ngày sản xuất sớm nhất của mã hàng − số ngày này.', verbose_name='Số ngày chuẩn bị NPL trước khi sản xuất'),
        ),
        migrations.AddField(
            model_name='sxmaterialplanline',
            name='need_date',
            field=models.DateField(blank=True, db_index=True, help_text='Ngày muộn nhất NPL phải có mặt tại kho (ngày SX sớm nhất − số ngày chuẩn bị).', null=True, verbose_name='Ngày cần'),
        ),
        migrations.AddField(
            model_name='sxnplpurchaserequestline',
            name='need_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cần'),
        ),
        migrations.AddField(
            model_name='sxpurchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hàng về dự kiến'),
        ),
        migrations.AddField(
            model_name='sxpurchaseorder',
            name='stock_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_purchase_orders', to='kho_npl.stockreceipt', verbose_name='Phiếu nhập kho NPL'),
        ),
        migrations.AddField(
            model_name='sxpurchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Chọn NCC trong danh mục kho để tạo phiếu nhập kho trực tiếp từ DMH.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_purchase_orders', to='kho_npl.supplier', verbose_name='Nhà cung cấp (kho NPL)'),
        ),
        migrations.AddField(
            model_name='sxpurchaseorderline',
            name='need_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cần'),
        ),
        migrations.AddField(
            model_name='sxpurchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá mua'),
        ),
        migrations.AddField(
            model_name='sxqcsamplingmethod',
            name='aql_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.5'), help_text='Mức chất lượng chấp nhận — dùng khi cách lấy mẫu là AQL.', max_digits=5, verbose_name='AQL (%)'),
        ),
        migrations.AddField(
            model_name='sxqcsamplingmethod',
            name='inspection_level',
            field=models.CharField(choices=[('S-1', 'S-1 (đặc biệt)'), ('S-2', 'S-2 (đặc biệt)'), ('S-3', 'S-3 (đặc biệt)'), ('S-4', 'S-4 (đặc biệt)'), ('I', 'I (giảm nhẹ)'), ('II', 'II (thông dụng)'), ('III', 'III (siết chặt)')], default='II', max_length=5, verbose_name='Mức kiểm tra'),
        ),
        migrations.AlterField(
            model_name='sxqcsamplingmethod',
            name='method_type',
            field=models.CharField(choices=[('fixed_qty', 'Số mẫu cố định'), ('percent', 'Tỷ lệ % lô'), ('aql', 'AQL — ISO 2859-1 (một lần, kiểm thường)')], default='fixed_qty', max_length=20, verbose_name='Cách lấy mẫu'),
        ),
        migrations.AlterField(
            model_name='sxqcsamplingmethod',
            name='sample_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=10, verbose_name='Giá trị (số mẫu hoặc %)'),
        ),
        migrations.CreateModel(
            name='SxPlanAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('confirm', 'Xác nhận'), ('close', 'Đóng'), ('cancel', 'Hủy'), ('reschedule', 'Xếp lịch lại'), ('netting', 'Tính net nhu cầu'), ('explode', 'Bung nhu cầu'), ('receipt', 'Nhập kho')], db_index=True, max_length=20, verbose_name='Thao tác')),
                ('object_type', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Đối tượng')),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('object_code', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Mã')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='Diễn giải')),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_plan_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký kế hoạch SX',
                'verbose_name_plural': 'Nhật ký kế hoạch SX',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
