# Generated by Django 5.2.7 on 2026-08-07 02:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0048_p4_feedback_loop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SxSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Số đơn hàng')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Khách hàng')),
                ('request_date', models.DateField(verbose_name='Ngày yêu cầu')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn sản xuất')),
                ('order_type', models.CharField(choices=[('production', 'Sản xuất')], default='production', max_length=20, verbose_name='Loại đơn')),
                ('confirm_status', models.CharField(choices=[('draft', 'Nháp / chưa xác nhận'), ('confirmed', 'Đã xác nhận'), ('rejected', 'Từ chối')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái xác nhận')),
                ('reject_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='Lý do từ chối')),
                ('source', models.CharField(choices=[('manual', 'Tạo tay'), ('kiotviet', 'KiotViet')], db_index=True, default='manual', max_length=20, verbose_name='Nguồn đơn')),
                ('kv_order_kiotviet_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='KV order id')),
                ('kv_order_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Mã đơn KV')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Đơn đặt hàng',
                'verbose_name_plural': 'Đơn đặt hàng',
                'ordering': ['-request_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sxoverallplanline',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overall_plan_lines', to='san_xuat.sxsalesorder', verbose_name='Đơn đặt hàng'),
        ),
        migrations.AddField(
            model_name='sxproductionorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='san_xuat.sxsalesorder', verbose_name='Đơn đặt hàng'),
        ),
        migrations.CreateModel(
            name='SxSalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=60, verbose_name='Mã sản phẩm')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên sản phẩm')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Số lượng')),
                ('qty_scrap_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, verbose_name='Tỷ lệ sai hỏng (%)')),
                ('uom', models.CharField(blank=True, default='', max_length=30, verbose_name='ĐVT')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn giao dòng')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='san_xuat.sxsalesorder', verbose_name='Đơn đặt hàng')),
            ],
            options={
                'verbose_name': 'Dòng đơn đặt hàng',
                'verbose_name_plural': 'Dòng đơn đặt hàng',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
