# Generated by Django 5.2.7 on 2026-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0053_work_center_load_pct_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxworkcenter',
            name='team_label',
            field=models.CharField(blank=True, default='', help_text='Khớp field team_label trên TKSX để đối chiếu sản lượng thực tế.', max_length=80, verbose_name='Nhãn tổ (khớp thống kê sản xuất)'),
        ),
    ]
