# Generated by Django 5.2.7 on 2026-08-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0055_sxsalesorderline_size_qtys'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxsalesorder',
            name='attachment',
            field=models.FileField(blank=True, upload_to='san_xuat/sales_orders/%Y/%m/', verbose_name='File đính kèm'),
        ),
    ]
