# Generated by Django 5.2.7 on 2026-08-10 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0056_sales_order_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sxsalesorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xác nhận'),
        ),
        migrations.AddField(
            model_name='sxsalesorder',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_sales_orders_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận'),
        ),
    ]
