# Generated by Django 5.2.7 on 2026-08-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0057_sales_order_confirmed_by_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxsalesorderline',
            name='bom_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='san_xuat.bomversion', verbose_name='Phiên bản BOM'),
        ),
        migrations.AddField(
            model_name='sxsalesorderline',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='san_xuat.sxrouting', verbose_name='Phiên bản công đoạn'),
        ),
    ]
