# Generated by Django 5.2.7 on 2026-08-12 04:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0061_sxteamworkclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxroutingline',
            name='price_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Hệ số đơn giá'),
        ),
        migrations.AddField(
            model_name='sxroutingline',
            name='total_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Tổng đơn giá'),
        ),
        migrations.AlterField(
            model_name='sxoperationgroup',
            name='data_owner',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Người lập'),
        ),
        migrations.AlterField(
            model_name='sxoperationgroup',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='sxoperationgroup',
            name='product_part',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Sản phẩm cần'),
        ),
    ]
