# Generated by Django 5.2.7 on 2026-08-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0062_routing_line_price_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxoperation',
            name='ie_owner',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Người lập'),
        ),
    ]
