# Generated by Django 5.2.7 on 2026-08-12 05:32

from django.db import migrations, models


def seed_product_parts(apps, schema_editor):
    SxProductPart = apps.get_model('san_xuat', 'SxProductPart')
    SxOperation = apps.get_model('san_xuat', 'SxOperation')
    SxOperationGroup = apps.get_model('san_xuat', 'SxOperationGroup')
    labels = set()
    for val in SxOperation.objects.exclude(product_part='').values_list('product_part', flat=True):
        labels.add((val or '').strip())
    for val in SxOperationGroup.objects.exclude(product_part='').values_list('product_part', flat=True):
        labels.add((val or '').strip())
    labels.discard('')
    for order, label in enumerate(sorted(labels), start=1):
        code = label[:40]
        SxProductPart.objects.update_or_create(
            code=code,
            defaults={'name': label[:150], 'sort_order': order * 10, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0064_skill_levels_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SxProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=150, verbose_name='Tên')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang dùng')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cụm chi tiết',
                'verbose_name_plural': 'Cụm chi tiết',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.RunPython(seed_product_parts, migrations.RunPython.noop),
    ]
