# Generated by Django 5.2.7 on 2026-08-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0066_smv_basis_and_stage_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxroutingline',
            name='seq_no',
            field=models.PositiveIntegerField(default=1, verbose_name='Thứ tự'),
        ),
    ]
