# Generated by Django 5.2.7 on 2026-08-13 02:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0067_alter_sxroutingline_seq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxoperation',
            name='base_smv_min',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='SMV chuẩn trên một đơn vị cơ sở, đơn vị phút.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SMV chuẩn (phút)'),
        ),
        migrations.AlterField(
            model_name='sxroutingline',
            name='library_unit_smv',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='SMV chuẩn (phút)'),
        ),
    ]
