# Generated by Django 5.2.7 on 2026-08-13 06:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_existing_order_routing(apps, schema_editor):
    SxSalesOrderLine = apps.get_model('san_xuat', 'SxSalesOrderLine')
    SxRoutingLine = apps.get_model('san_xuat', 'SxRoutingLine')
    Snap = apps.get_model('san_xuat', 'SxSalesOrderRoutingLine')
    q4 = Decimal('0.0001')
    q2 = Decimal('0.01')
    rows = []
    for ln in SxSalesOrderLine.objects.filter(routing_id__isnull=False).iterator():
        if Snap.objects.filter(sales_order_line_id=ln.pk).exists():
            continue
        for src in SxRoutingLine.objects.filter(routing_id=ln.routing_id).order_by('seq_no', 'id'):
            qty = src.qty_per_garment or Decimal('1')
            applied = src.applied_unit_smv or Decimal('0')
            lib = src.library_unit_smv or Decimal('0')
            total = (qty * applied).quantize(q4)
            var = Decimal('0')
            if lib:
                var = ((applied - lib) / lib * Decimal('100')).quantize(q2)
            rows.append(Snap(
                sales_order_line_id=ln.pk,
                source_routing_line_id=src.pk,
                seq_no=src.seq_no or 1,
                operation_id=src.operation_id,
                op_code=(src.op_code or '')[:30],
                op_rev=(src.op_rev or 'R01')[:10],
                op_name_vi=(src.op_name_vi or '')[:200],
                group_code=(src.group_code or '')[:30],
                qty_per_garment=qty,
                library_unit_smv=lib,
                applied_unit_smv=applied,
                total_operation_smv=total,
                smv_variance_pct=var,
                price_factor=src.price_factor or Decimal('0'),
                total_unit_price=src.total_unit_price or Decimal('0'),
                machine_id=src.machine_id,
                machine_code=(src.machine_code or '')[:40],
                work_center_id=src.work_center_id,
                work_center_code=(src.work_center_code or '')[:40],
                skill_level_label=(src.skill_level_label or '')[:60],
                critical_qc=bool(src.critical_qc),
                notes=(src.notes or '')[:255],
                variance_explanation=(src.variance_explanation or '')[:500],
            ))
            if len(rows) >= 500:
                Snap.objects.bulk_create(rows)
                rows = []
    if rows:
        Snap.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0071_producttechdoc_season_main_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='SxSalesOrderRoutingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('op_code', models.CharField(db_index=True, max_length=30, verbose_name='Mã công đoạn')),
                ('op_rev', models.CharField(default='R01', max_length=10, verbose_name='Phiên bản CĐ')),
                ('op_name_vi', models.CharField(blank=True, default='', max_length=200, verbose_name='Tên công đoạn')),
                ('group_code', models.CharField(blank=True, default='', max_length=30, verbose_name='Mã nhóm')),
                ('qty_per_garment', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SL/sản phẩm')),
                ('library_unit_smv', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='SMV chuẩn (phút)')),
                ('applied_unit_smv', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SMV áp dụng (phút)')),
                ('total_operation_smv', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='SL/SP × SMV áp dụng.', max_digits=12, verbose_name='Tổng SMV')),
                ('smv_variance_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Chênh lệch SMV (%)')),
                ('price_factor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Hệ số đơn giá')),
                ('total_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Tổng đơn giá')),
                ('machine_code', models.CharField(blank=True, default='', max_length=40, verbose_name='Máy (mã)')),
                ('work_center_code', models.CharField(blank=True, default='', max_length=40, verbose_name='Bộ phận (mã)')),
                ('skill_level_label', models.CharField(blank=True, default='', max_length=60, verbose_name='Bậc kỹ năng')),
                ('critical_qc', models.BooleanField(default=False, verbose_name='QC trọng yếu')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('variance_explanation', models.CharField(blank=True, default='', help_text='Bắt buộc khi |chênh lệch| > 15% trước khi xác nhận đơn.', max_length=500, verbose_name='Giải trình lệch SMV')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_routing_lines', to='san_xuat.sxmachine', verbose_name='Máy móc')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_routing_lines', to='san_xuat.sxoperation', verbose_name='Công đoạn (thư viện)')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_lines', to='san_xuat.sxsalesorderline', verbose_name='Dòng đơn')),
                ('source_routing_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_snapshots', to='san_xuat.sxroutingline', verbose_name='Dòng routing nguồn')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_routing_lines', to='san_xuat.sxworkcenter', verbose_name='Bộ phận chịu trách nhiệm')),
            ],
            options={
                'verbose_name': 'Công đoạn đơn hàng',
                'verbose_name_plural': 'Công đoạn đơn hàng',
                'ordering': ['sales_order_line', 'seq_no'],
                'constraints': [models.UniqueConstraint(fields=('sales_order_line', 'seq_no'), name='sx_so_routing_line_seq_uniq')],
            },
        ),
        migrations.RunPython(seed_existing_order_routing, migrations.RunPython.noop),
    ]
