# Generated by Django 5.2.7 on 2026-08-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0072_sales_order_routing_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxsalesorder',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến hoàn thành'),
        ),
        migrations.AlterField(
            model_name='sxsalesorder',
            name='request_date',
            field=models.DateField(verbose_name='Ngày dự kiến thực hiện'),
        ),
    ]
