# Generated by Django 5.2.7 on 2026-08-19 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0081_reset_unapproved_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SxBomAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('new_version', 'Tạo phiên bản')], db_index=True, max_length=20)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='san_xuat.bomversion', verbose_name='BOM')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_bom_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký BOM',
                'verbose_name_plural': 'Nhật ký BOM',
                'ordering': ['-created_at'],
            },
        ),
    ]
