# Generated by Django 5.2.7 on 2026-08-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_san_pham', '0009_warehouse_stockledger_stockbalance_and_more'),
        ('san_xuat', '0084_sxsku_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxfgreceiptrequest',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Kho ghi tăng tồn thành phẩm khi phiếu hoàn thành.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fg_receipts', to='kho_san_pham.warehouse', verbose_name='Kho nhập'),
        ),
        migrations.AlterField(
            model_name='sxfgreceiptrequest',
            name='warehouse_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Mã kho nhập (cũ)'),
        ),
        migrations.AlterField(
            model_name='sxfgreceiptrequest',
            name='warehouse_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Kho nhập (cũ)'),
        ),
    ]
