# Generated by Django 5.2.7 on 2026-08-22 04:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0088_inter_step_count_transfer_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='count_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Thời gian kiểm đếm sau công đoạn này, trước khi chuyển sang công đoạn sau. 0 = không phát sinh. Có thể chỉnh theo đơn.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kiểm đếm (phút)'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='transfer_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Thời gian vận chuyển hàng sang công đoạn sau. 0 = không phát sinh. Có thể chỉnh theo đơn.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vận chuyển (phút)'),
        ),
        migrations.AlterField(
            model_name='sxgeneralsettings',
            name='plan_count_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Gợi ý khi lên đơn / kế hoạch nếu công đoạn chưa khai báo. Có thể sửa từng khoảng CĐ — không cố định.', max_digits=10, verbose_name='Kiểm đếm mặc định giữa công đoạn (phút)'),
        ),
        migrations.AlterField(
            model_name='sxgeneralsettings',
            name='plan_transfer_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Gợi ý khi lên đơn / kế hoạch nếu công đoạn chưa khai báo. Có thể sửa từng khoảng CĐ — không cố định.', max_digits=10, verbose_name='Vận chuyển mặc định giữa công đoạn (phút)'),
        ),
        migrations.AlterField(
            model_name='sxroutingline',
            name='count_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sau công đoạn này, trước công đoạn sau. Chỉnh được, không cố định.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kiểm đếm (phút)'),
        ),
        migrations.AlterField(
            model_name='sxroutingline',
            name='transfer_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Chuyển hàng sang công đoạn sau. Chỉnh được, không cố định.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vận chuyển (phút)'),
        ),
        migrations.AlterField(
            model_name='sxsalesorderroutingline',
            name='count_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sau công đoạn này → công đoạn sau. Chỉnh theo đơn, không cố định.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kiểm đếm (phút)'),
        ),
        migrations.AlterField(
            model_name='sxsalesorderroutingline',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='sxsalesorderroutingline',
            name='transfer_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Chuyển hàng sang công đoạn sau. Chỉnh theo đơn, không cố định.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Vận chuyển (phút)'),
        ),
    ]
