# Generated by Django 5.x

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('san_xuat', '0092_drop_ranked_plan_status_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='SxTeamWorkAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('team_slug', models.CharField(
                    choices=[
                        ('cat', 'Cắt'),
                        ('inep', 'In - Ép'),
                        ('theu', 'Thêu'),
                        ('may', 'May'),
                        ('ht', 'Ủi - Gấp xếp'),
                        ('gh', 'Giao hàng thành phẩm'),
                    ],
                    db_index=True,
                    max_length=20,
                    verbose_name='Tổ chuyền',
                )),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Lúc nhận SX')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='%(app_label)s_%(class)s_created',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Người tạo',
                )),
                ('production_order', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='team_work_accepts',
                    to='san_xuat.sxproductionorder',
                    verbose_name='Lệnh sản xuất',
                )),
            ],
            options={
                'verbose_name': 'Nhận sản xuất tổ',
                'verbose_name_plural': 'Nhận sản xuất tổ',
                'ordering': ['accepted_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sxteamworkaccept',
            constraint=models.UniqueConstraint(
                fields=('production_order', 'team_slug'),
                name='san_xuat_team_work_accept_mo_slug_uniq',
            ),
        ),
    ]
