# Generated by Django 5.2.7 on 2026-08-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0100_sxsubcontractorder_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxqcrequest',
            name='stage_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Công đoạn'),
        ),
    ]
