# Generated by Django 5.2.7 on 2026-09-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0103_qc_inspection_size_defects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxsubcontractorder',
            name='team_slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Để trống = cả lệnh. Phiếu cũ có thể còn gắn một tổ.', max_length=20, verbose_name='Tổ Ob thuê ngoài'),
        ),
    ]
