# Generated by Django 5.2.7 on 2026-09-08 05:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0105_subcontract_team_not_whole_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxpurchaseorderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá mua'),
        ),
    ]
