# Generated by Django 5.2.7 on 2026-09-09 03:03

from django.db import migrations, models


def normalize_active_versions(apps, schema_editor):
    BomVersion = apps.get_model('san_xuat', 'BomVersion')
    SxRouting = apps.get_model('san_xuat', 'SxRouting')

    doc_ids = (
        BomVersion.objects.filter(status='active')
        .values_list('tech_doc_id', flat=True)
        .distinct()
    )
    for doc_id in doc_ids.iterator():
        active_ids = list(
            BomVersion.objects.filter(tech_doc_id=doc_id, status='active')
            .order_by('-activated_at', '-updated_at', '-id')
            .values_list('id', flat=True)
        )
        if len(active_ids) > 1:
            BomVersion.objects.filter(id__in=active_ids[1:]).update(status='archived')

    SxRouting.objects.filter(is_active=True).exclude(approval_status='approved').update(
        is_active=False,
    )
    routing_doc_ids = (
        SxRouting.objects.filter(is_active=True, tech_doc_id__isnull=False)
        .values_list('tech_doc_id', flat=True)
        .distinct()
    )
    for doc_id in routing_doc_ids.iterator():
        active_ids = list(
            SxRouting.objects.filter(tech_doc_id=doc_id, is_active=True)
            .order_by('-approved_at', '-updated_at', '-id')
            .values_list('id', flat=True)
        )
        if len(active_ids) > 1:
            SxRouting.objects.filter(id__in=active_ids[1:]).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0106_alter_sxpurchaseorderline_unit_price'),
    ]

    operations = [
        migrations.RunPython(normalize_active_versions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bomversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang áp dụng'), ('archived', 'Ngừng áp dụng')], db_index=True, default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
