# Generated by Django 5.2.7 on 2026-09-09 03:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0107_update_bom_status_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomversion',
            name='other_cost_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Chi phí khác cố định / 1 SP.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Chi phí khác'),
        ),
        migrations.AddField(
            model_name='costingsnapshot',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
