# Generated by Django 5.2.7 on 2026-09-09 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def label_existing_cost_versions(apps, schema_editor):
    CostingSnapshot = apps.get_model('san_xuat', 'CostingSnapshot')
    bom_ids = CostingSnapshot.objects.values_list('bom_id', flat=True).distinct()
    for bom_id in bom_ids.iterator():
        snapshots = CostingSnapshot.objects.filter(bom_id=bom_id).order_by('created_at', 'id')
        for index, snapshot in enumerate(snapshots.iterator(), start=1):
            snapshot.version_label = f'v{index}'
            snapshot.save(update_fields=['version_label'])


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0108_add_other_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costingsnapshot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiên bản Costing', 'verbose_name_plural': 'Phiên bản Costing'},
        ),
        migrations.AddField(
            model_name='costingsnapshot',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Chi tiết đã chốt'),
        ),
        migrations.AddField(
            model_name='costingsnapshot',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_snapshots', to='san_xuat.sxrouting', verbose_name='OB'),
        ),
        migrations.AddField(
            model_name='costingsnapshot',
            name='version_label',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Phiên bản Cost'),
        ),
        migrations.RunPython(label_existing_cost_versions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='costingsnapshot',
            constraint=models.UniqueConstraint(fields=('bom', 'version_label'), name='san_xuat_cost_version_unique_label_per_bom'),
        ),
    ]
