# Generated by Django 5.2.7 on 2026-09-09 04:24

from django.db import migrations


def normalize_bom_sort_order(apps, schema_editor):
    BomLine = apps.get_model('san_xuat', 'BomLine')
    bom_ids = BomLine.objects.values_list('bom_id', flat=True).distinct()
    for bom_id in bom_ids.iterator():
        line_ids = (
            BomLine.objects.filter(bom_id=bom_id)
            .order_by('sort_order', 'id')
            .values_list('id', flat=True)
        )
        for order, line_id in enumerate(line_ids.iterator(), start=1):
            BomLine.objects.filter(pk=line_id).update(sort_order=order)


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0109_cost_versions'),
    ]

    operations = [
        migrations.RunPython(normalize_bom_sort_order, migrations.RunPython.noop),
    ]
