# Generated by Django 5.2.7 on 2026-09-09 06:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0110_normalize_bom_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxsalesorder',
            name='npl_anchor',
            field=models.DateField(blank=True, help_text='Ngày bắt đầu mua / kitting. Trống = hôm nay lúc lưu.', null=True, verbose_name='Neo chuẩn bị NPL'),
        ),
        migrations.AddField(
            model_name='sxsalesorder',
            name='npl_kit_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Trống = lấy thiết lập chung npl_prep_days.', null=True, verbose_name='Ngày kitting (override)'),
        ),
        migrations.AddField(
            model_name='sxsalesorder',
            name='npl_lead_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Lead NPL (ngày lịch)'),
        ),
        migrations.AddField(
            model_name='sxsalesorder',
            name='npl_ready_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Ngày NPL sẵn'),
        ),
        migrations.AddField(
            model_name='sxsalesorder',
            name='npl_short_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Số mã NPL thiếu'),
        ),
        migrations.AddField(
            model_name='sxsalesorder',
            name='npl_status',
            field=models.CharField(choices=[('none', 'Chưa lập'), ('draft', 'Nháp'), ('ready', 'Đã tính vào KHSX')], db_index=True, default='none', max_length=12, verbose_name='TT kế hoạch NPL'),
        ),
        migrations.CreateModel(
            name='SxOrderNplLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(db_index=True, max_length=60, verbose_name='Mã NPL')),
                ('material_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên NPL')),
                ('unit', models.CharField(blank=True, default='', max_length=30, verbose_name='ĐVT')),
                ('qty_required', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('qty_available', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('qty_inbound', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('qty_shortfall', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('buy_lead_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ngày mua (tự nhập)')),
                ('ready_date', models.DateField(blank=True, null=True, verbose_name='Ngày sẵn')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npl_lines', to='san_xuat.sxsalesorder', verbose_name='Đơn đặt hàng')),
            ],
            options={
                'verbose_name': 'Dòng NPL trên KHSX',
                'verbose_name_plural': 'Dòng NPL trên KHSX',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('order', 'material_code'), name='sx_order_npl_line_unique_mat')],
            },
        ),
    ]
