# Generated by Django 5.2.7 on 2026-09-09 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0111_sales_order_npl_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxmaterialplan',
            name='sales_order',
            field=models.ForeignKey(
                blank=True,
                help_text='Nguồn từ bảng kế hoạch SX theo đơn. Trống = lập từ KHTT.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='material_plans',
                to='san_xuat.sxsalesorder',
                verbose_name='Đơn KHSX',
            ),
        ),
        migrations.AddField(
            model_name='sxnplpurchaserequest',
            name='sales_order',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='npl_purchase_requests',
                to='san_xuat.sxsalesorder',
                verbose_name='Đơn KHSX',
            ),
        ),
    ]
