# Generated by Django 5.2.7 on 2026-09-10 06:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0112_khnvl_ycm_sales_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxordernplline',
            name='qty_allocated',
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal('0'),
                help_text='SL tồn kho nhân viên KHSX gán cho đơn này — giữ chỗ mềm, chưa xuất phiếu.',
                max_digits=14,
                verbose_name='Đặt cho đơn',
            ),
        ),
        migrations.AlterField(
            model_name='sxordernplline',
            name='qty_available',
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal('0'),
                help_text='Tồn kho trừ phần đơn khác đã đặt (chưa xuất phiếu).',
                max_digits=14,
                verbose_name='Còn đặt được',
            ),
        ),
    ]
