# Generated by Django 5.2.7 on 2026-09-10 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0115_sales_order_plan_step_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxmaterialplanline',
            name='qty_reserved',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Số lượng thực tế giữ được trong kho (số đặt KHSX hoặc xác nhận KHNVL).', max_digits=14, verbose_name='Đã giữ chỗ'),
        ),
    ]
