# Generated by Django 5.2.7 on 2026-09-11 03:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0116_alter_sxmaterialplanline_qty_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxordernplline',
            name='qty_available',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tồn kho trừ phần đơn khác đã đặt (chưa xuất phiếu).', max_digits=14, verbose_name='Tồn kho'),
        ),
    ]
