# Generated by Django 5.2.7 on 2026-09-15 08:10

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_hours_and_division(apps, schema_editor):
    SxWorkCenter = apps.get_model('san_xuat', 'SxWorkCenter')
    Division = apps.get_model('hrm', 'Division')
    default_hours = Decimal('9.50')
    for wc in SxWorkCenter.objects.all().iterator():
        mins = int(wc.shift_minutes_per_head or 0)
        hours = (Decimal(mins) / Decimal('60')).quantize(Decimal('0.01')) if mins > 0 else default_hours
        update = ['work_hours_per_day']
        wc.work_hours_per_day = hours
        code = (wc.code or '').strip().upper()
        if code.startswith('HRD-') and not wc.division_id:
            suffix = code.split('-', 1)[-1]
            if suffix.isdigit() and Division.objects.filter(pk=int(suffix)).exists():
                wc.division_id = int(suffix)
                update.append('division')
        wc.save(update_fields=update)


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0104_grant_it_san_xuat_writes'),
        ('san_xuat', '0117_alter_sxordernplline_qty_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxworkcenter',
            name='work_hours_per_day',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('9.50'),
                help_text='Mặc định 9,5 giờ/ngày.',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0')),
                    django.core.validators.MaxValueValidator(Decimal('24')),
                ],
                verbose_name='Thời gian làm việc (giờ/ngày)',
            ),
        ),
        migrations.AddField(
            model_name='sxworkcenter',
            name='throughput_per_sec',
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal('0'),
                help_text='Số sản phẩm một người làm được mỗi giây.',
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                verbose_name='Hiệu suất chung (sản phẩm/s)',
            ),
        ),
        migrations.AddField(
            model_name='sxworkcenter',
            name='work_location',
            field=models.CharField(
                blank=True,
                default='',
                max_length=120,
                verbose_name='Địa điểm làm việc',
            ),
        ),
        migrations.AddField(
            model_name='sxworkcenter',
            name='division',
            field=models.ForeignKey(
                blank=True,
                help_text='Bộ phận trên sơ đồ nhân sự mà tổ sản xuất này thuộc về.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sx_work_centers',
                to='hrm.division',
                verbose_name='Thuộc tổ (cơ cấu nhân sự)',
            ),
        ),
        migrations.AlterField(
            model_name='sxworkcenter',
            name='headcount',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Số người làm việc trên tổ. Có thể lấy gợi ý từ bộ phận HR đã gắn.',
                verbose_name='Số lượng người',
            ),
        ),
        migrations.AlterField(
            model_name='sxworkcenter',
            name='shift_minutes_per_head',
            field=models.PositiveSmallIntegerField(
                default=570,
                help_text='Đồng bộ từ thời gian làm việc (mặc định 9,5 giờ = 570 phút).',
                verbose_name='Phút làm việc / người / ngày',
            ),
        ),
        migrations.AlterField(
            model_name='sxworkcenter',
            name='efficiency_pct',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('100'),
                help_text='Khả năng tăng ca so với ca chuẩn: 100 = bình thường, 150 = tăng ca 50%. Nhân vào quỹ phút và sản lượng ngày.',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0')),
                    django.core.validators.MaxValueValidator(Decimal('200')),
                ],
                verbose_name='Hệ số tải (%)',
            ),
        ),
        migrations.AlterField(
            model_name='sxworkcenter',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Tên tổ sản xuất'),
        ),
        migrations.AlterModelOptions(
            name='sxworkcenter',
            options={
                'ordering': ['code'],
                'verbose_name': 'Năng lực sản xuất',
                'verbose_name_plural': 'Năng lực sản xuất',
            },
        ),
        migrations.RunPython(backfill_hours_and_division, migrations.RunPython.noop),
    ]
