# Generated by Django 5.2.7 on 2026-09-15 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0104_grant_it_san_xuat_writes'),
        ('san_xuat', '0118_work_center_plan_capacity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxworkcenter',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Không bắt buộc. Tổ sản xuất tự khai, không phụ thuộc bộ phận HR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_work_centers', to='hrm.division', verbose_name='Thuộc tổ (cơ cấu nhân sự)'),
        ),
    ]
