# Generated by Django 5.2.7 on 2026-09-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0119_alter_sxworkcenter_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxworkcenter',
            name='is_subcontract',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Đánh dấu tổ này là đơn vị gia công. Nút Thuê gia công lấy tổ từ danh sách này.',
                verbose_name='Tổ thuê gia công',
            ),
        ),
    ]
