# Generated by Django 5.2.7 on 2026-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0127_npl_shortage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sxnplpurchaserequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn đặt hàng', 'verbose_name_plural': 'Đơn đặt hàng'},
        ),
        migrations.AlterField(
            model_name='sxgeneralsettings',
            name='prefix_npl_pr',
            field=models.CharField(default='DDH', max_length=16, verbose_name='Prefix đơn đặt hàng'),
        ),
        migrations.AlterField(
            model_name='sxnplpurchaserequest',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Mã đơn đặt hàng'),
        ),
    ]
