# Generated by Django 5.2.7 on 2026-09-25 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0128_don_dat_hang_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxsalesorder',
            name='plan_status',
            field=models.CharField(choices=[('queued', 'Chờ xếp'), ('ranked', 'Chờ xếp'), ('released', 'Đã chuyển SX'), ('in_progress', 'Đang sản xuất'), ('done', 'Hoàn thành'), ('on_hold', 'Tạm giữ'), ('cancelled', 'Đã hủy')], db_index=True, default='queued', max_length=20, verbose_name='TT kế hoạch SX'),
        ),
        migrations.CreateModel(
            name='SxProductionCancelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('mo', 'Lệnh sản xuất'), ('plan', 'Kế hoạch sản xuất')], db_index=True, max_length=12)),
                ('reason', models.TextField(verbose_name='Lý do hủy')),
                ('warning_text', models.TextField(blank=True, default='', verbose_name='Cảnh báo lúc gửi')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_requests', to='san_xuat.sxproductionorder')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sx_cancel_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_cancel_reviews', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_requests', to='san_xuat.sxsalesorder')),
            ],
            options={
                'verbose_name': 'Yêu cầu hủy sản xuất',
                'verbose_name_plural': 'Yêu cầu hủy sản xuất',
                'ordering': ['-requested_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('target_type', 'mo')), fields=('production_order',), name='sx_cancel_req_mo_pending'), models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('target_type', 'plan')), fields=('sales_order',), name='sx_cancel_req_plan_pending')],
            },
        ),
    ]
