# Generated by Django 5.2.7 on 2026-09-25 11:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0040_supplier_order_contact'),
        ('san_xuat', '0129_production_cancel_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sxnplpurchaserequest',
            name='price_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Duyệt giá lúc'),
        ),
        migrations.AddField(
            model_name='sxnplpurchaserequest',
            name='price_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_npl_price_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt giá'),
        ),
        migrations.AddField(
            model_name='sxnplpurchaserequest',
            name='price_return_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Lý do trả duyệt giá'),
        ),
        migrations.AlterField(
            model_name='sxnplpurchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('price_review', 'Chờ duyệt giá'), ('priced', 'Đã duyệt giá'), ('submitted', 'Đã gửi'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SxNplQuoteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(db_index=True, max_length=60, verbose_name='Mã NPL')),
                ('material_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Tên NPL')),
                ('unit_price', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá')),
                ('quality_note', models.CharField(blank=True, default='', max_length=255, verbose_name='Chất lượng')),
                ('capacity_note', models.CharField(blank=True, default='', max_length=255, verbose_name='Năng lực')),
                ('is_chosen', models.BooleanField(db_index=True, default=False, verbose_name='Sếp đã chọn')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='npl_quote_offers', to='kho_npl.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Báo giá NPL',
                'verbose_name_plural': 'Báo giá NPL',
                'ordering': ['material_code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sxnplpurchaserequestline',
            name='quote_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='san_xuat.sxnplquoteoffer', verbose_name='Báo giá đã chốt'),
        ),
        migrations.CreateModel(
            name='SxNplQuoteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã bảng so giá')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Tiêu đề')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Chờ chốt giá'), ('decided', 'Đã chốt giá')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_npl_quotes_decided', to=settings.AUTH_USER_MODEL, verbose_name='Người chốt giá')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_quote_sheets', to='san_xuat.sxsalesorder', verbose_name='Đơn KHSX')),
            ],
            options={
                'verbose_name': 'Bảng so giá NPL',
                'verbose_name_plural': 'Bảng so giá NPL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sxnplquoteoffer',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='san_xuat.sxnplquotesheet'),
        ),
        migrations.AddConstraint(
            model_name='sxnplquoteoffer',
            constraint=models.UniqueConstraint(fields=('sheet', 'material_code', 'supplier'), name='sx_npl_quote_offer_sheet_mat_sup'),
        ),
    ]
