# Generated by Django 5.2.7 on 2026-10-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0131_npl_quote_offer_material_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxmaterialissuerequest',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issue_requests', to='san_xuat.sxworkcenter', verbose_name='Tổ / bộ phận nhận'),
        ),
        migrations.AddField(
            model_name='sxmaterialissuerequestline',
            name='bom_material_code',
            field=models.CharField(blank=True, default='', help_text='Mã NPL chính trên BOM (khác material_code khi xuất NPL thay thế).', max_length=60, verbose_name='Mã NPL theo BOM'),
        ),
    ]
