# Generated by Django 5.2.7 on 2026-10-07 09:03

from django.db import migrations, models


def backfill_stock_issues(apps, schema_editor):
    Request = apps.get_model('san_xuat', 'SxMaterialIssueRequest')
    Through = Request.stock_issues.through
    rows = [
        Through(sxmaterialissuerequest_id=pk, stockissue_id=issue_id)
        for pk, issue_id in Request.objects.filter(stock_issue__isnull=False).values_list('pk', 'stock_issue_id')
    ]
    Through.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0040_supplier_order_contact'),
        ('san_xuat', '0132_ycx_work_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='sxmaterialissuerequest',
            name='stock_issues',
            field=models.ManyToManyField(blank=True, related_name='ycx_requests', to='kho_npl.stockissue', verbose_name='Các phiếu xuất NPL (gồm bổ sung)'),
        ),
        migrations.RunPython(backfill_stock_issues, migrations.RunPython.noop),
    ]
