# Generated by Django 5.2.7 on 2026-10-10 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0133_ycx_stock_issues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SxTeamWorkDayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_demo', models.BooleanField(db_index=True, default=False, verbose_name='Dữ liệu demo')),
                ('team_slug', models.CharField(choices=[('cat', 'Cắt'), ('inep', 'In - Ép'), ('theu', 'Thêu'), ('may', 'May'), ('ht', 'Ủi - Gấp xếp'), ('gh', 'Giao hàng thành phẩm')], db_index=True, max_length=20, verbose_name='Tổ chuyền')),
                ('note_date', models.DateField(verbose_name='Ngày')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='Ghi chú')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_work_day_notes', to='san_xuat.sxproductionorder', verbose_name='Lệnh sản xuất')),
            ],
            options={
                'verbose_name': 'Ghi chú tiến độ tổ theo ngày',
                'verbose_name_plural': 'Ghi chú tiến độ tổ theo ngày',
                'ordering': ['note_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('production_order', 'team_slug', 'note_date'), name='san_xuat_team_work_day_note_uniq')],
            },
        ),
    ]
