# Generated by Django 5.2.7 on 2026-10-10 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0134_team_work_day_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SxTeamProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_slug', models.CharField(choices=[('cat', 'Cắt'), ('inep', 'In - Ép'), ('theu', 'Thêu'), ('may', 'May'), ('ht', 'Ủi - Gấp xếp'), ('gh', 'Giao hàng thành phẩm')], db_index=True, max_length=20, verbose_name='Tổ chuyền')),
                ('work_date', models.DateField(verbose_name='Ngày tiến độ')),
                ('size_label', models.CharField(blank=True, default='', max_length=40, verbose_name='Size')),
                ('old_qty', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='SL cũ')),
                ('new_qty', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='SL mới')),
                ('is_backfill', models.BooleanField(db_index=True, default=False, verbose_name='Nhập bù')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sx_team_progress_logs', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress_logs', to='san_xuat.sxproductionorder', verbose_name='Lệnh sản xuất')),
            ],
            options={
                'verbose_name': 'Lịch sử cập nhật tiến độ tổ',
                'verbose_name_plural': 'Lịch sử cập nhật tiến độ tổ',
                'ordering': ['work_date', 'changed_at', 'pk'],
                'indexes': [models.Index(fields=['production_order', 'team_slug', 'work_date'], name='sx_team_prog_log_day_idx')],
            },
        ),
    ]
