# Generated by Django 5.2.7 on 2026-06-01 03:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0028_nas_storage_upload_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tên thiết bị')),
                ('managed_by', models.CharField(choices=[('IT', 'IT / CNTT'), ('MAINTENANCE', 'Bảo trì xưởng'), ('OTHER', 'Khác')], default='IT', max_length=20, verbose_name='Bộ phận quản lý')),
                ('category', models.CharField(choices=[('PC', 'Máy tính bàn (PC)'), ('Laptop', 'Laptop'), ('Printer', 'Máy in'), ('Network', 'Server / Thiết bị mạng'), ('Internet', 'Internet / Đường truyền'), ('Production', 'Máy sản xuất'), ('Tool', 'Dụng cụ / thiết bị xưởng'), ('CCTV', 'Camera (CCTV)'), ('Other', 'Khác')], default='PC', max_length=50, verbose_name='Loại thiết bị')),
                ('usage_department_text', models.CharField(blank=True, max_length=100, verbose_name='Phòng ban (text)')),
                ('usage_room', models.CharField(blank=True, max_length=100, verbose_name='Vị trí / phòng')),
                ('assigned_user_text', models.CharField(blank=True, max_length=100, verbose_name='Người dùng (text)')),
                ('handover_date', models.DateField(blank=True, null=True, verbose_name='Ngày bàn giao')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Serial')),
                ('configuration', models.TextField(blank=True, verbose_name='Cấu hình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email liên hệ')),
                ('status', models.CharField(choices=[('new', 'Mới lắp'), ('active', 'Đang hoạt động'), ('broken', 'Đang hỏng'), ('maintenance', 'Đang bảo trì'), ('scrapped', 'Đã hủy / Thanh lý')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='equipment/qr_codes/')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đơn giá (VNĐ)')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=15, verbose_name='Thành tiền (VNĐ)')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='Hostname')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP')),
                ('is_online', models.BooleanField(default=False, verbose_name='Trạng thái mạng')),
                ('last_scan_date', models.DateTimeField(blank=True, null=True, verbose_name='Lần quét cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Người sử dụng')),
                ('usage_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_devices', to='hrm.department', verbose_name='Phòng ban sử dụng')),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': 'Thiết bị',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.CharField(max_length=100, verbose_name='Người báo')),
                ('reporter_email', models.EmailField(blank=True, max_length=254, verbose_name='Email người báo')),
                ('issue_description', models.TextField(verbose_name='Mô tả lỗi')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Chi phí sửa')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến xong')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian sửa xong')),
                ('repair_note', models.TextField(blank=True, verbose_name='Ghi chú sửa chữa')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Đã sửa xong')),
                ('repaired_by', models.CharField(blank=True, max_length=100, verbose_name='Người sửa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='equipment.device')),
            ],
            options={
                'verbose_name': 'Lịch sử bảo trì',
                'verbose_name_plural': 'Lịch sử bảo trì',
                'ordering': ['-created_at'],
            },
        ),
    ]
