# Generated by Django 5.2.7 on 2026-06-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_agent_install'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('CUT_SPREAD', 'Máy trải vải'), ('CUT_TABLE', 'Bàn cắt / spreading table'), ('CUT_MACHINE', 'Máy cắt (dao rung, đĩa, laser…)'), ('CUT_AUX', 'Máy cắt phụ (band knife, notch, drill…)'), ('CUT_MEASURE', 'Cân / đo vải'), ('CUT_CAD', 'Plotter / CAD cắt'), ('SEW_LOCKSTITCH', 'Máy may 1 kim (lockstitch)'), ('SEW_DOUBLE', 'Máy may 2 kim'), ('SEW_OVERLOCK', 'Máy may overlock'), ('SEW_INTERLOCK', 'Máy may interlock / flatlock'), ('SEW_SPECIAL', 'Máy may chuyên dụng (nút, túi, bartack…)'), ('SEW_AUTO', 'Máy may tự động / CNC'), ('SEW_AUX', 'Phụ trợ may (bàn, ghế, đèn, hút bụi…)'), ('FINISH_IRON', 'Bàn ủi / máy ủi hơi'), ('FINISH_PRESS', 'Máy ép / heat press'), ('FINISH_TUNNEL', 'Tunnel / form finisher'), ('FINISH_TRIM', 'Cắt chỉ / xử lý lông'), ('EMB_MACHINE', 'Máy thêu'), ('PRINT_MACHINE', 'Máy in (screen, DTG, sublimation…)'), ('LABEL_PRESS', 'Máy ép nhãn / logo'), ('BARCODE_PRINT', 'Máy in tem / mã vạch'), ('WASH_MACHINE', 'Máy giặt công nghiệp'), ('DRY_MACHINE', 'Máy sấy'), ('WASH_EFFECT', 'Máy xử lý wash effect'), ('QC_LAB', 'Thiết bị phòng lab / đo lường'), ('QC_MEASURE', 'Bàn đo / template QC'), ('QC_DETECT', 'Kim detector / metal detector'), ('QC_CAMERA', 'Camera kiểm QC'), ('PACK_MACHINE', 'Máy đóng gói (hút chân không, co film…)'), ('PACK_SCALE', 'Cân đóng gói'), ('WARE_CONVEYOR', 'Băng chuyền / băng tải'), ('WARE_FORKLIFT', 'Xe nâng / pallet jack'), ('WARE_RACK', 'Kệ / pallet'), ('WARE_SCANNER', 'Máy quét barcode / RFID'), ('SAMPLE_SEW', 'Máy may mẫu'), ('SAMPLE_EMB', 'Máy thêu / in mẫu'), ('SAMPLE_MEASURE', 'Thiết bị đo mẫu'), ('SAMPLE_CUT', 'Plotter / cắt mẫu'), ('PC', 'Máy tính bàn (PC)'), ('Laptop', 'Laptop'), ('Printer', 'Máy in'), ('Network', 'Server / Thiết bị mạng'), ('Internet', 'Internet / Đường truyền'), ('CCTV', 'Camera an ninh (CCTV)'), ('PHONE', 'Tổng đài / walkie-talkie'), ('ATTENDANCE', 'Máy chấm công'), ('DISPLAY', 'Màn hình / TV / Andon'), ('Tool', 'Dụng cụ / bàn ghế xưởng'), ('PROD_OTHER', 'Máy sản xuất khác'), ('Other', 'Khác'), ('Production', 'Máy sản xuất (cũ)')], default='PC', max_length=50, verbose_name='Loại thiết bị'),
        ),
    ]
