# Generated by Django 5.2.7 on 2026-06-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_device_mac_address'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='equipment_device_mac_unique',
        ),
    ]
