# Generated by Django 5.2.7 on 2026-06-01 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('category', models.CharField(choices=[('process', 'Quy trình'), ('environment', 'Môi trường làm việc'), ('tool', 'Công cụ / IT'), ('hr', 'Nhân sự'), ('other', 'Khác')], default='other', max_length=32, verbose_name='Chủ đề')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('in_review', 'Đang xử lý'), ('resolved', 'Đã phản hồi'), ('closed', 'Đã đóng')], db_index=True, default='new', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Góp ý',
                'verbose_name_plural': 'Góp ý',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_replies', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedback')),
            ],
            options={
                'verbose_name': 'Phản hồi góp ý',
                'verbose_name_plural': 'Phản hồi góp ý',
                'ordering': ['created_at'],
            },
        ),
    ]
