# Generated by Django 5.2.7 on 2026-06-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Gửi ẩn danh'),
        ),
        migrations.DeleteModel(
            name='FeedbackReply',
        ),
    ]
