# Generated by Django 5.2.7 on 2026-06-01 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_assigned_to_remove_feedback_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xem'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_viewed', to=settings.AUTH_USER_MODEL, verbose_name='Người xem'),
        ),
    ]
