from django.urls import path

from san_xuat import views, views_hub, views_kv_embed

app_name = 'san_xuat'

urlpatterns = [
    path('', views.hub, name='hub'),
    path('tong-quan/', views_hub.overview, name='overview'),
    path('don-hang/', views_hub.redirect_orders, name='redirect_orders'),
    path('ke-hoach/', views_hub.plan_stub, name='plan_stub'),
    path('ke-hoach/tong-the/', views_hub.plan_overall, name='plan_overall'),
    path('ke-hoach/chi-tiet/', views_hub.plan_detail, name='plan_detail'),
    path('ke-hoach/npl/', views_hub.plan_npl, name='plan_npl'),
    path('ke-hoach/yeu-cau-mua-npl/', views_hub.npl_purchase_request, name='npl_purchase_request'),
    path('ke-hoach/don-mua-hang/', views_hub.purchase_order, name='purchase_order'),
    path('dieu-phoi/', views_hub.dispatch_stub, name='dispatch_stub'),
    path('dieu-phoi/lenh-sx/', views_hub.dispatch_mo, name='dispatch_mo'),
    path('dieu-phoi/lenh-thao-do/', views_hub.dispatch_disassembly, name='dispatch_disassembly'),
    path('dieu-phoi/lich-sx/', views_hub.dispatch_schedule, name='dispatch_schedule'),
    path('dieu-phoi/yeu-cau-xuat-vt/', views_hub.dispatch_material_issue_req, name='dispatch_material_issue_req'),
    path('dieu-phoi/thong-ke-sx/', views_hub.dispatch_prod_stats, name='dispatch_prod_stats'),
    path('dieu-phoi/yeu-cau-nhap-tp/', views_hub.dispatch_fg_receipt_req, name='dispatch_fg_receipt_req'),
    path('dieu-phoi/npl-thua/', views_hub.dispatch_npl_surplus, name='dispatch_npl_surplus'),
    path('dieu-phoi/ban-giao-btp/', views_hub.dispatch_wip_handover, name='dispatch_wip_handover'),
    path('dieu-phoi/tra-lai-btp/', views_hub.dispatch_wip_return, name='dispatch_wip_return'),
    path('dieu-phoi/tinh-hinh-ban-giao/', views_hub.dispatch_handover_status, name='dispatch_handover_status'),
    path('chat-luong/', views_hub.qc_stub, name='qc_stub'),
    path('chat-luong/yeu-cau/', views_hub.qc_request, name='qc_request'),
    path('chat-luong/phieu/', views_hub.qc_sheet, name='qc_sheet'),
    path('chat-luong/tieu-chi/', views_hub.qc_criteria, name='qc_criteria'),
    path('chat-luong/nhom-tieu-chi/', views_hub.qc_criteria_group, name='qc_criteria_group'),
    path('chat-luong/chon-mau/', views_hub.qc_sampling, name='qc_sampling'),
    path('chat-luong/bo-tieu-chuan/', views_hub.qc_standard_set, name='qc_standard_set'),
    path('chat-luong/loi/', views_hub.qc_defect, name='qc_defect'),
    path('chat-luong/nhom-loi/', views_hub.qc_defect_group, name='qc_defect_group'),
    path('gia-thanh/', views_hub.redirect_costing, name='redirect_costing'),
    path('gia-thanh/dinh-muc/', views_hub.costing_norm, name='costing_norm'),
    path('gia-thanh/theo-don/', views_hub.costing_by_order, name='costing_by_order'),
    path('kho-san-pham/', views_kv_embed.fg_stock_hub, name='redirect_fg_stock'),
    path('kho-san-pham/hang-hoa/', views_kv_embed.fg_product_lookup, name='fg_product_lookup'),
    path('kho-san-pham/hang-hoa/<int:product_id>/', views_kv_embed.fg_product_detail, name='fg_product_detail'),
    path('kho-san-pham/ton-kho/', views_kv_embed.fg_stock_lookup, name='fg_stock_lookup'),
    path('kho-san-pham/phieu-nhap/', views_kv_embed.fg_purchase_lookup, name='fg_purchase_lookup'),
    path('kho-san-pham/phieu-nhap/<int:purchase_id>/', views_kv_embed.fg_purchase_detail, name='fg_purchase_detail'),
    path('kho-npl/', views_hub.redirect_npl_stock, name='redirect_npl_stock'),
    path('quy-trinh/', views_hub.process_stub, name='process_stub'),
    path('ho-so/', views.doc_list, name='doc_list'),
    path('ho-so/them/', views.doc_create, name='doc_create'),
    path('ho-so/<int:pk>/', views.doc_detail, name='doc_detail'),
    path('api/tim-ma-sp/', views.product_code_search, name='product_code_search'),
]
