# Generated by Django 5.2.7 on 2026-06-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nas_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nassharelink',
            new_name='nas_storage_created_75c74a_idx',
            old_name='nas_storage_created_8a0f0d_idx',
        ),
    ]
