# Generated by Django 5.2.7 on 2026-06-18 05:26

from django.db import migrations, models


def clear_share_expiry(apps, schema_editor):
    NasShareLink = apps.get_model('nas_storage', 'NasShareLink')
    NasShareLink.objects.all().update(expires_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('nas_storage', '0003_nasuserfolderaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nassharelink',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(clear_share_expiry, migrations.RunPython.noop),
    ]
