# Generated by Django 5.2.7 on 2026-06-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas_storage', '0004_share_no_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên nhóm')),
                ('nas_principal', models.CharField(blank=True, help_text='VD: @SX@ldap.justplay.local hoặc @IT. Để trống → tự sinh từ tên nhóm.', max_length=200, verbose_name='Principal trên NAS')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhóm quyền NAS',
                'verbose_name_plural': 'Nhóm quyền NAS',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NasShareFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_name', models.CharField(help_text='VD: 07_SAN_XUAT', max_length=120, unique=True, verbose_name='Tên share NAS')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Tên hiển thị')),
                ('volume_path', models.CharField(blank=True, help_text='VD: /volume1/07_SAN_XUAT', max_length=500, verbose_name='Đường dẫn volume')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thư mục share NAS',
                'verbose_name_plural': 'Thư mục share NAS',
                'ordering': ['sort_order', 'share_name'],
            },
        ),
        migrations.CreateModel(
            name='NasFolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('allow', 'Cho phép'), ('deny', 'Từ chối')], default='allow', max_length=8, verbose_name='Loại')),
                ('apply_to', models.CharField(choices=[('all', 'Tất cả'), ('folder', 'Chỉ thư mục này'), ('subfolders', 'Chỉ thư mục con'), ('files', 'Chỉ tệp')], default='all', max_length=16, verbose_name='Áp dụng cho')),
                ('inherit_from_parent', models.BooleanField(default=False, verbose_name='Kế thừa từ thư mục cha')),
                ('perm_traverse', models.BooleanField(default=True, verbose_name='Duyệt / Thực thi')),
                ('perm_list_read', models.BooleanField(default=True, verbose_name='Liệt kê / Đọc')),
                ('perm_read_attr', models.BooleanField(default=True, verbose_name='Đọc thuộc tính')),
                ('perm_read_ext_attr', models.BooleanField(default=True, verbose_name='Đọc thuộc tính mở rộng')),
                ('perm_read_acl', models.BooleanField(default=True, verbose_name='Đọc quyền')),
                ('perm_create_files', models.BooleanField(default=True, verbose_name='Tạo tệp / Ghi')),
                ('perm_create_folders', models.BooleanField(default=True, verbose_name='Tạo thư mục')),
                ('perm_write_attr', models.BooleanField(default=True, verbose_name='Ghi thuộc tính')),
                ('perm_write_ext_attr', models.BooleanField(default=True, verbose_name='Ghi thuộc tính mở rộng')),
                ('perm_delete_children', models.BooleanField(default=True, verbose_name='Xóa con')),
                ('perm_delete', models.BooleanField(default=True, verbose_name='Xóa')),
                ('perm_change_acl', models.BooleanField(default=False, verbose_name='Đổi quyền')),
                ('perm_take_ownership', models.BooleanField(default=False, verbose_name='Chiếm sở hữu')),
                ('last_applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Áp dụng NAS lần cuối')),
                ('last_apply_status', models.CharField(blank=True, max_length=500, verbose_name='Trạng thái áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to='nas_storage.nasaccessgroup', verbose_name='Nhóm')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='nas_storage.nassharefolder', verbose_name='Thư mục NAS')),
            ],
            options={
                'verbose_name': 'Phân quyền thư mục NAS',
                'verbose_name_plural': 'Phân quyền thư mục NAS',
                'ordering': ['folder__sort_order', 'group__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('folder', 'group'), name='nas_storage_folder_group_perm_uniq')],
            },
        ),
    ]
