# Generated by Django 5.2.7 on 2026-06-26 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas_storage', '0009_nasfolderpermission_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nasfolderpermission',
            options={'ordering': ['folder__sort_order', 'group__sort_order', 'user__username', 'id'], 'verbose_name': 'Phân quyền thư mục NAS', 'verbose_name_plural': 'Phân quyền thư mục NAS'},
        ),
        migrations.AlterField(
            model_name='nasaccessgroup',
            name='portal_excluded_members',
            field=models.ManyToManyField(blank=True, help_text='User thuộc phòng ban nhóm nhưng không được tính vào nhóm.', related_name='nas_portal_excluded_groups', to=settings.AUTH_USER_MODEL, verbose_name='Loại trừ khỏi nhóm (Portal)'),
        ),
    ]
