# Generated by Django 5.2.7 on 2026-08-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nas_storage', '0011_nassharefolder_parent_subpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasaccessgroup',
            name='portal_browse_all',
            field=models.BooleanField(default=False, help_text='Thành viên nhóm xem được mọi share trên Portal và được gán quyền đầy đủ (đọc/ghi/quản trị) trên tất cả thư mục NAS đã đăng ký.', verbose_name='Duyệt tất cả share (Portal)'),
        ),
    ]
