# Generated by Django 5.2.7 on 2026-04-23 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Họ và tên')),
                ('position', models.CharField(blank=True, choices=[('Bác Sĩ', 'Bác Sĩ'), ('Điều Dưỡng', 'Điều Dưỡng'), ('Dược Sĩ', 'Dược Sĩ'), ('Kỹ Thuật viên', 'Kỹ Thuật viên'), ('Khối Hỗ trợ', 'Khối Hỗ trợ')], max_length=50, verbose_name='Chức danh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_profile',
            },
        ),
    ]
