# Generated by Django 5.2.7 on 2026-04-28 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Nhân viên'), ('HOD', 'Trưởng phòng / Quản lý trực tiếp (HOD)'), ('GM', 'Giám đốc / Quản lý chung (GM)')], default='EMPLOYEE', max_length=20, verbose_name='Vai trò hệ thống'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subordinates',
            field=models.ManyToManyField(blank=True, related_name='my_hod_managers', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên dưới quyền (Dành cho HOD)'),
        ),
    ]
