# Generated by Django 5.2.7 on 2026-05-28 06:26

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_update_position_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hướng dẫn sử dụng JustPlay Portal', max_length=255, verbose_name='Tiêu đề')),
                ('subtitle', models.TextField(blank=True, default='Hướng dẫn từng bước — dành cho người chưa từng dùng hệ thống. Đọc theo thứ tự hoặc nhảy tới mục bạn cần.', verbose_name='Mô tả ngắn')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='Nội dung')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_updates', to=settings.AUTH_USER_MODEL, verbose_name='Cập nhật bởi')),
            ],
            options={
                'verbose_name': 'Hướng dẫn sử dụng',
                'verbose_name_plural': 'Hướng dẫn sử dụng',
            },
        ),
    ]
