# Generated by Django 5.2.7 on 2026-05-29 05:00

from django.db import migrations, models


def seed_role_permissions(apps, schema_editor):
    RoleModulePermission = apps.get_model('hrm', 'RoleModulePermission')
    defaults = {
        'EMPLOYEE': {
            'announcements': {'view': True, 'edit': False},
            'training': {'view': True, 'edit': False},
            'assessment': {'view': True, 'edit': False},
            'kpi': {'view': True, 'edit': False},
            'reports': {'view': True, 'edit': False},
            'guide': {'view': True, 'edit': False},
            'documents': {'view': True, 'edit': False},
            'recruitment': {'view': False, 'edit': False},
            'hrm': {'view': False, 'edit': False},
        },
        'TEAM_LEADER': {
            'announcements': {'view': True, 'edit': False},
            'training': {'view': True, 'edit': False},
            'assessment': {'view': True, 'edit': False},
            'kpi': {'view': True, 'edit': True},
            'reports': {'view': True, 'edit': True},
            'guide': {'view': True, 'edit': True},
            'documents': {'view': True, 'edit': False},
            'recruitment': {'view': False, 'edit': False},
            'hrm': {'view': False, 'edit': False},
        },
        'DIVISION_HEAD': {
            'announcements': {'view': True, 'edit': False},
            'training': {'view': True, 'edit': True},
            'assessment': {'view': True, 'edit': True},
            'kpi': {'view': True, 'edit': True},
            'reports': {'view': True, 'edit': True},
            'guide': {'view': True, 'edit': True},
            'documents': {'view': True, 'edit': True},
            'recruitment': {'view': False, 'edit': False},
            'hrm': {'view': False, 'edit': False},
        },
        'DIRECTOR': {
            'announcements': {'view': True, 'edit': True},
            'training': {'view': True, 'edit': True},
            'assessment': {'view': True, 'edit': True},
            'kpi': {'view': True, 'edit': True},
            'reports': {'view': True, 'edit': True},
            'guide': {'view': True, 'edit': True},
            'documents': {'view': True, 'edit': True},
            'recruitment': {'view': True, 'edit': True},
            'hrm': {'view': True, 'edit': True},
        },
    }
    for role, perms in defaults.items():
        RoleModulePermission.objects.get_or_create(
            role=role,
            defaults={'module_permissions': perms},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0016_add_documents_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Nhân viên'), ('TEAM_LEADER', 'Tổ trưởng'), ('DIVISION_HEAD', 'Trưởng bộ phận'), ('DIRECTOR', 'Giám đốc')], max_length=20, unique=True, verbose_name='Vai trò')),
                ('module_permissions', models.JSONField(blank=True, default=dict, help_text='JSON: {module: {view: bool, edit: bool}}', verbose_name='Quyền theo module')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phân quyền vai trò',
                'verbose_name_plural': 'Phân quyền vai trò',
            },
        ),
        migrations.RunPython(seed_role_permissions, noop),
    ]
