# Generated by Django 5.2.7 on 2026-05-29 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0020_add_tasks_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subordinates',
            field=models.ManyToManyField(blank=True, related_name='my_hod_managers', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên cấp dưới trực tiếp'),
        ),
    ]
