# Generated by Django 5.2.7 on 2026-06-08 06:19

from django.db import migrations, models


def seed_department_report_profiles(apps, schema_editor):
    Department = apps.get_model('hrm', 'Department')
    production_names = {'SẢN XUẤT', 'ĐẢM BẢO CHẤT LƯỢNG'}
    for dept in Department.objects.all().only('id', 'name', 'report_profile'):
        normalized = (dept.name or '').strip().upper()
        if normalized in production_names:
            profile = 'PRODUCTION'
        elif 'SẢN XUẤT' in normalized and 'KẾ HOẠCH' not in normalized:
            profile = 'PRODUCTION'
        else:
            profile = 'OFFICE'
        if dept.report_profile != profile:
            Department.objects.filter(pk=dept.pk).update(report_profile=profile)


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0035_fix_hcns_hrm_delete_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='report_profile',
            field=models.CharField(choices=[('PRODUCTION', 'Sản xuất (bảng năng suất)'), ('OFFICE', 'Phòng ban khác (Excel / Word tự do)')], default='OFFICE', max_length=20, verbose_name='Mẫu báo cáo'),
        ),
        migrations.RunPython(seed_department_report_profiles, migrations.RunPython.noop),
    ]
