# Generated by Django 5.2.7 on 2026-06-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0039_department_head_role_and_concurrent_subordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Nhân viên'), ('TEAM_LEADER', 'Tổ trưởng'), ('DIVISION_HEAD', 'Trưởng bộ phận'), ('DEPARTMENT_HEAD', 'Trưởng phòng'), ('DIRECTOR', 'Giám đốc')], max_length=20, unique=True, verbose_name='Vai trò'),
        ),
    ]
