# Generated by Django 5.2.7 on 2026-06-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0041_add_kho_npl_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {module: {view, create, update, delete, export, menus?: {menu_key: {...}}}}', verbose_name='Quyền theo module'),
        ),
    ]
