# Generated by Django 5.2.7 on 2026-06-16 10:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0043_userguide_section_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguide',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Nội dung (cũ)'),
        ),
        migrations.AlterField(
            model_name='userguide',
            name='section_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='{section_id: {title?, body}}', verbose_name='Ghi đè theo mục'),
        ),
    ]
