# Generated by Django 5.2.7 on 2026-07-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0059_profile_on_probation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='on_probation',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Thử việc'),
        ),
    ]
