# Generated by Django 5.2.7 on 2026-10-05 09:35

import django.db.models.deletion
import xay_dung.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('html_file', models.FileField(max_length=255, storage=xay_dung.models.private_storage, upload_to=xay_dung.models.model_upload_to, verbose_name='File HTML')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Tên file gốc')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Dung lượng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xay_dung_models', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Mô hình 3D',
                'verbose_name_plural': 'Mô hình 3D',
                'ordering': ['-created_at'],
            },
        ),
    ]
