# Generated by Django 5.2.7 on 2026-04-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetabaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên Báo Cáo (VD: Thống kê Quý 1)')),
                ('uuid', models.CharField(max_length=100, verbose_name='Mã UUID từ Metabase')),
                ('report_type', models.CharField(choices=[('dashboard', 'Dashboard (Bảng điều khiển)'), ('question', 'Question (Biểu đồ đơn)')], default='dashboard', max_length=20, verbose_name='Loại báo cáo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cho phép hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Báo Cáo Metabase',
                'verbose_name_plural': 'Danh Sách Báo Cáo',
            },
        ),
    ]
