# Generated by Django 5.2.7 on 2026-05-28 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Ngày báo cáo')),
                ('shift', models.CharField(choices=[('MORNING', 'Ca sáng'), ('AFTERNOON', 'Ca chiều'), ('NIGHT', 'Ca đêm')], default='MORNING', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã nộp')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hod_reviewed', models.BooleanField(default=False, verbose_name='HOD đã xem')),
                ('hod_note', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú HOD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_reports', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Báo cáo công việc ngày',
                'verbose_name_plural': 'Báo cáo công việc ngày',
                'ordering': ['-report_date', '-updated_at'],
                'unique_together': {('employee', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyWorkReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('CUT', 'Cắt vải'), ('SEW', 'May'), ('PRINT', 'In/Thêu'), ('PACK', 'Gói đóng'), ('QC', 'Kiểm QC'), ('WH', 'Kho'), ('PLAN', 'KHSX'), ('TECH', 'Kỹ thuật/Rập'), ('OTHER', 'Khác')], max_length=20, verbose_name='Công đoạn')),
                ('order_code', models.CharField(blank=True, max_length=80, verbose_name='Mã đơn/Style')),
                ('product_name', models.CharField(blank=True, max_length=120, verbose_name='Tên SP')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Sản lượng')),
                ('unit', models.CharField(choices=[('PCS', 'Cái'), ('SET', 'Bộ'), ('M', 'Mét'), ('KG', 'Kg')], default='PCS', max_length=10, verbose_name='ĐVT')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú ngắn')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reports.dailyworkreport', verbose_name='Báo cáo')),
            ],
            options={
                'verbose_name': 'Dòng công việc',
                'verbose_name_plural': 'Dòng công việc',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='MetabaseReport',
        ),
    ]
