# Generated by Django 5.2.7 on 2026-06-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyworkreport_dailyworkreportline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='document_html',
            field=models.TextField(blank=True, verbose_name='Văn bản Word (HTML)'),
        ),
        migrations.AddField(
            model_name='dailyworkreport',
            name='report_profile',
            field=models.CharField(choices=[('PRODUCTION', 'Sản xuất (bảng năng suất)'), ('OFFICE', 'Phòng ban khác (Excel / Word tự do)')], default='PRODUCTION', max_length=20, verbose_name='Loại báo cáo'),
        ),
        migrations.AddField(
            model_name='dailyworkreport',
            name='spreadsheet_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Bảng Excel (JSON)'),
        ),
        migrations.AlterField(
            model_name='dailyworkreport',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Ca sáng'), ('AFTERNOON', 'Ca chiều'), ('NIGHT', 'Ca đêm')], default='MORNING', max_length=20),
        ),
    ]
