# Generated by Django 5.2.7 on 2026-06-08 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_profile_routing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Tuần (thứ 2)')),
                ('report_profile', models.CharField(choices=[('PRODUCTION', 'Sản xuất (bảng năng suất)'), ('OFFICE', 'Phòng ban khác (Excel / Word tự do)')], default='PRODUCTION', max_length=20, verbose_name='Loại báo cáo')),
                ('spreadsheet_json', models.JSONField(blank=True, null=True, verbose_name='Bảng (JSON)')),
                ('document_html', models.TextField(blank=True, verbose_name='Văn bản (HTML)')),
                ('summary_note', models.TextField(blank=True, verbose_name='Tóm tắt tuần')),
                ('issues_note', models.TextField(blank=True, verbose_name='Sự cố / vướng mắc')),
                ('plan_next_week', models.TextField(blank=True, verbose_name='Kế hoạch tuần sau')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã nộp')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hod_reviewed', models.BooleanField(default=False, verbose_name='HOD đã xem')),
                ('hod_note', models.CharField(blank=True, max_length=500, verbose_name='Ghi chú HOD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_work_reports', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Báo cáo công việc tuần',
                'verbose_name_plural': 'Báo cáo công việc tuần',
                'ordering': ['-week_start', '-updated_at'],
                'unique_together': {('employee', 'week_start')},
            },
        ),
    ]
