# Generated by Django 5.2.7 on 2026-06-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_weekly_work_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyworkreport',
            name='document_html',
        ),
        migrations.RemoveField(
            model_name='weeklyworkreport',
            name='issues_note',
        ),
        migrations.RemoveField(
            model_name='weeklyworkreport',
            name='plan_next_week',
        ),
        migrations.RemoveField(
            model_name='weeklyworkreport',
            name='report_profile',
        ),
        migrations.RemoveField(
            model_name='weeklyworkreport',
            name='spreadsheet_json',
        ),
        migrations.RemoveField(
            model_name='weeklyworkreport',
            name='summary_note',
        ),
        migrations.AddField(
            model_name='weeklyworkreport',
            name='links',
            field=models.TextField(blank=True, verbose_name='Link (mỗi dòng một link)'),
        ),
        migrations.CreateModel(
            name='WeeklyWorkReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FILE', 'File'), ('IMAGE', 'Ảnh')], max_length=10)),
                ('file', models.FileField(upload_to='reports/weekly/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.weeklyworkreport', verbose_name='Báo cáo tuần')),
            ],
            options={
                'verbose_name': 'Đính kèm báo cáo tuần',
                'verbose_name_plural': 'Đính kèm báo cáo tuần',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
