# Generated by Django 5.2.7 on 2026-06-16 07:50

import reports.weekly_nas_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_draft_saved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyworkreportattachment',
            name='file',
            field=models.FileField(storage=reports.weekly_nas_storage.WeeklyReportNasStorage(), upload_to=reports.weekly_nas_storage.weekly_attachment_upload_to),
        ),
    ]
