# Generated by Django 5.2.7 on 2026-06-17 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_weekly_attachment_nas_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='shift_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu ca'),
        ),
        migrations.CreateModel(
            name='ProductionShiftProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=80, verbose_name='Mã hàng')),
                ('process_name', models.CharField(max_length=120, verbose_name='Tên công đoạn')),
                ('norm_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Định mức 1 giờ')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang làm'), ('DONE', 'Đã kết thúc')], default='ACTIVE', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_products', to='reports.dailyworkreport', verbose_name='Báo cáo')),
            ],
            options={
                'verbose_name': 'Mã hàng trong ca',
                'verbose_name_plural': 'Mã hàng trong ca',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionHourlyQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField(verbose_name='Khung giờ')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Sản lượng giờ')),
                ('partial_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Giờ thực tế (khi chia giờ)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_entries', to='reports.productionshiftproduct', verbose_name='Mã hàng')),
            ],
            options={
                'verbose_name': 'Sản lượng theo giờ',
                'verbose_name_plural': 'Sản lượng theo giờ',
                'ordering': ['slot_index'],
                'unique_together': {('product', 'slot_index')},
            },
        ),
    ]
