# Generated by Django 5.2.7 on 2026-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_production_hourly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionshiftproduct',
            name='norm_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Định mức 1 giờ'),
        ),
        migrations.AlterField(
            model_name='productionshiftproduct',
            name='process_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Tên công đoạn'),
        ),
        migrations.AlterField(
            model_name='productionshiftproduct',
            name='product_code',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Mã hàng'),
        ),
    ]
