# Generated by Django 5.1.6 on 2026-05-28

import reports.daily_nas_storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_weekly_report_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tab', models.CharField(choices=[('BANG', 'Bảng'), ('VANBAN', 'Văn bản')], max_length=10)),
                ('kind', models.CharField(choices=[('FILE', 'File'), ('IMAGE', 'Ảnh')], max_length=10)),
                ('file', models.FileField(storage=reports.daily_nas_storage.DailyReportNasStorage(), upload_to=reports.daily_nas_storage.daily_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.dailyworkreport', verbose_name='Báo cáo ngày')),
            ],
            options={
                'verbose_name': 'Đính kèm báo cáo ngày',
                'verbose_name_plural': 'Đính kèm báo cáo ngày',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
