# Generated by Django 5.2.7 on 2026-07-02 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_production_decimal_quantities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='proxy_entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_daily_reports_entered', to=settings.AUTH_USER_MODEL, verbose_name='Tổ trưởng nhập hộ'),
        ),
    ]
