# Generated by Django 5.2.7 on 2026-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_dailyworkreport_proxy_entered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='title',
            field=models.CharField(blank=True, help_text='Dùng cho báo cáo tuần / tháng.', max_length=255, verbose_name='Tiêu đề báo cáo'),
        ),
    ]
