# Generated by Django 5.2.7 on 2026-07-03 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_dailyworkreport_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Nội dung nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận xét')),
                ('daily_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.dailyworkreport', verbose_name='Báo cáo ngày')),
                ('weekly_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.weeklyworkreport', verbose_name='Báo cáo tuần')),
            ],
            options={
                'verbose_name': 'Nhận xét báo cáo',
                'verbose_name_plural': 'Nhận xét báo cáo',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
