# Generated by Django 5.2.7 on 2026-07-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_reportcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Đã đọc'),
        ),
    ]
