# Generated by Django 5.2.7 on 2026-07-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_merge_overtime_into_morning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkreport',
            name='title',
            field=models.CharField(blank=True, help_text='Tuỳ chọn với báo cáo ngày; bắt buộc khi nộp báo cáo tuần / tháng.', max_length=255, verbose_name='Tiêu đề báo cáo'),
        ),
    ]
