# Generated by Django 5.2.7 on 2026-07-06 03:35

import django.db.models.deletion
from django.db import migrations, models
import reports.comment_nas_storage


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_alter_dailyworkreport_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FILE', 'File'), ('IMAGE', 'Ảnh')], max_length=10)),
                ('file', models.FileField(storage=reports.comment_nas_storage.ReportCommentNasStorage(), upload_to=reports.comment_nas_storage.comment_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.reportcomment', verbose_name='Nhận xét')),
            ],
            options={
                'verbose_name': 'Đính kèm nhận xét',
                'verbose_name_plural': 'Đính kèm nhận xét',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
