# Generated by Django 5.2.7 on 2026-07-06 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_daily_attachment_file_maxlen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyworkreport',
            options={'ordering': ['-report_date', '-updated_at'], 'verbose_name': 'Báo cáo công việc', 'verbose_name_plural': 'Báo cáo công việc'},
        ),
        migrations.AlterModelOptions(
            name='dailyworkreportattachment',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Đính kèm báo cáo', 'verbose_name_plural': 'Đính kèm báo cáo'},
        ),
        migrations.AlterModelOptions(
            name='weeklyworkreport',
            options={'ordering': ['-week_start', '-updated_at'], 'verbose_name': 'Báo cáo tuần (sản xuất)', 'verbose_name_plural': 'Báo cáo tuần (sản xuất)'},
        ),
        migrations.AlterModelOptions(
            name='weeklyworkreportattachment',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Đính kèm báo cáo tuần (SX)', 'verbose_name_plural': 'Đính kèm báo cáo tuần (SX)'},
        ),
        migrations.AlterField(
            model_name='dailyworkreportattachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.dailyworkreport', verbose_name='Báo cáo'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.dailyworkreport', verbose_name='Báo cáo'),
        ),
    ]
