# Generated by Django 5.2.7 on 2026-07-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_dailyworkreporteditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyworkreporteditlog',
            new_name='reports_dai_report__a79895_idx',
            old_name='reports_dai_report__a8f2c1_idx',
        ),
    ]
