# Generated by Django 5.2.7 on 2026-07-09 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0038_clear_bulk_proxy_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionshiftproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_products_updated', to=settings.AUTH_USER_MODEL, verbose_name='Cập nhật'),
        ),
    ]
