# Generated by Django 5.2.7 on 2026-07-22 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_alter_productionshiftproduct_updated_by_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReportReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Ngày báo cáo')),
                ('shift', models.CharField(choices=[('MORNING', 'Ca sáng'), ('OVERTIME', 'Tăng ca'), ('NIGHT', 'Ca tối')], max_length=20, verbose_name='Ca')),
                ('wave', models.PositiveSmallIntegerField(choices=[(1, 'Đợt 1'), (2, 'Đợt 2')], verbose_name='Đợt nhắc')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_report_reminder_logs', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Log nhắc nộp báo cáo SX',
                'verbose_name_plural': 'Log nhắc nộp báo cáo SX',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'report_date', 'shift', 'wave'), name='uniq_prod_report_reminder_employee_date_shift_wave')],
            },
        ),
    ]
