# Generated by Django 5.2.7 on 2026-07-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_production_report_reminder_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='auto_submitted',
            field=models.BooleanField(default=False, help_text='True khi báo cáo được gửi tự động lúc 11:30 (không phải công nhân / tổ trưởng gửi).', verbose_name='Hệ thống tự động gửi'),
        ),
    ]
