# Generated by Django 5.2.7 on 2026-07-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0046_reportsgeneralsettings_night_auto_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsgeneralsettings',
            name='allow_edit_wrong_stage_time',
            field=models.BooleanField(default=True, help_text='Khi bật — vẫn sửa được giờ công đoạn sai dù đã tắt quyền sửa giờ thường.', verbose_name='Báo cáo sai: cho sửa thời gian công đoạn sai'),
        ),
    ]
