# Generated by Django 5.2.7 on 2026-08-15 02:15

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0049_auto_approve_manager_edited_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReportImageImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Ngày báo cáo')),
                ('shift', models.CharField(choices=[('MORNING', 'Ca sáng'), ('OVERTIME', 'Tăng ca'), ('NIGHT', 'Ca tối')], max_length=20, verbose_name='Ca')),
                ('image', models.ImageField(upload_to=reports.models.production_report_import_upload_to, verbose_name='Ảnh phiếu báo cáo')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Tên file gốc')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu AI trích xuất')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='Lỗi phân tích')),
                ('status', models.CharField(choices=[('PROCESSING', 'Đang phân tích'), ('READY', 'Chờ xác nhận'), ('APPLIED', 'Đã đổ vào báo cáo'), ('FAILED', 'Phân tích lỗi')], db_index=True, default='PROCESSING', max_length=20, verbose_name='Trạng thái')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Đổ dữ liệu lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_imports', to='reports.dailyworkreport', verbose_name='Báo cáo đã đổ dữ liệu')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_report_image_imports', to=settings.AUTH_USER_MODEL, verbose_name='Người tải ảnh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_report_image_imports', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Import ảnh báo cáo SX',
                'verbose_name_plural': 'Import ảnh báo cáo SX',
                'ordering': ['-created_at'],
            },
        ),
    ]
