# Generated by Django 5.2.7 on 2026-08-24 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0052_reportsgeneralsettings_efficiency_caps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDayLeaveMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, verbose_name='Ngày nghỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_day_leave_marks', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_day_leave_marks_created', to=settings.AUTH_USER_MODEL, verbose_name='Người đánh dấu')),
            ],
            options={
                'verbose_name': 'Đánh dấu nghỉ phép SX',
                'verbose_name_plural': 'Đánh dấu nghỉ phép SX',
                'ordering': ['-report_date', '-created_at'],
                'unique_together': {('employee', 'report_date')},
            },
        ),
    ]
