# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0053_production_day_leave_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionshiftproduct',
            name='efficiency_bonus_pct',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Hiệu suất tặng thêm khi chuyển công đoạn mới — tổ trưởng/quản lý nhập.',
                max_digits=6,
                null=True,
                verbose_name='Hiệu suất bù (%)',
            ),
        ),
    ]
