# Generated by Django 5.2.7 on 2026-09-21 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0056_employee_edit_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsgeneralsettings',
            name='approve_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Giờ làm việc sau khi nộp — hạn SLA duyệt (badge quá hạn). Không tính chiều T7 và CN.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Thời hạn duyệt (giờ)'),
        ),
        migrations.AlterField(
            model_name='reportsgeneralsettings',
            name='auto_reject_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Giờ làm việc sau khi nộp — quá hạn tự chuyển «Không duyệt». Không tính chiều T7 và CN.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Thời hạn không duyệt (giờ)'),
        ),
        migrations.AlterField(
            model_name='reportsgeneralsettings',
            name='employee_edit_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Giờ làm việc sau khi nộp — không tính chiều thứ Bảy (từ 12:00) và Chủ nhật.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='Thời hạn CN sửa sau nộp (giờ)'),
        ),
        migrations.AlterField(
            model_name='reportsgeneralsettings',
            name='unapprove_deadline_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Ngày làm việc sau khi duyệt (mỗi ngày = 24 giờ LV, không tính chiều T7 và CN).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Thời hạn hoàn duyệt (ngày làm việc)'),
        ),
    ]
