# Generated by Django 5.2.7 on 2026-05-29 04:51

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Mã URL')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Mô tả ngắn')),
                ('icon', models.CharField(default='bi-folder2', help_text='Ví dụ: bi-people-fill, bi-folder2', max_length=64, verbose_name='Icon Bootstrap')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
            ],
            options={
                'verbose_name': 'Nhóm tài liệu',
                'verbose_name_plural': 'Nhóm tài liệu',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=120, verbose_name='Mã URL')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='Tóm tắt')),
                ('content_type', models.CharField(choices=[('TEXT', 'Văn bản'), ('PDF', 'PDF')], default='TEXT', max_length=10, verbose_name='Loại nội dung')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='Nội dung')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/pdf/', verbose_name='File PDF')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentcategory', verbose_name='Nhóm')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'ordering': ['category__sort_order', 'sort_order', 'title'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
