# Generated by Django 5.2.7 on 2026-05-29 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_seed_sample_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryQAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Lấy tại Google AI Studio. Để trống nếu dùng biến GEMINI_API_KEY trong file .env.', max_length=255, verbose_name='Gemini API Key')),
                ('gemini_model', models.CharField(choices=[('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-1.5-flash', 'Gemini 1.5 Flash')], default='gemini-1.5-pro', max_length=64, verbose_name='Model')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_qa_config_updates', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Cấu hình Hỏi đáp AI',
                'verbose_name_plural': 'Cấu hình Hỏi đáp AI',
            },
        ),
    ]
