# Generated by Django 5.2.7 on 2026-05-29 09:26

from django.db import migrations, models


def migrate_legacy_models(apps, schema_editor):
    LibraryQAConfig = apps.get_model('documents', 'LibraryQAConfig')
    legacy = {
        'gemini-1.5-pro': 'gemini-2.5-flash',
        'gemini-1.5-flash': 'gemini-2.5-flash',
        'gemini-2.0-flash': 'gemini-2.5-flash',
    }
    for cfg in LibraryQAConfig.objects.all():
        if cfg.gemini_model in legacy:
            cfg.gemini_model = legacy[cfg.gemini_model]
            cfg.save(update_fields=['gemini_model'])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_library_qa_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryqaconfig',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.5-flash', 'Nhanh & cân bằng'), ('gemini-2.5-pro', 'Chi tiết & chính xác'), ('gemini-flash-latest', 'Tự động cập nhật (flash)')], default='gemini-2.5-flash', max_length=64, verbose_name='Model'),
        ),
        migrations.RunPython(migrate_legacy_models, migrations.RunPython.noop),
    ]
