server {
    listen 80;
    server_name portfolio.phongkstudio.com;

    client_max_body_size 6m;

    include /etc/nginx/conf.d/security-headers.conf;
    include /etc/nginx/error-pages.conf;
    include /etc/nginx/scanner-block.conf;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
