# Generated by Django — initial audit log model

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(choices=[('view', 'Xem trang'), ('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('login', 'Đăng nhập'), ('logout', 'Đăng xuất'), ('login_failed', 'Đăng nhập thất bại'), ('export', 'Xuất dữ liệu'), ('import', 'Nhập dữ liệu'), ('other', 'Khác')], db_index=True, max_length=32)),
                ('module_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('module_label', models.CharField(blank=True, max_length=128)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('path', models.CharField(blank=True, db_index=True, max_length=500)),
                ('url_name', models.CharField(blank=True, max_length=128)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('query_string', models.CharField(blank=True, max_length=1000)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('object_type', models.CharField(blank=True, max_length=128)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhật ký thao tác',
                'verbose_name_plural': 'Nhật ký thao tác',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='audit_useract_user_id_created_idx'),
                    models.Index(fields=['action', '-created_at'], name='audit_useract_action_created_idx'),
                    models.Index(fields=['module_key', '-created_at'], name='audit_useract_module_created_idx'),
                    models.Index(fields=['username', '-created_at'], name='audit_useract_username_created_idx'),
                ],
            },
        ),
    ]
