# Generated by Django 5.2.7 on 2026-05-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_useractivitylog_machine_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='audit_usera_user_id_1d091e_idx',
            old_name='audit_useract_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='audit_usera_action_be4952_idx',
            old_name='audit_useract_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='audit_usera_module__088d1b_idx',
            old_name='audit_useract_module_created_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='audit_usera_usernam_dcc753_idx',
            old_name='audit_useract_username_created_idx',
        ),
    ]
