# Generated by Django 5.2.7 on 2026-06-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_drop_axes_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP truy cập'),
        ),
    ]
