# Generated by Django 5.2.7 on 2026-09-14 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_emailsmtpconfig_ssl_verify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileScanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Bật quét virus file upload')),
                ('fail_closed', models.BooleanField(default=False, help_text='Bật: ClamAV lỗi thì không nhận file (an toàn hơn nhưng scanner chết là không ai gửi được đính kèm). Tắt: cho qua và ghi log cảnh báo.', verbose_name='Từ chối file khi không quét được')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_scan_configs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Cập nhật bởi')),
            ],
            options={
                'verbose_name': 'Cấu hình quét virus file',
                'verbose_name_plural': 'Cấu hình quét virus file',
            },
        ),
    ]
