# Generated by Django 5.2.7 on 2026-05-29 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_batch', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('task_type', models.CharField(choices=[('PRODUCTION', 'Sản xuất'), ('OFFICE', 'Văn phòng'), ('GENERAL', 'Chung')], default='GENERAL', max_length=20, verbose_name='Loại việc')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('NORMAL', 'Bình thường'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='NORMAL', max_length=10, verbose_name='Ưu tiên')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn hoàn thành')),
                ('status', models.CharField(choices=[('pending_ack', 'Chờ xác nhận'), ('in_progress', 'Đang thực hiện'), ('rejected', 'Đã từ chối'), ('pending_review', 'Chờ duyệt'), ('revision', 'Cần sửa lại'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('reassigned', 'Đã giao lại')], db_index=True, default='pending_ack', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Tiến độ %')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('result_note', models.TextField(blank=True, verbose_name='Kết quả / báo cáo')),
                ('review_note', models.TextField(blank=True, verbose_name='Ghi chú duyệt')),
                ('order_code', models.CharField(blank=True, max_length=80, verbose_name='Mã đơn/Style')),
                ('product_name', models.CharField(blank=True, max_length=120, verbose_name='Tên SP / hạng mục')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_work_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_work_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người giao')),
                ('reassigned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments', to='tasks.worktask', verbose_name='Giao lại từ')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='tasks.worktask', verbose_name='Thay bằng việc')),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Công việc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assigned', 'Giao việc'), ('acknowledged', 'Xác nhận'), ('rejected', 'Từ chối'), ('progress', 'Cập nhật tiến độ'), ('submitted', 'Nộp hoàn thành'), ('approved', 'Duyệt'), ('revision', 'Yêu cầu sửa'), ('reassigned', 'Giao lại'), ('cancelled', 'Hủy')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_task_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.worktask')),
            ],
            options={
                'verbose_name': 'Nhật ký công việc',
                'verbose_name_plural': 'Nhật ký công việc',
                'ordering': ['created_at'],
            },
        ),
    ]
