# Generated by Django 5.2.7 on 2026-05-29 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktask',
            name='order_code',
        ),
        migrations.RemoveField(
            model_name='worktask',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='worktasklog',
            name='action',
            field=models.CharField(choices=[('assigned', 'Giao việc'), ('acknowledged', 'Xác nhận'), ('rejected', 'Từ chối'), ('progress', 'Cập nhật tiến độ'), ('submitted', 'Nộp hoàn thành'), ('approved', 'Duyệt'), ('revision', 'Yêu cầu sửa'), ('reassigned', 'Giao lại'), ('cancelled', 'Hủy'), ('attachment', 'Đính kèm')], max_length=20),
        ),
        migrations.CreateModel(
            name='WorkTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/attachments/%Y/%m/', verbose_name='File đính kèm')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Tên file gốc')),
                ('stage', models.CharField(choices=[('assign', 'Khi giao việc'), ('work', 'Kết quả đã làm')], db_index=True, default='assign', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.worktask', verbose_name='Công việc')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Đính kèm công việc',
                'verbose_name_plural': 'Đính kèm công việc',
                'ordering': ['created_at'],
            },
        ),
    ]
