# Generated by Django 5.2.7 on 2026-05-29 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_worktask_order_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_steps', to='tasks.worktask', verbose_name='Phụ thuộc bước'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='step_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='status',
            field=models.CharField(choices=[('pending_ack', 'Chờ xác nhận'), ('in_progress', 'Đang thực hiện'), ('rejected', 'Đã từ chối'), ('pending_review', 'Chờ duyệt'), ('revision', 'Cần sửa lại'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('reassigned', 'Đã giao lại'), ('blocked', 'Chờ bước trước'), ('handed_off', 'Đã chuyển giao')], db_index=True, default='pending_ack', max_length=20),
        ),
        migrations.AlterField(
            model_name='worktasklog',
            name='action',
            field=models.CharField(choices=[('assigned', 'Giao việc'), ('acknowledged', 'Xác nhận'), ('rejected', 'Từ chối'), ('progress', 'Cập nhật tiến độ'), ('submitted', 'Nộp hoàn thành'), ('approved', 'Duyệt'), ('revision', 'Yêu cầu sửa'), ('reassigned', 'Giao lại'), ('cancelled', 'Hủy'), ('attachment', 'Đính kèm'), ('handoff', 'Chuyển giao')], max_length=20),
        ),
        migrations.CreateModel(
            name='InternalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên dự án')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn dự án')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang chạy'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='internal_projects', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_internal_projects', to=settings.AUTH_USER_MODEL, verbose_name='Chủ dự án')),
            ],
            options={
                'verbose_name': 'Dự án nội bộ',
                'verbose_name_plural': 'Dự án nội bộ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='worktask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.internalproject', verbose_name='Dự án'),
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL)),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='mentioned_in_project_comments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.internalproject')),
            ],
            options={
                'verbose_name': 'Comment dự án',
                'verbose_name_plural': 'Comment dự án',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkTaskHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú chuyển giao')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_handoff', to='tasks.worktask')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs_from', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='tasks.internalproject')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_requests', to='tasks.worktask')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chuyển giao bước',
                'verbose_name_plural': 'Chuyển giao bước',
                'ordering': ['-created_at'],
            },
        ),
    ]
