# Generated by Django 5.2.7 on 2026-05-30 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0022_add_service_requests_module'),
        ('tasks', '0003_worktask_depends_on_worktask_step_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalproject',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='cross_department_projects', to='hrm.department', verbose_name='Phòng ban tham gia'),
        ),
        migrations.AddField(
            model_name='internalproject',
            name='project_type',
            field=models.CharField(choices=[('team', 'Nội bộ'), ('cross_dept', 'Liên phòng ban')], db_index=True, default='team', max_length=20, verbose_name='Loại dự án'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='assignee_mode',
            field=models.CharField(choices=[('specific', 'Chỉ định người'), ('dept_queue', 'Hàng đợi phòng ban')], default='specific', max_length=20, verbose_name='Cách gán người'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_task_steps', to='hrm.department', verbose_name='Phòng ban xử lý'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_work_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='status',
            field=models.CharField(choices=[('pending_ack', 'Chờ xác nhận'), ('in_progress', 'Đang thực hiện'), ('rejected', 'Đã từ chối'), ('pending_review', 'Chờ duyệt'), ('revision', 'Cần sửa lại'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('reassigned', 'Đã giao lại'), ('blocked', 'Chờ bước trước'), ('handed_off', 'Đã chuyển giao'), ('pending_claim', 'Chờ tiếp nhận')], db_index=True, default='pending_ack', max_length=20),
        ),
    ]
