# Generated by Django 5.2.7 on 2026-07-17 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('san_xuat', '0014_phase3_ops_extensions'),
        ('tasks', '0006_worktask_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='process_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Công đoạn'),
        ),
        migrations.AddField(
            model_name='worktask',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_tasks', to='san_xuat.sxproductionorder', verbose_name='LSX'),
        ),
    ]
