# Generated by Django 5.2.7 on 2026-07-02 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề khảo sát')),
                ('question', models.TextField(help_text='Câu hỏi nhân viên cần trả lời.', verbose_name='Nội dung câu hỏi')),
                ('reference_url', models.URLField(blank=True, help_text='Link tài liệu / Google Form gốc (tuỳ chọn).', verbose_name='Link tham khảo')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang mở')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Hạn nhận câu hỏi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Khảo sát',
                'verbose_name_plural': 'Khảo sát',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='Nội dung câu hỏi')),
                ('employee_code', models.CharField(blank=True, max_length=50, verbose_name='Mã NV')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Họ và tên')),
                ('department_name', models.CharField(blank=True, max_length=255, verbose_name='Bộ phận')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='Khảo sát')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Phản hồi khảo sát',
                'verbose_name_plural': 'Phản hồi khảo sát',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('survey', 'user'), name='surveys_unique_response_per_user')],
            },
        ),
    ]
