# Generated by Django 5.2.7 on 2026-07-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        ('training', '0005_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='required_course',
            field=models.ForeignKey(blank=True, help_text='Nhân viên phải hoàn thành bài học này trước khi trả lời khảo sát.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_surveys', to='training.course', verbose_name='Bài học bắt buộc'),
        ),
    ]
