# Generated by Django 5.2.7 on 2026-07-02 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_required_course'),
        ('training', '0005_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='required_course',
            field=models.ForeignKey(blank=True, help_text='Nhân viên có thể bấm học trước (không bắt buộc) rồi quay lại khảo sát.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_surveys', to='training.course', verbose_name='Bài học gợi ý'),
        ),
    ]
