# Generated by Django 5.2.7 on 2026-07-02 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_required_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=50, verbose_name='Mã NV')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Họ và tên')),
                ('department_name', models.CharField(blank=True, max_length=255, verbose_name='Bộ phận')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Lần xem đầu')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='Lần xem gần nhất')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='surveys.survey', verbose_name='Khảo sát')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_views', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Lượt xem khảo sát',
                'verbose_name_plural': 'Lượt xem khảo sát',
                'ordering': ['-last_viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('survey', 'user'), name='surveys_unique_view_per_user')],
            },
        ),
    ]
