from hrm.module_permissions import (
    MODULE_ANNOUNCEMENTS,
    MODULE_ASSESSMENT,
    MODULE_DOCUMENTS,
    MODULE_GUIDE,
    MODULE_HRM,
    MODULE_KPI,
    MODULE_RECRUITMENT,
    MODULE_REPORTS,
    MODULE_TRAINING,
    bypass_department_modules,
    get_user_enabled_modules,
    user_can_access_module,
    user_can_edit_module,
)
from hrm.permissions import (
    can_edit_user_guide,
    can_view_team_reports,
    is_gm,
    is_hod,
    is_manager,
    is_portal_admin,
    is_team_leader,
    is_division_head,
    role_display,
    user_role,
)


def portal_permissions(request):
    user = request.user
    if not user.is_authenticated:
        return {
            'jp_can_portal_admin': False,
            'jp_can_edit_guide': False,
            'jp_is_hod': False,
            'jp_is_gm': False,
            'jp_is_team_leader': False,
            'jp_is_division_head': False,
            'jp_is_manager': False,
            'jp_can_team_reports': False,
            'jp_user_role': '',
            'jp_role_display': '',
            'jp_enabled_modules': set(),
            'jp_can_announcements': False,
            'jp_can_recruitment': False,
            'jp_can_training': False,
            'jp_can_assessment': False,
            'jp_can_hrm': False,
            'jp_can_kpi': False,
            'jp_can_reports': False,
            'jp_can_guide': False,
            'jp_can_documents': False,
            'jp_can_edit_announcements': False,
            'jp_can_edit_recruitment': False,
            'jp_can_edit_training': False,
            'jp_can_edit_assessment': False,
            'jp_can_edit_hrm': False,
            'jp_can_edit_kpi': False,
            'jp_can_edit_reports': False,
            'jp_can_edit_guide': False,
            'jp_can_edit_documents': False,
            'jp_can_manage_permissions': False,
        }
    enabled = get_user_enabled_modules(user)
    return {
        'jp_can_portal_admin': is_portal_admin(user),
        'jp_can_edit_guide': can_edit_user_guide(user),
        'jp_is_hod': is_hod(user),
        'jp_is_gm': is_gm(user),
        'jp_is_team_leader': is_team_leader(user),
        'jp_is_division_head': is_division_head(user),
        'jp_is_manager': is_manager(user),
        'jp_can_team_reports': can_view_team_reports(user),
        'jp_user_role': user_role(user),
        'jp_role_display': role_display(user),
        'jp_enabled_modules': enabled,
        'jp_can_announcements': user_can_access_module(user, MODULE_ANNOUNCEMENTS),
        'jp_can_recruitment': user_can_access_module(user, MODULE_RECRUITMENT),
        'jp_can_training': user_can_access_module(user, MODULE_TRAINING),
        'jp_can_assessment': user_can_access_module(user, MODULE_ASSESSMENT),
        'jp_can_hrm': user_can_access_module(user, MODULE_HRM),
        'jp_can_kpi': user_can_access_module(user, MODULE_KPI),
        'jp_can_reports': user_can_access_module(user, MODULE_REPORTS),
        'jp_can_guide': user_can_access_module(user, MODULE_GUIDE),
        'jp_can_documents': user_can_access_module(user, MODULE_DOCUMENTS),
        'jp_can_edit_announcements': user_can_edit_module(user, MODULE_ANNOUNCEMENTS),
        'jp_can_edit_recruitment': user_can_edit_module(user, MODULE_RECRUITMENT),
        'jp_can_edit_training': user_can_edit_module(user, MODULE_TRAINING),
        'jp_can_edit_assessment': user_can_edit_module(user, MODULE_ASSESSMENT),
        'jp_can_edit_hrm': user_can_edit_module(user, MODULE_HRM),
        'jp_can_edit_kpi': user_can_edit_module(user, MODULE_KPI),
        'jp_can_edit_reports': user_can_edit_module(user, MODULE_REPORTS),
        'jp_can_edit_guide': user_can_edit_module(user, MODULE_GUIDE),
        'jp_can_edit_documents': user_can_edit_module(user, MODULE_DOCUMENTS),
        'jp_can_manage_permissions': user_can_edit_module(user, MODULE_HRM) or bypass_department_modules(user),
    }
