from hrm.module_permissions import (
    MODULE_AUDIT,
    MODULE_ANNOUNCEMENTS,
    MODULE_ASSESSMENT,
    MODULE_DOCUMENTS,
    MODULE_GUIDE,
    MODULE_HRM,
    MODULE_KPI,
    MODULE_PERMISSIONS,
    MODULE_RECRUITMENT,
    MODULE_REPORTS,
    MODULE_TASKS,
    MODULE_DE_XUAT,
    MODULE_HO_TRO,
    MODULE_NAS_STORAGE,
    MODULE_EQUIPMENT,
    MODULE_FEEDBACK,
    MODULE_KIOTVIET,
    MODULE_KHO_NPL,
    MODULE_TRAINING,
    bypass_department_modules,
    get_user_enabled_modules,
    user_can_access_module,
    user_can_create_module,
    user_can_delete_module,
    user_can_edit_module,
    user_can_export_module,
    user_can_update_module,
)
from hrm.permissions import (
    can_assign_tasks,
    can_create_cross_dept_project,
    can_create_internal_project,
    can_edit_user_guide,
    can_receive_assigned_tasks,
    can_submit_daily_report,
    can_view_team_reports,
    is_gm,
    is_hod,
    is_manager,
    is_portal_admin,
    is_team_leader,
    is_division_head,
    is_department_head,
    role_display,
    user_role,
)


def _jp_concurrent_positions(user):
    from hrm.concurrent_positions import concurrent_positions_summary, get_profile

    profile = get_profile(user)
    if not profile:
        return []
    return concurrent_positions_summary(profile)


def portal_permissions(request):
    user = request.user
    if not user.is_authenticated:
        return {
            'jp_force_password_change': False,
            'jp_can_portal_admin': False,
            'jp_can_edit_guide': False,
            'jp_is_hod': False,
            'jp_is_gm': False,
            'jp_is_team_leader': False,
            'jp_is_division_head': False,
            'jp_is_department_head': False,
            'jp_is_manager': False,
            'jp_can_team_reports': False,
            'jp_can_submit_reports': False,
            'jp_user_role': '',
            'jp_role_display': '',
            'jp_concurrent_positions': [],
            'jp_enabled_modules': set(),
            'jp_can_announcements': False,
            'jp_can_recruitment': False,
            'jp_can_training': False,
            'jp_can_assessment': False,
            'jp_can_hrm': False,
            'jp_can_kpi': False,
            'jp_can_reports': False,
            'jp_can_guide': False,
            'jp_can_documents': False,
            'jp_can_permissions': False,
            'jp_can_audit': False,
            'jp_can_edit_audit': False,
            'jp_can_export_audit': False,
            'jp_can_tasks': False,
            'jp_can_de_xuat': False,
            'jp_can_ho_tro': False,
            'jp_de_xuat_pending_count': 0,
            'jp_ho_tro_pending_count': 0,
            'jp_can_manage_catalog': False,
            'jp_can_nas_storage': False,
            'jp_can_equipment': False,
            'jp_can_feedback': False,
            'jp_can_kiotviet': False,
            'jp_can_kho_npl': False,
            'jp_can_assign_tasks': False,
            'jp_can_create_internal_project': False,
            'jp_can_create_cross_dept': False,
            'jp_can_receive_tasks': False,
            'jp_can_edit_announcements': False,
            'jp_can_create_announcements': False,
            'jp_can_update_announcements': False,
            'jp_can_delete_announcements': False,
            'jp_can_edit_recruitment': False,
            'jp_can_create_recruitment': False,
            'jp_can_update_recruitment': False,
            'jp_can_delete_recruitment': False,
            'jp_can_edit_training': False,
            'jp_can_create_training': False,
            'jp_can_update_training': False,
            'jp_can_delete_training': False,
            'jp_can_edit_assessment': False,
            'jp_can_create_assessment': False,
            'jp_can_update_assessment': False,
            'jp_can_delete_assessment': False,
            'jp_can_edit_hrm': False,
            'jp_can_create_hrm': False,
            'jp_can_update_hrm': False,
            'jp_can_delete_hrm': False,
            'jp_can_edit_kpi': False,
            'jp_can_edit_reports': False,
            'jp_can_create_reports': False,
            'jp_can_update_reports': False,
            'jp_can_delete_reports': False,
            'jp_can_edit_guide': False,
            'jp_can_update_guide': False,
            'jp_can_edit_documents': False,
            'jp_can_create_documents': False,
            'jp_can_update_documents': False,
            'jp_can_delete_documents': False,
            'jp_can_edit_permissions': False,
            'jp_can_create_permissions': False,
            'jp_can_update_permissions': False,
            'jp_can_delete_permissions': False,
            'jp_can_create_de_xuat': False,
            'jp_can_update_de_xuat': False,
            'jp_can_delete_de_xuat': False,
            'jp_can_create_ho_tro': False,
            'jp_can_update_ho_tro': False,
            'jp_can_delete_ho_tro': False,
            'jp_can_create_kiotviet': False,
            'jp_can_update_kiotviet': False,
            'jp_can_delete_kiotviet': False,
            'jp_can_edit_kho_npl': False,
            'jp_can_create_kho_npl': False,
            'jp_can_update_kho_npl': False,
            'jp_can_delete_kho_npl': False,
            'jp_can_export_kho_npl': False,
            'jp_can_edit_tasks': False,
            'jp_can_create_tasks': False,
            'jp_can_update_tasks': False,
            'jp_can_delete_tasks': False,
            'jp_can_edit_nas_storage': False,
            'jp_can_update_nas_storage': False,
            'jp_can_edit_equipment': False,
            'jp_can_edit_feedback': False,
            'jp_can_create_feedback': False,
            'jp_can_update_feedback': False,
            'jp_can_delete_feedback': False,
            'jp_can_export_hrm': False,
            'jp_can_export_recruitment': False,
            'jp_can_export_equipment': False,
            'jp_can_create_kpi': False,
            'jp_can_update_kpi': False,
            'jp_can_delete_kpi': False,
            'jp_can_create_equipment': False,
            'jp_can_update_equipment': False,
            'jp_can_delete_equipment': False,
            'jp_can_create_nas_storage': False,
            'jp_can_delete_nas_storage': False,
            'jp_can_manage_permissions': False,
        }
    enabled = get_user_enabled_modules(user)
    profile = getattr(user, 'profile', None)
    base = {
        'jp_force_password_change': bool(profile and profile.must_change_password),
        'jp_can_portal_admin': is_portal_admin(user),
        'jp_can_edit_guide': can_edit_user_guide(user),
        'jp_is_hod': is_hod(user),
        'jp_is_gm': is_gm(user),
        'jp_is_team_leader': is_team_leader(user),
        'jp_is_division_head': is_division_head(user),
        'jp_is_department_head': is_department_head(user),
        'jp_is_manager': is_manager(user),
        'jp_can_team_reports': can_view_team_reports(user),
        'jp_can_submit_reports': can_submit_daily_report(user),
        'jp_user_role': user_role(user),
        'jp_role_display': role_display(user),
        'jp_concurrent_positions': _jp_concurrent_positions(user),
        'jp_enabled_modules': enabled,
        'jp_can_announcements': user_can_access_module(user, MODULE_ANNOUNCEMENTS),
        'jp_can_recruitment': user_can_access_module(user, MODULE_RECRUITMENT),
        'jp_can_training': user_can_access_module(user, MODULE_TRAINING),
        'jp_can_assessment': user_can_access_module(user, MODULE_ASSESSMENT),
        'jp_can_hrm': user_can_access_module(user, MODULE_HRM),
        'jp_can_kpi': user_can_access_module(user, MODULE_KPI),
        'jp_can_reports': user_can_access_module(user, MODULE_REPORTS),
        'jp_can_guide': user_can_access_module(user, MODULE_GUIDE),
        'jp_can_documents': user_can_access_module(user, MODULE_DOCUMENTS),
        'jp_can_permissions': user_can_access_module(user, MODULE_PERMISSIONS),
        'jp_can_audit': user_can_access_module(user, MODULE_AUDIT),
        'jp_can_edit_audit': user_can_edit_module(user, MODULE_AUDIT),
        'jp_can_export_audit': user_can_export_module(user, MODULE_AUDIT),
        'jp_can_tasks': user_can_access_module(user, MODULE_TASKS),
        'jp_can_de_xuat': user_can_access_module(user, MODULE_DE_XUAT),
        'jp_can_ho_tro': user_can_access_module(user, MODULE_HO_TRO),
        'jp_can_nas_storage': user_can_access_module(user, MODULE_NAS_STORAGE),
        'jp_can_equipment': user_can_access_module(user, MODULE_EQUIPMENT),
        'jp_can_feedback': user_can_access_module(user, MODULE_FEEDBACK),
        'jp_can_kiotviet': _jp_can_kiotviet(user),
        'jp_can_kho_npl': user_can_access_module(user, MODULE_KHO_NPL),
        'jp_can_assign_tasks': can_assign_tasks(user),
        'jp_can_create_internal_project': can_create_internal_project(user),
        'jp_can_create_cross_dept': can_create_cross_dept_project(user),
        'jp_can_receive_tasks': can_receive_assigned_tasks(user),
        'jp_can_edit_announcements': user_can_edit_module(user, MODULE_ANNOUNCEMENTS),
        'jp_can_create_announcements': user_can_create_module(user, MODULE_ANNOUNCEMENTS),
        'jp_can_update_announcements': user_can_update_module(user, MODULE_ANNOUNCEMENTS),
        'jp_can_delete_announcements': user_can_delete_module(user, MODULE_ANNOUNCEMENTS),
        'jp_can_edit_recruitment': user_can_edit_module(user, MODULE_RECRUITMENT),
        'jp_can_create_recruitment': user_can_create_module(user, MODULE_RECRUITMENT),
        'jp_can_update_recruitment': user_can_update_module(user, MODULE_RECRUITMENT),
        'jp_can_delete_recruitment': user_can_delete_module(user, MODULE_RECRUITMENT),
        'jp_can_edit_training': user_can_edit_module(user, MODULE_TRAINING),
        'jp_can_create_training': user_can_create_module(user, MODULE_TRAINING),
        'jp_can_update_training': user_can_update_module(user, MODULE_TRAINING),
        'jp_can_delete_training': user_can_delete_module(user, MODULE_TRAINING),
        'jp_can_edit_assessment': user_can_edit_module(user, MODULE_ASSESSMENT),
        'jp_can_create_assessment': user_can_create_module(user, MODULE_ASSESSMENT),
        'jp_can_update_assessment': user_can_update_module(user, MODULE_ASSESSMENT),
        'jp_can_delete_assessment': user_can_delete_module(user, MODULE_ASSESSMENT),
        'jp_can_edit_hrm': user_can_edit_module(user, MODULE_HRM),
        'jp_can_create_hrm': user_can_create_module(user, MODULE_HRM),
        'jp_can_update_hrm': user_can_update_module(user, MODULE_HRM),
        'jp_can_delete_hrm': user_can_delete_module(user, MODULE_HRM),
        'jp_can_edit_kpi': user_can_edit_module(user, MODULE_KPI),
        'jp_can_edit_reports': user_can_edit_module(user, MODULE_REPORTS),
        'jp_can_create_reports': user_can_create_module(user, MODULE_REPORTS),
        'jp_can_update_reports': user_can_update_module(user, MODULE_REPORTS),
        'jp_can_delete_reports': user_can_delete_module(user, MODULE_REPORTS),
        'jp_can_edit_guide': user_can_edit_module(user, MODULE_GUIDE),
        'jp_can_update_guide': user_can_update_module(user, MODULE_GUIDE),
        'jp_can_edit_documents': user_can_edit_module(user, MODULE_DOCUMENTS),
        'jp_can_create_documents': user_can_create_module(user, MODULE_DOCUMENTS),
        'jp_can_update_documents': user_can_update_module(user, MODULE_DOCUMENTS),
        'jp_can_delete_documents': user_can_delete_module(user, MODULE_DOCUMENTS),
        'jp_can_edit_permissions': user_can_edit_module(user, MODULE_PERMISSIONS),
        'jp_can_create_permissions': user_can_create_module(user, MODULE_PERMISSIONS),
        'jp_can_update_permissions': user_can_update_module(user, MODULE_PERMISSIONS),
        'jp_can_delete_permissions': user_can_delete_module(user, MODULE_PERMISSIONS),
        'jp_can_create_de_xuat': user_can_create_module(user, MODULE_DE_XUAT),
        'jp_can_update_de_xuat': user_can_update_module(user, MODULE_DE_XUAT),
        'jp_can_delete_de_xuat': user_can_delete_module(user, MODULE_DE_XUAT),
        'jp_can_create_ho_tro': user_can_create_module(user, MODULE_HO_TRO),
        'jp_can_update_ho_tro': user_can_update_module(user, MODULE_HO_TRO),
        'jp_can_delete_ho_tro': user_can_delete_module(user, MODULE_HO_TRO),
        'jp_can_create_kiotviet': user_can_create_module(user, MODULE_KIOTVIET),
        'jp_can_update_kiotviet': user_can_update_module(user, MODULE_KIOTVIET),
        'jp_can_delete_kiotviet': user_can_delete_module(user, MODULE_KIOTVIET),
        'jp_can_edit_kho_npl': user_can_edit_module(user, MODULE_KHO_NPL),
        'jp_can_create_kho_npl': user_can_create_module(user, MODULE_KHO_NPL),
        'jp_can_update_kho_npl': user_can_update_module(user, MODULE_KHO_NPL),
        'jp_can_delete_kho_npl': user_can_delete_module(user, MODULE_KHO_NPL),
        'jp_can_export_kho_npl': user_can_export_module(user, MODULE_KHO_NPL),
        'jp_can_edit_tasks': user_can_edit_module(user, MODULE_TASKS),
        'jp_can_create_tasks': user_can_create_module(user, MODULE_TASKS),
        'jp_can_update_tasks': user_can_update_module(user, MODULE_TASKS),
        'jp_can_delete_tasks': user_can_delete_module(user, MODULE_TASKS),
        'jp_can_edit_nas_storage': user_can_edit_module(user, MODULE_NAS_STORAGE),
        'jp_can_update_nas_storage': user_can_update_module(user, MODULE_NAS_STORAGE),
        'jp_can_edit_equipment': user_can_edit_module(user, MODULE_EQUIPMENT),
        'jp_can_edit_feedback': user_can_edit_module(user, MODULE_FEEDBACK),
        'jp_can_create_feedback': user_can_create_module(user, MODULE_FEEDBACK),
        'jp_can_update_feedback': user_can_update_module(user, MODULE_FEEDBACK),
        'jp_can_delete_feedback': user_can_delete_module(user, MODULE_FEEDBACK),
        'jp_can_export_hrm': user_can_export_module(user, MODULE_HRM),
        'jp_can_export_recruitment': user_can_export_module(user, MODULE_RECRUITMENT),
        'jp_can_export_equipment': user_can_export_module(user, MODULE_EQUIPMENT),
        'jp_can_create_kpi': user_can_create_module(user, MODULE_KPI),
        'jp_can_update_kpi': user_can_update_module(user, MODULE_KPI),
        'jp_can_delete_kpi': user_can_delete_module(user, MODULE_KPI),
        'jp_can_create_equipment': user_can_create_module(user, MODULE_EQUIPMENT),
        'jp_can_update_equipment': user_can_update_module(user, MODULE_EQUIPMENT),
        'jp_can_delete_equipment': user_can_delete_module(user, MODULE_EQUIPMENT),
        'jp_can_create_nas_storage': user_can_create_module(user, MODULE_NAS_STORAGE),
        'jp_can_delete_nas_storage': user_can_delete_module(user, MODULE_NAS_STORAGE),
        'jp_can_manage_permissions': user_can_edit_module(user, MODULE_PERMISSIONS) or bypass_department_modules(user),
    }
    from service_requests.portal_nav import portal_nav_context

    try:
        base.update(portal_nav_context(user))
    except Exception as exc:
        import logging
        logging.getLogger(__name__).warning('portal_nav_context failed: %s', exc)
        base.update({
            'jp_de_xuat_pending_count': 0,
            'jp_ho_tro_pending_count': 0,
            'jp_can_manage_catalog': False,
        })
    return base


def _jp_can_kiotviet(user) -> bool:
    try:
        from kiotviet.access import user_can_use_kiotviet
        return user_can_use_kiotviet(user)
    except Exception:
        return False
