"""
URL chụp ảnh minh họa từng bước hướng dẫn — {section}-{nn}.png
"""

# filename (không .png) -> (path, wait_selector)
STEP_SCREENSHOTS: dict[str, tuple[str, str]] = {
    # Đăng nhập & nền tảng
    'dang-nhap-01': ('/accounts/login/', '.card-login'),
    'dang-nhap-02': ('/accounts/login/', '.card-login'),
    'dang-nhap-03': ('/accounts/login/', '.card-login'),
    'dang-nhap-04': ('/accounts/login/', '.card-login'),
    'dang-nhap-05': ('/', '.portal-container'),
    'doi-mat-khau-01': ('/change-password/', '.jp-page'),
    'doi-mat-khau-02': ('/change-password/', '.jp-page'),
    'doi-mat-khau-03': ('/change-password/', '.jp-page'),
    'doi-mat-khau-04': ('/', '.portal-container'),
    'bat-dau-01': ('/accounts/login/', '.card-login'),
    'bat-dau-02': ('/accounts/login/', '.card-login'),
    'bat-dau-03': ('/change-password/', '.jp-page'),
    'bat-dau-04': ('/announcements/', '.jp-page'),
    'gioi-thieu-01': ('/', '.portal-container'),
    'gioi-thieu-02': ('/', '.portal-container'),
    'gioi-thieu-03': ('/announcements/', '.jp-page'),
    'gioi-thieu-04': ('/huong-dan/', '.jp-guide-page'),
    'chuan-bi-01': ('/accounts/login/', '.card-login'),
    'chuan-bi-02': ('/accounts/login/', '.card-login'),
    'chuan-bi-03': ('/change-password/', '.jp-page'),
    'chuan-bi-04': ('/', '.portal-container'),
    # Thông báo & báo cáo
    'thong-bao-01': ('/announcements/', '.jp-page'),
    'thong-bao-02': ('/announcements/', '.jp-page'),
    'thong-bao-03': ('/announcements/', '.jp-page'),
    'thong-bao-04': ('/announcements/', '.jp-page'),
    'thong-bao-05': ('/announcements/', '.jp-page'),
    'thong-bao-06': ('/announcements/', '.jp-page'),
    'thong-bao-07': ('/announcements/', '.jp-page'),
    'thong-bao-08': ('/announcements/', '.jp-page'),
    'thong-bao-09': ('/announcements/', '.jp-page'),
    'thong-bao-10': ('/announcements/', '.jp-page'),
    'bao-cao-01': ('/reports/today/', '.jp-page'),
    'bao-cao-02': ('/reports/today/', '.jp-page'),
    'bao-cao-03': ('/reports/today/', '.jp-page'),
    'bao-cao-04': ('/reports/today/', '.jp-page'),
    'bao-cao-05': ('/reports/today/', '.jp-page'),
    'bao-cao-06': ('/reports/today/', '.jp-page'),
    'bao-cao-07': ('/reports/today/', '.jp-page'),
    'bao-cao-08': ('/reports/my/', '.jp-page'),
    'bao-cao-09': ('/reports/team/', '.jp-page'),
    'bao-cao-10': ('/reports/team/', '.jp-page'),
    'bao-cao-11': ('/reports/team/', '.jp-page'),
    'bao-cao-12': ('/reports/team/', '.jp-page'),
    'bao-cao-13': ('/reports/team/', '.jp-page'),
    # Đào tạo & kiểm tra
    'dao-tao-01': ('/training/my-courses/', '.jp-page'),
    'dao-tao-02': ('/training/my-courses/', '.jp-page'),
    'dao-tao-03': ('/training/my-courses/', '.jp-page'),
    'dao-tao-04': ('/training/my-courses/', '.jp-page'),
    'dao-tao-05': ('/training/my-courses/', '.jp-page'),
    'dao-tao-06': ('/training/my-courses/', '.jp-page'),
    'kiem-tra-01': ('/exams/', '.jp-page'),
    'kiem-tra-02': ('/exams/', '.jp-page'),
    'kiem-tra-03': ('/exams/', '.jp-page'),
    'kiem-tra-04': ('/exams/', '.jp-page'),
    'kiem-tra-05': ('/exams/', '.jp-page'),
    'kpi-01': ('/kpi/', '.jp-page'),
    'kpi-02': ('/kpi/', '.jp-page'),
    'kpi-03': ('/kpi/', '.jp-page'),
    'kpi-04': ('/kpi/', '.jp-page'),
    'kpi-05': ('/kpi/', '.jp-page'),
    'phan-quyen-01': ('/dashboard/permissions/', '.jp-page'),
    'phan-quyen-02': ('/dashboard/permissions/', '.jp-page'),
    'phan-quyen-03': ('/dashboard/permissions/', '.jp-page'),
    # Tài liệu trở xuống
    'tai-lieu-01': ('/tai-lieu/', '.jp-page'),
    'tai-lieu-02': ('/tai-lieu/', '.jp-page'),
    'tai-lieu-03': ('/tai-lieu/', '.jp-page'),
    'tai-lieu-04': ('/tai-lieu/hoi-dap/', '.jp-page'),
    'tai-lieu-05': ('/tai-lieu/hoi-dap/', '.jp-page'),
    'tai-lieu-06': ('/tai-lieu/', '.jp-page'),
    'tai-lieu-07': ('/tai-lieu/admin/documents/', '.jp-page'),
    'tai-lieu-08': ('/tai-lieu/admin/documents/add/', '.jp-page'),
    'tai-lieu-09': ('/dashboard/permissions/', '.jp-page'),
    'tai-lieu-10': ('/nhat-ky/tro-ly-ai/', '.jp-page'),
    'cong-viec-01': ('/cong-viec/ca-nhan/cua-toi/', '.jp-page'),
    'cong-viec-02': ('/cong-viec/ca-nhan/cua-toi/', '.jp-page'),
    'cong-viec-03': ('/cong-viec/ca-nhan/cua-toi/', '.jp-page'),
    'cong-viec-04': ('/cong-viec/du-an/', '.jp-page'),
    'cong-viec-05': ('/cong-viec/du-an/', '.jp-page'),
    'cong-viec-06': ('/cong-viec/lien-phong-ban/', '.jp-page'),
    'cong-viec-07': ('/cong-viec/du-an/tao/', '.jp-page'),
    'cong-viec-08': ('/cong-viec/du-an/', '.jp-page'),
    'cong-viec-09': ('/cong-viec/ca-nhan/giao/', '.jp-page'),
    'cong-viec-10': ('/cong-viec/du-an/', '.jp-page'),
    'de-xuat-01': ('/yeu-cau/de-xuat/cua-toi/', '.jp-page'),
    'de-xuat-02': ('/yeu-cau/de-xuat/tao/', '.jp-page'),
    'de-xuat-03': ('/yeu-cau/de-xuat/tao/', '.jp-page'),
    'de-xuat-04': ('/yeu-cau/de-xuat/cua-toi/', '.jp-page'),
    'de-xuat-05': ('/yeu-cau/de-xuat/cua-toi/', '.jp-page'),
    'de-xuat-06': ('/yeu-cau/de-xuat/cua-toi/', '.jp-page'),
    'de-xuat-07': ('/yeu-cau/de-xuat/danh-muc-dinh-ky/', '.jp-page'),
    'de-xuat-08': ('/yeu-cau/de-xuat/cho-xu-ly/', '.jp-page'),
    'de-xuat-09': ('/yeu-cau/de-xuat/cho-xu-ly/', '.jp-page'),
    'de-xuat-10': ('/yeu-cau/de-xuat/cho-xu-ly/', '.jp-page'),
    'de-xuat-11': ('/yeu-cau/de-xuat/danh-muc-dinh-ky/', '.jp-page'),
    'ho-tro-01': ('/yeu-cau/ho-tro/tao/', '.jp-page'),
    'ho-tro-02': ('/yeu-cau/ho-tro/tao/', '.jp-page'),
    'ho-tro-03': ('/yeu-cau/ho-tro/tao/', '.jp-page'),
    'ho-tro-04': ('/yeu-cau/ho-tro/tao/', '.jp-page'),
    'ho-tro-05': ('/yeu-cau/ho-tro/cua-toi/', '.jp-page'),
    'ho-tro-06': ('/yeu-cau/ho-tro/cua-toi/', '.jp-page'),
    'ho-tro-07': ('/yeu-cau/ho-tro/cho-xu-ly/', '.jp-page'),
    'ho-tro-08': ('/yeu-cau/ho-tro/cho-xu-ly/', '.jp-page'),
    'ho-tro-09': ('/yeu-cau/ho-tro/cho-xu-ly/', '.jp-page'),
    'ho-tro-10': ('/thiet-bi/it/', '.jp-page'),
    'thiet-bi-01': ('/thiet-bi/it/', '.jp-page'),
    'thiet-bi-02': ('/thiet-bi/it/', '.jp-page'),
    'thiet-bi-03': ('/thiet-bi/it/', '.jp-page'),
    'thiet-bi-04': ('/thiet-bi/it/', '.jp-page'),
    'thiet-bi-05': ('/yeu-cau/ho-tro/tao/', '.jp-page'),
    'thiet-bi-06': ('/thiet-bi/san-xuat/', '.jp-page'),
    'thiet-bi-07': ('/thiet-bi/it/', '.jp-page'),
    'thiet-bi-08': ('/thiet-bi/it/', '.jp-page'),
    'thiet-bi-09': ('/thiet-bi/it/', '.jp-page'),
    'thiet-bi-10': ('/thiet-bi/san-xuat/', '.jp-page'),
    'gop-y-01': ('/gop-y/tao/', '.jp-page'),
    'gop-y-02': ('/gop-y/tao/', '.jp-page'),
    'gop-y-03': ('/gop-y/tao/', '.jp-page'),
    'gop-y-04': ('/gop-y/tao/', '.jp-page'),
    'gop-y-05': ('/gop-y/danh-sach/', '.jp-page'),
    'gop-y-06': ('/gop-y/danh-sach/', '.jp-page'),
    'gop-y-07': ('/gop-y/danh-sach/', '.jp-page'),
    'gop-y-08': ('/gop-y/danh-sach/', '.jp-page'),
    'kho-npl-01': ('/kho-npl/tong-quan/', '.jp-page'),
    'kho-npl-02': ('/kho-npl/danh-muc/', '.jp-page'),
    'kho-npl-03': ('/kho-npl/ton-kho-npl/', '.jp-page'),
    'kho-npl-04': ('/kho-npl/phieu-nhap/', '.jp-page'),
    'kho-npl-05': ('/kho-npl/phieu-xuat/', '.jp-page'),
    'kho-npl-06': ('/kho-npl/chuyen-kho/', '.jp-page'),
    'kho-npl-07': ('/kho-npl/kiem-ke/', '.jp-page'),
    'kho-npl-08': ('/kho-npl/thiet-lap/', '.jp-page'),
    'kho-npl-09': ('/kho-npl/phieu-huy/', '.jp-page'),
    'kho-npl-10': ('/kho-npl/kiem-ke/', '.jp-page'),
    'kho-npl-11': ('/kho-npl/bao-cao/', '.jp-page'),
    'kiotviet-01': ('/kiotviet/khach-hang/', '.jp-page'),
    'kiotviet-02': ('/kiotviet/khach-hang/', '.jp-page'),
    'kiotviet-03': ('/kiotviet/khach-hang/', '.jp-page'),
    'kiotviet-04': ('/kiotviet/don-dat-hang/', '.jp-page'),
    'kiotviet-05': ('/kiotviet/hang-hoa/', '.jp-page'),
    'kiotviet-06': ('/kiotviet/ton-kho/', '.jp-page'),
    'kiotviet-07': ('/nhat-ky/kiotviet-sync/', '.jp-page'),
    'kiotviet-08': ('/nhat-ky/kiotviet-sync/', '.jp-page'),
    'nas-01': ('/thu-muc-nas/', '.jp-page'),
    'nas-02': ('/thu-muc-nas/', '.jp-page'),
    'nas-03': ('/thu-muc-nas/', '.jp-page'),
    'nas-04': ('/thu-muc-nas/', '.jp-page'),
    'nas-05': ('/thu-muc-nas/', '.jp-page'),
    'nas-06': ('/thu-muc-nas/', '.jp-page'),
    'nas-07': ('/nhat-ky/nas-links/', '.jp-page'),
    'nas-08': ('/nhat-ky/nas-links/', '.jp-page'),
    'tuyen-dung-01': ('/hr/admin/recruitment/kanban/', '.kanban-wrapper, .jp-page'),
    'tuyen-dung-02': ('/hr/admin/recruitment/kanban/', '.kanban-wrapper, .jp-page'),
    'tuyen-dung-03': ('/hr/admin/recruitment/jobs/', '.jp-page'),
    'tuyen-dung-04': ('/hr/admin/recruitment/kanban/', '.jp-page'),
    'tuyen-dung-05': ('/hr/admin/recruitment/kanban/', '.jp-page'),
    'tuyen-dung-06': ('/dashboard/users/', '.jp-page'),
    'quan-tri-01': ('/dashboard/users/', '.jp-page'),
    'quan-tri-02': ('/dashboard/users/', '.jp-page'),
    'quan-tri-03': ('/dashboard/users/', '.jp-page'),
    'quan-tri-04': ('/dashboard/users/', '.jp-page'),
    'quan-tri-05': ('/dashboard/users/', '.jp-page'),
    'quan-tri-06': ('/dashboard/users/', '.jp-page'),
    'quan-tri-07': ('/dashboard/users/', '.jp-page'),
    'quan-tri-he-thong-01': ('/nhat-ky/', '.jp-page'),
    'quan-tri-he-thong-02': ('/nhat-ky/bao-mat-dang-nhap/', '.jp-page'),
    'quan-tri-he-thong-03': ('/nhat-ky/backup/', '.jp-page'),
    'quan-tri-he-thong-04': ('/nhat-ky/kiotviet-sync/', '.jp-page'),
    'quan-tri-he-thong-05': ('/nhat-ky/nas-links/', '.jp-page'),
    'quan-tri-he-thong-06': ('/nhat-ky/tro-ly-ai/', '.jp-page'),
    # FAQ
    'faq-01': ('/accounts/login/', '.card-login'),
    'faq-02': ('/', '.portal-container'),
    'faq-03': ('/reports/today/', '.jp-page'),
    'faq-04': ('/kpi/', '.jp-page'),
    'faq-05': ('/training/my-courses/', '.jp-page'),
    'faq-06': ('/exams/', '.jp-page'),
    'faq-07': ('/exams/', '.jp-page'),
    'faq-08': ('/accounts/login/', '.card-login'),
}

# section_id -> ảnh mặc định khi bước chưa có trong STEP_SCREENSHOTS
SECTION_FALLBACK: dict[str, str] = {
    'bat-dau': '02-trang-chu.png',
    'dang-nhap': '01-dang-nhap.png',
    'doi-mat-khau': '04-doi-mat-khau.png',
    'gioi-thieu': '02-trang-chu.png',
    'chuan-bi': '01-dang-nhap.png',
    'thong-bao': '05-thong-bao.png',
    'bao-cao': '06-bao-cao.png',
    'dao-tao': '07-dao-tao.png',
    'kiem-tra': '08-kiem-tra.png',
    'kpi': '09-kpi.png',
    'phan-quyen': '11-phan-quyen.png',
    'tai-lieu': '12-tai-lieu.png',
    'cong-viec': '13-cong-viec.png',
    'de-xuat': '14-de-xuat.png',
    'ho-tro': '15-ho-tro.png',
    'thiet-bi': '16-thiet-bi.png',
    'gop-y': '17-gop-y.png',
    'kho-npl': '18-kho-npl.png',
    'kiotviet': '19-kiotviet.png',
    'nas': '20-nas.png',
    'tuyen-dung': '21-tuyen-dung.png',
    'quan-tri': '10-nhan-su.png',
    'quan-tri-he-thong': '22-audit.png',
    'faq': '23-huong-dan.png',
}
