# Generated by Django 5.2.7 on 2026-05-28 02:34

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='Tóm tắt')),
                ('content_type', models.CharField(choices=[('TEXT', 'Văn bản'), ('PDF', 'PDF'), ('VIDEO', 'Video')], default='TEXT', max_length=10, verbose_name='Loại nội dung')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='Nội dung văn bản')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='announcements/pdf/', verbose_name='File PDF')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='announcements/videos/', verbose_name='File video')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Ghim lên đầu')),
                ('require_acknowledgment', models.BooleanField(default=True, verbose_name='Yêu cầu xác nhận đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xác nhận đọc',
                'verbose_name_plural': 'Xác nhận đọc',
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
