# Generated by Django 5.2.7 on 2026-06-18 04:53

import announcements.nas_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='original_file',
            field=models.FileField(blank=True, null=True, storage=announcements.nas_storage.AnnouncementNasStorage(), upload_to=announcements.nas_storage.announcement_file_upload_to, verbose_name='File gốc đính kèm'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=announcements.nas_storage.AnnouncementNasStorage(), upload_to=announcements.nas_storage.announcement_file_upload_to, verbose_name='File PDF'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=announcements.nas_storage.AnnouncementNasStorage(), upload_to=announcements.nas_storage.announcement_file_upload_to, verbose_name='File video'),
        ),
    ]
