# Generated by Django 5.2.7 on 2026-07-28 01:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('thanh_pham', 'Thành phẩm'), ('hang_hoa', 'Hàng hoá')], db_index=True, default='hang_hoa', max_length=20, verbose_name='Loại')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Mã sản phẩm')),
                ('accounting_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Mã kế toán')),
                ('kiotviet_code', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Mã KiotViet')),
                ('kiotviet_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID KiotViet')),
                ('name', models.CharField(max_length=500, verbose_name='Tên sản phẩm')),
                ('full_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Tên đầy đủ')),
                ('bar_code', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Mã vạch')),
                ('unit', models.CharField(blank=True, default='', max_length=32, verbose_name='Đơn vị tính')),
                ('category_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nhóm hàng')),
                ('category_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Đường dẫn nhóm')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Giá bán')),
                ('image', models.ImageField(blank=True, upload_to='kho_sp/products/', verbose_name='Hình ảnh')),
                ('image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL ảnh KV')),
                ('allows_sale', models.BooleanField(blank=True, null=True, verbose_name='Cho phép bán')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang dùng')),
                ('sync_source', models.CharField(choices=[('manual', 'Nhập tay'), ('kiotviet', 'KiotViet')], default='manual', max_length=20, verbose_name='Nguồn')),
                ('kv_modified_at', models.DateTimeField(blank=True, null=True, verbose_name='KV sửa lúc')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Đồng bộ lúc')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kho_sp_products_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'kho_sp_product',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['product_type', 'is_active'], name='kho_sp_prod_product_fffaf6_idx'), models.Index(fields=['kiotviet_code'], name='kho_sp_prod_kiotvie_f2d0cd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accounting_code', ''), _negated=True), fields=('accounting_code',), name='kho_sp_product_accounting_code_uniq')],
            },
        ),
    ]
