# Generated by Django 5.2.7 on 2026-07-28 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_san_pham', '0001_initial'),
        ('san_xuat', '0036_link_time_studies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['style_code', 'color_code', 'size_label', 'code'], 'verbose_name': 'Sản phẩm (SKU)', 'verbose_name_plural': 'Sản phẩm (SKU)'},
        ),
        migrations.AddField(
            model_name='product',
            name='color_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Mã màu'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_label',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Tên màu'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_label',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='style_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Mã Style = mã SP hồ sơ thiết kế (vd. JP-TEE-260001).', max_length=60, verbose_name='Style'),
        ),
        migrations.AddField(
            model_name='product',
            name='sx_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kho_sp_products', to='san_xuat.sxsku', verbose_name='SKU SX'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='SKU = Style-Màu-Size (vd. JP-TEE-260001-NVY-M).', max_length=100, unique=True, verbose_name='SKU'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['style_code', 'is_active'], name='kho_sp_prod_style_c_e964d8_idx'),
        ),
    ]
