# Generated by Django 5.2.7 on 2026-07-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kho_san_pham', '0003_catalog_type_style_kv_map'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productstyle',
            new_name='kho_sp_prod_product_23f5c2_idx',
            old_name='kho_sp_prod_product_5b0f0a_idx',
        ),
        migrations.RenameIndex(
            model_name='productstyle',
            new_name='kho_sp_prod_source_8a4e37_idx',
            old_name='kho_sp_prod_source_8d2c1a_idx',
        ),
    ]
