# Generated by Django 5.2.7 on 2026-07-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kho_san_pham', '0005_product_accounting_code_shared'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='kho_sp_prod_account_b08923_idx',
            old_name='kho_sp_prod_account_0a1b2c_idx',
        ),
    ]
