# Generated by Django 5.2.7 on 2026-07-28 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_san_pham', '0006_rename_accounting_code_index'),
        ('san_xuat', '0036_link_time_studies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('bar_code', ''), _negated=True), fields=('bar_code',), name='kho_sp_product_bar_code_uniq'),
        ),
    ]
