# Generated by Django 5.2.7 on 2026-08-20 05:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_san_pham', '0008_product_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã kho')),
                ('name', models.CharField(max_length=120, verbose_name='Tên kho')),
                ('owner_system', models.CharField(choices=[('portal', 'Portal (xưởng)'), ('sales', 'Bán hàng')], db_index=True, default='portal', help_text='Hệ nào được ghi phát sinh vào kho này.', max_length=20, verbose_name='Hệ sở hữu')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang dùng')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kho thành phẩm',
                'verbose_name_plural': 'Kho thành phẩm',
                'db_table': 'kho_sp_warehouse',
                'ordering': ['owner_system', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('production_in', 'Nhập thành phẩm'), ('sale_out', 'Xuất bán'), ('sale_return_in', 'Khách trả'), ('transfer_out', 'Chuyển đi'), ('transfer_in', 'Chuyển đến'), ('adjust', 'Điều chỉnh / kiểm kê'), ('disposal_out', 'Xuất hủy')], db_index=True, max_length=24, verbose_name='Loại phát sinh')),
                ('qty_delta', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Biến động')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tồn sau')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Bắt buộc với nhập thành phẩm. Phát sinh xuất để trống — giá vốn tính từ tồn.', max_digits=14, null=True, verbose_name='Giá thành')),
                ('source_system', models.CharField(choices=[('portal', 'Portal'), ('sales', 'Bán hàng')], db_index=True, max_length=20, verbose_name='Hệ nguồn')),
                ('source_doc_type', models.CharField(choices=[('fg_receipt', 'Yêu cầu nhập thành phẩm'), ('invoice', 'Hóa đơn bán'), ('sale_return', 'Phiếu trả hàng'), ('transfer', 'Phiếu chuyển kho'), ('stocktake', 'Phiếu kiểm kê'), ('disposal', 'Phiếu hủy')], max_length=30, verbose_name='Loại chứng từ')),
                ('source_doc_code', models.CharField(db_index=True, max_length=60, verbose_name='Số chứng từ')),
                ('source_line_no', models.PositiveIntegerField(default=1, verbose_name='Dòng')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Thời điểm phát sinh')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm ghi sổ')),
                ('actor', models.CharField(blank=True, default='', max_length=150, verbose_name='Người thực hiện (hệ nguồn)')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kho_sp_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='kho_san_pham.product', verbose_name='SKU')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='kho_san_pham.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Sổ kho thành phẩm',
                'verbose_name_plural': 'Sổ kho thành phẩm',
                'db_table': 'kho_sp_stock_ledger',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Tồn')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='kho_san_pham.product', verbose_name='SKU')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='kho_san_pham.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Tồn thành phẩm',
                'verbose_name_plural': 'Tồn thành phẩm',
                'db_table': 'kho_sp_stock_balance',
                'ordering': ['warehouse', 'product'],
            },
        ),
        migrations.CreateModel(
            name='NegativeStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('warehouse_code', models.CharField(db_index=True, max_length=40, verbose_name='Kho')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tồn sau')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Đã xử lý lúc')),
                ('resolution_note', models.CharField(blank=True, default='', max_length=255, verbose_name='Cách xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kho_sp_negative_alerts_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negative_alert', to='kho_san_pham.stockledger', verbose_name='Dòng sổ kho')),
            ],
            options={
                'verbose_name': 'Cảnh báo tồn âm',
                'verbose_name_plural': 'Cảnh báo tồn âm',
                'db_table': 'kho_sp_negative_stock_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved_at'], name='kho_sp_nega_resolve_c324d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['product', 'warehouse', 'occurred_at'], name='kho_sp_stoc_product_383787_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.UniqueConstraint(fields=('source_system', 'source_doc_type', 'source_doc_code', 'source_line_no'), name='kho_sp_ledger_source_uniq'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['warehouse', 'qty_on_hand'], name='kho_sp_stoc_warehou_c7c2ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='kho_sp_balance_product_wh_uniq'),
        ),
    ]
