# Generated by Django 5.2.7 on 2026-08-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_san_pham', '0009_warehouse_stockledger_stockbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legacy_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Mã trước khi sinh lại theo từ vựng chuẩn. Để tra cứu ngược, không dùng làm khóa.', max_length=100, verbose_name='Mã SKU cũ'),
        ),
    ]
