# Generated by Django 5.2.7 on 2026-08-20 06:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_san_pham', '0010_product_legacy_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_on_hand',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Bản sao tồn kho xưởng (XUONG-TP). Nguồn sự thật là sổ kho; cột này chỉ để xem trên danh mục.', max_digits=14, verbose_name='Tồn kho'),
        ),
    ]
