# Generated by Django 5.2.7 on 2026-08-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_san_pham', '0014_stock_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='source_doc_type',
            field=models.CharField(choices=[('fg_receipt', 'Yêu cầu nhập thành phẩm'), ('stock_receipt', 'Phiếu nhập kho thành phẩm'), ('invoice', 'Hóa đơn bán'), ('sale_return', 'Phiếu trả hàng'), ('transfer', 'Phiếu chuyển kho'), ('stocktake', 'Phiếu kiểm kê'), ('kv_onhand', 'Tồn KiotViet (cửa hàng)'), ('disposal', 'Phiếu hủy')], max_length=30, verbose_name='Loại chứng từ'),
        ),
    ]
