# Generated by Django 5.2.7 on 2026-04-28 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='VD: Đánh giá KPI Quý 1/2026', max_length=255, verbose_name='Tên kỳ đánh giá')),
                ('year', models.IntegerField(default=2026, verbose_name='Năm')),
                ('period_type', models.CharField(choices=[('Q1', 'Quý 1'), ('Q2', 'Quý 2'), ('Q3', 'Quý 3'), ('Q4', 'Quý 4'), ('H1', 'Sáu tháng đầu năm (H1)'), ('H2', 'Sáu tháng cuối năm (H2)'), ('Y', 'Cả năm')], max_length=2, verbose_name='Loại kỳ')),
                ('start_date', models.DateTimeField(verbose_name='Ngày mở đánh giá')),
                ('end_date', models.DateTimeField(verbose_name='Ngày đóng đánh giá')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kích hoạt')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Đang thiết lập mục tiêu'), ('self_evaluating', 'Nhân viên đang đánh giá'), ('manager_evaluating', 'Quản lý đang đánh giá'), ('general_evaluating', 'Quản lý chung đang chốt'), ('completed', 'Đã hoàn tất')], default='draft', max_length=20)),
                ('total_final_score', models.FloatField(default=0, verbose_name='Tổng điểm cuối cùng (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_kpis', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_kpis', to=settings.AUTH_USER_MODEL)),
                ('general_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_kpis', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_kpis', to='kpi.kpiperiod')),
            ],
            options={
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='KpiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('PEOPLE', 'Quản trị nguồn nhân lực (People Management)'), ('FINANCE', 'Kết quả Tài chính (Financial Result)'), ('CUSTOMER', 'Khách hàng/Bệnh nhân (Customer/Patient)'), ('OPERATION', 'Vận hành - Công nghệ (Operation - Technology)')], max_length=20, verbose_name='Lĩnh vực (Pillar)')),
                ('personal_objective', models.TextField(verbose_name='Mục tiêu cá nhân')),
                ('kpi_indicator', models.TextField(verbose_name='Chỉ số đo lường (KPIs)')),
                ('weightage', models.FloatField(help_text='VD: 5, 10, 15', verbose_name='Trọng số (%)')),
                ('target', models.FloatField(verbose_name='Chỉ tiêu chuẩn (Target)')),
                ('unit', models.CharField(help_text='VD: %, #, VNĐ', max_length=20, verbose_name='Đơn vị (Unit)')),
                ('trend', models.CharField(choices=[('HIGHER', 'Cao hơn (Higher)'), ('LOWER', 'Thấp hơn (Lower)'), ('EXACT', 'Chính xác (Exact)')], max_length=10, verbose_name='Xu hướng (Trend)')),
                ('self_actual_result', models.FloatField(blank=True, null=True, verbose_name='NV: Kết quả thực tế')),
                ('self_score', models.FloatField(blank=True, null=True, verbose_name='NV: Tự chấm điểm (%)')),
                ('self_note', models.TextField(blank=True, verbose_name='NV: Ghi chú giải trình')),
                ('manager_score', models.FloatField(blank=True, null=True, verbose_name='QLTT: Chấm điểm (%)')),
                ('manager_note', models.TextField(blank=True, verbose_name='QLTT: Nhận xét')),
                ('general_score', models.FloatField(blank=True, null=True, verbose_name='QLC: Điểm chốt cuối (%)')),
                ('general_note', models.TextField(blank=True, verbose_name='QLC: Nhận xét cuối')),
                ('kpi_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kpi.employeekpi')),
            ],
        ),
    ]
