# Generated by Django 5.2.7 on 2026-04-28 03:27

import django.db.models.deletion
import django.utils.timezone
import kpi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeekpi',
            name='direct_manager',
        ),
        migrations.RemoveField(
            model_name='employeekpi',
            name='general_manager',
        ),
        migrations.RemoveField(
            model_name='employeekpi',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='kpiitem',
            name='target',
        ),
        migrations.AddField(
            model_name='kpiitem',
            name='period_target',
            field=models.FloatField(default=0.0, verbose_name='Chỉ tiêu theo Kỳ'),
        ),
        migrations.AlterField(
            model_name='employeekpi',
            name='status',
            field=models.CharField(choices=[('self_evaluating', 'Nhân viên đang đánh giá'), ('manager_evaluating', 'Quản lý trực tiếp đang đánh giá'), ('general_evaluating', 'Quản lý chung đang chốt'), ('completed', 'Đã hoàn tất')], default='self_evaluating', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='general_note',
            field=models.TextField(blank=True, default='', verbose_name='QLC: Nhận xét'),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='general_score',
            field=models.FloatField(blank=True, null=True, verbose_name='QLC: Điểm chốt (%)'),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='kpi_indicator',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='manager_note',
            field=models.TextField(blank=True, default='', verbose_name='QLTT: Nhận xét'),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='manager_score',
            field=models.FloatField(blank=True, null=True, verbose_name='QLTT: Điểm (%)'),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='personal_objective',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='pillar',
            field=models.CharField(default='OPERATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='self_note',
            field=models.TextField(blank=True, default='', verbose_name='NV: Giải trình'),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='trend',
            field=models.CharField(default='HIGHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='unit',
            field=models.CharField(default='%', max_length=20),
        ),
        migrations.AlterField(
            model_name='kpiitem',
            name='weightage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đóng đánh giá'),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='period_type',
            field=models.CharField(choices=[('Q1', 'Quý 1'), ('Q2', 'Quý 2'), ('Q3', 'Quý 3'), ('Q4', 'Quý 4'), ('H1', 'Sáu tháng đầu năm (H1)'), ('H2', 'Sáu tháng cuối năm (H2)'), ('Y', 'Cả năm')], default='Q1', max_length=2, verbose_name='Loại kỳ'),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày mở đánh giá'),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên kỳ đánh giá'),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='year',
            field=models.IntegerField(default=kpi.models.current_year, verbose_name='Năm'),
        ),
        migrations.CreateModel(
            name='YearlyKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=kpi.models.current_year, verbose_name='Năm giao KPI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_yearly_kpis', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_kpis', to=settings.AUTH_USER_MODEL)),
                ('general_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_yearly_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.AddField(
            model_name='employeekpi',
            name='yearly_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi.yearlykpi', verbose_name='Tham chiếu Bảng Mẹ'),
        ),
        migrations.CreateModel(
            name='YearlyKpiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('PEOPLE', 'Quản trị nguồn nhân lực'), ('FINANCE', 'Kết quả Tài chính'), ('CUSTOMER', 'Khách hàng/Bệnh nhân'), ('OPERATION', 'Vận hành - Công nghệ')], default='OPERATION', max_length=20, verbose_name='Lĩnh vực')),
                ('personal_objective', models.TextField(default='', verbose_name='Mục tiêu cá nhân')),
                ('kpi_indicator', models.TextField(default='', verbose_name='Chỉ số đo lường (KPIs)')),
                ('weightage', models.FloatField(default=0.0, verbose_name='Trọng số (%)')),
                ('yearly_target', models.FloatField(default=0.0, verbose_name='Chỉ tiêu 1 NĂM (Target)')),
                ('unit', models.CharField(default='%', max_length=20, verbose_name='Đơn vị')),
                ('trend', models.CharField(choices=[('HIGHER', 'Cao hơn'), ('LOWER', 'Thấp hơn'), ('EXACT', 'Chính xác')], default='HIGHER', max_length=10, verbose_name='Xu hướng')),
                ('yearly_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kpi.yearlykpi')),
            ],
        ),
    ]
