# Generated by Django 5.2.7 on 2026-04-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_remove_employeekpi_direct_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiitem',
            name='kpi_board',
        ),
        migrations.RemoveField(
            model_name='kpiperiod',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='kpiperiod',
            name='start_date',
        ),
        migrations.AddField(
            model_name='yearlykpi',
            name='eval_type',
            field=models.CharField(choices=[('QUARTER', 'Đánh giá theo Quý (4 cột)'), ('HALF', 'Đánh giá theo Kỳ (2 cột)')], default='QUARTER', max_length=10, verbose_name='Chế độ hiển thị'),
        ),
        migrations.AddField(
            model_name='yearlykpi',
            name='h1_status',
            field=models.CharField(default='self_evaluating', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlykpi',
            name='h2_status',
            field=models.CharField(default='self_evaluating', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlykpi',
            name='q1_status',
            field=models.CharField(default='self_evaluating', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlykpi',
            name='q2_status',
            field=models.CharField(default='self_evaluating', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlykpi',
            name='q3_status',
            field=models.CharField(default='self_evaluating', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlykpi',
            name='q4_status',
            field=models.CharField(default='self_evaluating', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='h1_gm',
            field=models.FloatField(blank=True, null=True, verbose_name='GM H1'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='h1_mgr',
            field=models.FloatField(blank=True, null=True, verbose_name='HOD H1'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='h1_self',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm NV H1'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='h2_gm',
            field=models.FloatField(blank=True, null=True, verbose_name='GM H2'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='h2_mgr',
            field=models.FloatField(blank=True, null=True, verbose_name='HOD H2'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='h2_self',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm NV H2'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q1_gm',
            field=models.FloatField(blank=True, null=True, verbose_name='GM Q1'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q1_mgr',
            field=models.FloatField(blank=True, null=True, verbose_name='HOD Q1'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q1_self',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm NV Q1'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q2_gm',
            field=models.FloatField(blank=True, null=True, verbose_name='GM Q2'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q2_mgr',
            field=models.FloatField(blank=True, null=True, verbose_name='HOD Q2'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q2_self',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm NV Q2'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q3_gm',
            field=models.FloatField(blank=True, null=True, verbose_name='GM Q3'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q3_mgr',
            field=models.FloatField(blank=True, null=True, verbose_name='HOD Q3'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q3_self',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm NV Q3'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q4_gm',
            field=models.FloatField(blank=True, null=True, verbose_name='GM Q4'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q4_mgr',
            field=models.FloatField(blank=True, null=True, verbose_name='HOD Q4'),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='q4_self',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm NV Q4'),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Admin cho phép chấm điểm'),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='period_type',
            field=models.CharField(choices=[('Q1', 'Quý 1'), ('Q2', 'Quý 2'), ('Q3', 'Quý 3'), ('Q4', 'Quý 4'), ('H1', 'Sáu tháng đầu năm (H1)'), ('H2', 'Sáu tháng cuối năm (H2)'), ('Y', 'Cả năm (Y)')], max_length=2, verbose_name='Loại kỳ'),
        ),
        migrations.AlterField(
            model_name='kpiperiod',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên kỳ'),
        ),
        migrations.AlterField(
            model_name='yearlykpiitem',
            name='kpi_indicator',
            field=models.TextField(verbose_name='Chỉ số đo lường'),
        ),
        migrations.AlterField(
            model_name='yearlykpiitem',
            name='personal_objective',
            field=models.TextField(verbose_name='Mục tiêu cá nhân'),
        ),
        migrations.AlterField(
            model_name='yearlykpiitem',
            name='pillar',
            field=models.CharField(choices=[('PEOPLE', 'Quản trị nguồn nhân lực'), ('FINANCE', 'Kết quả Tài chính'), ('CUSTOMER', 'Khách hàng/Bệnh nhân'), ('OPERATION', 'Vận hành - Công nghệ')], default='OPERATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearlykpiitem',
            name='trend',
            field=models.CharField(default='HIGHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='yearlykpiitem',
            name='unit',
            field=models.CharField(default='%', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearlykpiitem',
            name='yearly_target',
            field=models.FloatField(default=0.0, verbose_name='Chỉ tiêu năm'),
        ),
        migrations.DeleteModel(
            name='EmployeeKpi',
        ),
        migrations.DeleteModel(
            name='KpiItem',
        ),
    ]
