# Generated by Django 5.2.7 on 2026-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_remove_kpiitem_kpi_board_remove_kpiperiod_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlykpi',
            name='y_status',
            field=models.CharField(default='self_evaluating', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='y_gm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='y_mgr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlykpiitem',
            name='y_self',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearlykpi',
            name='eval_type',
            field=models.CharField(choices=[('QUARTER', 'Đánh giá theo Quý (4 cột)'), ('HALF', 'Đánh giá theo Kỳ (2 cột)'), ('YEAR', 'Đánh giá Cả năm (1 cột)')], default='QUARTER', max_length=10, verbose_name='Chế độ hiển thị'),
        ),
    ]
