# Generated by Django 5.2.7 on 2026-04-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_yearlykpi_y_status_yearlykpiitem_y_gm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlykpi',
            name='h1_status',
            field=models.CharField(choices=[('self_evaluating', 'Đang làm'), ('manager_evaluating', 'HOD Đang chấm'), ('general_evaluating', 'GM Đang chấm'), ('completed', 'Hoàn tất')], default='self_evaluating', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearlykpi',
            name='h2_status',
            field=models.CharField(choices=[('self_evaluating', 'Đang làm'), ('manager_evaluating', 'HOD Đang chấm'), ('general_evaluating', 'GM Đang chấm'), ('completed', 'Hoàn tất')], default='self_evaluating', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearlykpi',
            name='q1_status',
            field=models.CharField(choices=[('self_evaluating', 'Đang làm'), ('manager_evaluating', 'HOD Đang chấm'), ('general_evaluating', 'GM Đang chấm'), ('completed', 'Hoàn tất')], default='self_evaluating', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearlykpi',
            name='q2_status',
            field=models.CharField(choices=[('self_evaluating', 'Đang làm'), ('manager_evaluating', 'HOD Đang chấm'), ('general_evaluating', 'GM Đang chấm'), ('completed', 'Hoàn tất')], default='self_evaluating', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearlykpi',
            name='q3_status',
            field=models.CharField(choices=[('self_evaluating', 'Đang làm'), ('manager_evaluating', 'HOD Đang chấm'), ('general_evaluating', 'GM Đang chấm'), ('completed', 'Hoàn tất')], default='self_evaluating', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearlykpi',
            name='q4_status',
            field=models.CharField(choices=[('self_evaluating', 'Đang làm'), ('manager_evaluating', 'HOD Đang chấm'), ('general_evaluating', 'GM Đang chấm'), ('completed', 'Hoàn tất')], default='self_evaluating', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearlykpi',
            name='y_status',
            field=models.CharField(choices=[('self_evaluating', 'Đang làm'), ('manager_evaluating', 'HOD Đang chấm'), ('general_evaluating', 'GM Đang chấm'), ('completed', 'Hoàn tất')], default='self_evaluating', max_length=20),
        ),
    ]
