"""Patch SX list grid column defaults and definitions."""
from pathlib import Path

path = Path(__file__).resolve().parents[1] / "san_xuat" / "list_grid.py"
text = path.read_text(encoding="utf-8")

replacements = [
    (
        """    'dispatch_mo': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('product', 'Sản phẩm', weight=140),
            _col('qty', 'Số lượng', weight=80, align='end'),
            _col('order_date', 'Ngày', weight=90),
            _col('due_date', 'Hạn', weight=90),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'product': 'product_code',
            'qty': 'qty',
            'order_date': 'order_date',
            'due_date': 'due_date',
            'status': 'status',
            'created_by': 'created_by__username',
            'created_at': 'created_at',
        },
        default_sort='order_date',
    ),""",
        """    'dispatch_mo': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('product', 'Sản phẩm', weight=140),
            _col('qty', 'Số lượng', weight=80, align='end'),
            _col('qty_done', 'Đã đạt', weight=80, align='end'),
            _col('team_label', 'Tổ / công đoạn', weight=110, default=False),
            _col('order_date', 'Ngày lập', weight=90),
            _col('due_date', 'Hạn', weight=90),
            _col('planned_start', 'KH bắt đầu', weight=95, default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'product': 'product_code',
            'qty': 'qty',
            'qty_done': 'qty_done',
            'team_label': 'team_label',
            'order_date': 'order_date',
            'due_date': 'due_date',
            'planned_start': 'planned_start',
            'status': 'status',
            'created_by': 'created_by__username',
            'created_at': 'created_at',
        },
        default_sort='order_date',
    ),""",
    ),
    (
        "'mo': 'source_mo__code',",
        "'mo': 'production_order__code',",
    ),
    (
        """            _col('issue_doc', 'Phiếu xuất', weight=110),
            actions=False,
        ),
        {
            'code': 'code',
            'mo': 'production_order__code',
            'request_date': 'request_date',
            'status': 'status',
            'issue_doc': 'npl_issue_doc_code',""",
        """            _col('issue_doc', 'Phiếu xuất', weight=110, default=False),
            actions=False,
        ),
        {
            'code': 'code',
            'mo': 'production_order__code',
            'request_date': 'request_date',
            'status': 'status',
            'issue_doc': 'npl_issue_doc_code',""",
    ),
    (
        """            _col('qty_defect', 'Lỗi', weight=70, align='end'),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'mo': 'production_order__code',
            'stat_date': 'stat_date',""",
        """            _col('qty_defect', 'Lỗi', weight=70, align='end', default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'mo': 'production_order__code',
            'stat_date': 'stat_date',""",
    ),
    (
        """            _col('kv_doc', 'Phiếu KV', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'mo': 'production_order__code',
            'request_date': 'request_date',
            'qty': 'qty',
            'status': 'status',
            'kv_doc': 'kv_receipt_code',""",
        """            _col('kv_doc', 'Phiếu KV', weight=100, default=False),
            actions=False,
        ),
        {
            'code': 'code',
            'mo': 'production_order__code',
            'request_date': 'request_date',
            'qty': 'qty',
            'status': 'status',
            'kv_doc': 'kv_receipt_code',""",
    ),
    (
        """            _col('stock_adj', 'ĐC kho', weight=90),
            actions=False,
        ),
        {
            'code': 'code',
            'material': 'material_code',
            'qty': 'qty',
            'source': 'production_order__code',""",
        """            _col('stock_adj', 'ĐC kho', weight=90, default=False),
            actions=False,
        ),
        {
            'code': 'code',
            'material': 'material_code',
            'qty': 'qty',
            'source': 'production_order__code',""",
    ),
    (
        """    'qc_request': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('mo', 'Lệnh sản xuất', weight=120),
            _col('product', 'Mã sản phẩm', weight=110),
            _col('process', 'Công đoạn', weight=110),
            _col('request_date', 'Ngày', weight=90),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'mo': 'production_order__code',
            'product': 'product_code',
            'process': 'stage_name',
            'request_date': 'request_date',
            'status': 'status',""",
        """    'qc_request': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('mo', 'Lệnh sản xuất', weight=120),
            _col('product', 'Mã sản phẩm', weight=110),
            _col('process', 'Công đoạn', weight=110, default=False),
            _col('qty', 'Số lượng', weight=80, align='end'),
            _col('request_date', 'Ngày YC', weight=90),
            _col('due_date', 'Hạn', weight=90, default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'mo': 'production_order__code',
            'product': 'product_code',
            'process': 'stage_name',
            'qty': 'qty',
            'request_date': 'request_date',
            'due_date': 'due_date',
            'status': 'status',""",
    ),
    (
        """    'qc_sheet': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('qc_request', 'Yêu cầu kiểm tra', weight=130),
            _col('inspected_at', 'Ngày kiểm', weight=100),
            _col('standard', 'Bộ tiêu chuẩn', weight=120),
            _col('qty_sample', 'Mẫu', weight=70, align='end'),
            _col('qty_pass', 'Đạt', weight=70, align='end'),
            _col('qty_fail', 'Lỗi', weight=70, align='end'),
            _col('result', 'Kết luận', weight=100),
            actions=False,
        ),""",
        """    'qc_sheet': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('qc_request', 'Yêu cầu kiểm tra', weight=130, default=False),
            _col('inspected_at', 'Ngày kiểm', weight=100),
            _col('standard', 'Bộ tiêu chuẩn', weight=120, default=False),
            _col('qty_sample', 'Mẫu', weight=70, align='end', default=False),
            _col('qty_pass', 'Đạt', weight=70, align='end'),
            _col('qty_fail', 'Lỗi', weight=70, align='end', default=False),
            _col('result', 'Kết luận', weight=100),
            actions=False,
        ),""",
    ),
    (
        """    'qc_alert': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('alert_type', 'Loại', weight=90),
            _col('mo', 'Lệnh sản xuất', weight=120),
            _col('process', 'Công đoạn', weight=110),
            _col('qty', 'Số lượng', weight=80, align='end'),
            _col('message', 'Nội dung', weight=150),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'alert_type': 'alert_type',
            'mo': 'production_order__code',
            'process': 'process_name',
            'qty': 'qty',
            'message': 'message',
            'status': 'status',""",
        """    'qc_alert': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('alert_type', 'Loại', weight=90, default=False),
            _col('mo', 'Lệnh sản xuất', weight=120),
            _col('process', 'Công đoạn', weight=110),
            _col('defect_rate', 'Tỷ lệ lỗi', weight=90, align='end'),
            _col('tolerance_limit', 'Ngưỡng', weight=80, align='end', default=False),
            _col('message', 'Nội dung', weight=150, default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'alert_type': 'alert_type',
            'mo': 'production_order__code',
            'process': 'process_name',
            'defect_rate': 'defect_rate',
            'tolerance_limit': 'tolerance_limit',
            'message': 'message',
            'status': 'status',""",
    ),
    (
        """            _col('work_task', 'WorkTask', weight=100),
            _col('due_date', 'Hạn', weight=90),""",
        """            _col('work_task', 'WorkTask', weight=100, default=False),
            _col('due_date', 'Hạn', weight=90),""",
    ),
    (
        """            _col('lot', 'Lô', weight=90),
            _col('pack_date', 'Ngày', weight=90),""",
        """            _col('lot', 'Lô', weight=90, default=False),
            _col('pack_date', 'Ngày', weight=90),""",
    ),
    (
        """            _col('source', 'Nguồn', weight=100),
            _col('line_count', 'Dòng SP', weight=80, align='end'),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'name': 'name',
            'date_from': 'date_from',
            'date_to': 'date_to',
            'source': 'source',
            'line_count': 'pk',""",
        """            _col('source', 'Nguồn', weight=100, default=False),
            _col('line_count', 'Dòng SP', weight=80, align='end', default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'name': 'name',
            'date_from': 'date_from',
            'date_to': 'date_to',
            'source': 'source',
            'line_count': 'pk',""",
    ),
    (
        """            _col('overall', 'Kế hoạch tổng thể nguồn', weight=140),
            _col('period', 'Kỳ', weight=120),
            _col('line_count', 'Dòng SP', weight=80, align='end'),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'name': 'name',
            'overall': 'overall_plan__code',
            'period': 'date_from',
            'line_count': 'pk',""",
        """            _col('overall', 'Kế hoạch tổng thể nguồn', weight=140, default=False),
            _col('period', 'Kỳ', weight=120),
            _col('line_count', 'Dòng SP', weight=80, align='end', default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'name': 'name',
            'overall': 'overall_plan__code',
            'period': 'date_from',
            'line_count': 'pk',""",
    ),
    (
        """            _col('overall', 'Kế hoạch tổng thể nguồn', weight=140),
            _col('line_count', 'Dòng NPL', weight=80, align='end'),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'name': 'name',
            'overall': 'overall_plan__code',
            'line_count': 'pk',""",
        """            _col('overall', 'Kế hoạch tổng thể nguồn', weight=140, default=False),
            _col('line_count', 'Dòng NPL', weight=80, align='end', default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'name': 'name',
            'overall': 'overall_plan__code',
            'line_count': 'pk',""",
    ),
    (
        """            _col('plan', 'Kế hoạch NPL', weight=130),
            _col('request_date', 'Ngày yêu cầu', weight=100),
            _col('due_date', 'Hạn', weight=90),
            _col('line_count', 'Dòng', weight=70, align='end'),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'plan': 'npl_plan__code',""",
        """            _col('plan', 'Kế hoạch NPL', weight=130, default=False),
            _col('request_date', 'Ngày yêu cầu', weight=100),
            _col('due_date', 'Hạn', weight=90),
            _col('line_count', 'Dòng', weight=70, align='end', default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'plan': 'npl_plan__code',""",
    ),
    (
        """    'purchase_order': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('supplier', 'NCC', weight=130),
            _col('pr', 'Yêu cầu mua NPL nguồn', weight=140),
            _col('total', 'Tổng tiền', weight=90, align='end'),
            _col('kv_receipt', 'Phiếu nhập KiotViet', weight=120),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'supplier': 'supplier_name',
            'pr': 'purchase_request__code',
            'total': 'total_amount',
            'kv_receipt': 'kv_receipt_code',""",
        """    'purchase_order': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('supplier', 'NCC', weight=130),
            _col('pr', 'Yêu cầu mua NPL', weight=140, default=False),
            _col('line_count', 'Số dòng', weight=80, align='end', default=False),
            _col('kv_receipt', 'Phiếu nhập KiotViet', weight=120, default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'supplier': 'supplier_name',
            'pr': 'purchase_request__code',
            'line_count': 'pk',
            'kv_receipt': 'kv_purchase_code',""",
    ),
    (
        """            _col('line_count', 'Dòng', weight=80, align='end'),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'name': 'name',
            'period': 'date_from',
            'line_count': 'pk',
            'status': 'status',
            'created_by': 'created_by__username',
            'created_at': 'created_at',
        },
        default_sort='date_from',
    ),
    'costing_order': _spec(""",
        """            _col('line_count', 'Dòng', weight=80, align='end', default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),
        {
            'code': 'code',
            'name': 'name',
            'period': 'date_from',
            'line_count': 'pk',
            'status': 'status',
            'created_by': 'created_by__username',
            'created_at': 'created_at',
        },
        default_sort='date_from',
    ),
    'costing_order': _spec(""",
    ),
    (
        """            _col('kv_order', 'Đơn KV', weight=110),
            _col('period', 'Kỳ', weight=120),
            _col('total', 'Tổng', weight=90, align='end'),""",
        """            _col('kv_order', 'Đơn KV', weight=110, default=False),
            _col('period', 'Kỳ', weight=120),
            _col('total', 'Tổng', weight=90, align='end'),""",
    ),
    (
        """            _col('category', 'Nhóm', weight=110),
            _col('status', 'Trạng thái', weight=100),
            actions=True,
        ),
        {
            'code': 'code',
            'name': 'name',
            'category': 'category',""",
        """            _col('category', 'Nhóm', weight=110, default=False),
            _col('status', 'Trạng thái', weight=100),
            actions=True,
        ),
        {
            'code': 'code',
            'name': 'name',
            'category': 'category',""",
    ),
    (
        """            _col('disposition', 'Hướng xử lý', weight=120),
            _col('qty', 'Số lượng', weight=80, align='end'),""",
        """            _col('disposition', 'Hướng xử lý', weight=120, default=False),
            _col('qty', 'Số lượng', weight=80, align='end'),""",
    ),
    (
        """    'actual_cost': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('mo', 'Lệnh sản xuất', weight=120),
            _col('material', 'Nguyên phụ liệu', weight=100, align='end'),
            _col('labor', 'Nhân công', weight=90, align='end'),
            _col('subcontract', 'Gia công', weight=90, align='end'),
            _col('total', 'Tổng', weight=90, align='end'),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),""",
        """    'actual_cost': _spec(
        _cols(
            _col('code', 'Mã', required=True),
            _col('mo', 'Lệnh sản xuất', weight=120),
            _col('material', 'Nguyên phụ liệu', weight=100, align='end', default=False),
            _col('labor', 'Nhân công', weight=90, align='end', default=False),
            _col('subcontract', 'Gia công', weight=90, align='end', default=False),
            _col('total', 'Tổng', weight=90, align='end'),
            _col('status', 'Trạng thái', weight=100),
            actions=False,
        ),""",
    ),
    (
        """            _col('team_label', 'Nhãn Thống kê sản xuất', weight=140),
            _col('capacity', 'Năng lực/ngày', weight=100, align='end'),
            _col('uom', 'Đơn vị tính', weight=80),
            _col('status', 'Trạng thái', weight=90),""",
        """            _col('team_label', 'Nhãn Thống kê sản xuất', weight=140, default=False),
            _col('capacity', 'Năng lực/ngày', weight=100, align='end'),
            _col('uom', 'Đơn vị tính', weight=80, default=False),
            _col('status', 'Trạng thái', weight=90),""",
    ),
    (
        """            _col('line_count', 'Dòng NPL', weight=80, align='end'),
            _col('step_count', 'Công đoạn', weight=80, align='end'),
            _col('updated_at', 'Cập nhật', weight=110),""",
        """            _col('line_count', 'Dòng NPL', weight=80, align='end', default=False),
            _col('step_count', 'Công đoạn', weight=80, align='end', default=False),
            _col('updated_at', 'Cập nhật', weight=110),""",
    ),
    (
        """    'costing_bom': _spec(
        _cols(
            _col('product_code', 'Mã sản phẩm', required=True),
            _col('product_name', 'Tên', weight=140),
            _col('material', 'Nguyên phụ liệu', weight=100, align='end'),
            _col('labor', 'Nhân công', weight=90, align='end'),
            _col('overhead', 'Phụ phí', weight=90, align='end'),
            _col('total', 'Tổng GT', weight=90, align='end'),
            _col('sell_price', 'Giá bán', weight=90, align='end'),
            _col('margin', 'Biên', weight=80, align='end'),
            actions=False,
        ),""",
        """    'costing_bom': _spec(
        _cols(
            _col('product_code', 'Mã sản phẩm', required=True),
            _col('product_name', 'Tên', weight=140),
            _col('material', 'Nguyên phụ liệu', weight=100, align='end', default=False),
            _col('labor', 'Nhân công', weight=90, align='end', default=False),
            _col('overhead', 'Phụ phí', weight=90, align='end', default=False),
            _col('total', 'Tổng GT', weight=90, align='end'),
            _col('sell_price', 'Giá bán', weight=90, align='end', default=False),
            _col('margin', 'Biên', weight=80, align='end', default=False),
            actions=False,
        ),""",
    ),
]

for old, new in replacements:
    if old not in text:
        raise SystemExit(f"MISSING block:\n{old[:120]}...")
    text = text.replace(old, new, 1)

path.write_text(text, encoding="utf-8")
print("patched list_grid.py")
