# Generated by Django 5.2.7 on 2026-06-18 07:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tên món')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng trong danh mục')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Món cơm',
                'verbose_name_plural': 'Món cơm',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealDayOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(verbose_name='Ngày ăn')),
                ('is_offered', models.BooleanField(default=False, verbose_name='Cho phép đặt')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_offerings', to='utilities.mealdish', verbose_name='Món')),
            ],
            options={
                'verbose_name': 'Món trong ngày',
                'verbose_name_plural': 'Món trong ngày',
                'ordering': ['meal_date', 'dish__sort_order', 'dish__name'],
                'unique_together': {('meal_date', 'dish')},
            },
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(verbose_name='Ngày ăn')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='utilities.mealdish', verbose_name='Món đã chọn')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_orders', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Đơn đặt cơm',
                'verbose_name_plural': 'Đơn đặt cơm',
                'ordering': ['-meal_date', '-created_at'],
                'unique_together': {('employee', 'meal_date')},
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_month', models.DateField(verbose_name='Tháng ứng')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('3000000'))], verbose_name='Số tiền (VNĐ)')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advance_requests', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Yêu cầu ứng lương',
                'verbose_name_plural': 'Yêu cầu ứng lương',
                'ordering': ['-request_month', '-created_at'],
                'unique_together': {('employee', 'request_month')},
            },
        ),
    ]
