# Generated by Django 5.2.7 on 2026-06-18 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_seed_meal_dishes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOrderDecline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(verbose_name='Ngày ăn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_order_declines', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Từ chối đặt cơm',
                'verbose_name_plural': 'Từ chối đặt cơm',
                'ordering': ['-meal_date', '-created_at'],
                'unique_together': {('employee', 'meal_date')},
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvanceDecline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_month', models.DateField(verbose_name='Tháng ứng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advance_declines', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Từ chối ứng lương',
                'verbose_name_plural': 'Từ chối ứng lương',
                'ordering': ['-request_month', '-created_at'],
                'unique_together': {('employee', 'request_month')},
            },
        ),
    ]
