# Generated by Django 5.2.7 on 2026-06-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_decline_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='Push endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='auth')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Đăng ký push đặt cơm',
                'verbose_name_plural': 'Đăng ký push đặt cơm',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPushReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(verbose_name='Ngày ăn')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_push_reminder_logs', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Log push đặt cơm',
                'verbose_name_plural': 'Log push đặt cơm',
                'ordering': ['-sent_at'],
                'unique_together': {('employee', 'meal_date')},
            },
        ),
    ]
