# Generated by Django 5.2.7 on 2026-08-01 05:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_meal_dish_name_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Tắt = đóng đăng ký bất kể ngày trong tháng.', verbose_name='Bật ứng lương')),
                ('open_day_start', models.PositiveSmallIntegerField(default=18, help_text='Ngày trong tháng bắt đầu mở ứng (1–31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Ngày bắt đầu')),
                ('open_day_end', models.PositiveSmallIntegerField(default=19, help_text='Ngày trong tháng kết thúc mở ứng (1–31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Ngày kết thúc')),
                ('max_amount', models.DecimalField(decimal_places=0, default=Decimal('3000000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000')), django.core.validators.MaxValueValidator(Decimal('50000000'))], verbose_name='Mức ứng tối đa (VNĐ)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thiết lập ứng lương',
                'verbose_name_plural': 'Thiết lập ứng lương',
            },
        ),
        migrations.AlterField(
            model_name='salaryadvancerequest',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('50000000'))], verbose_name='Số tiền (VNĐ)'),
        ),
    ]
