# Generated by Django 5.2.7 on 2026-10-08 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiet_ke_sp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_soon_notified_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='overdue_notified_at',
        ),
        migrations.AddField(
            model_name='designversion',
            name='option_no',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Phương án'),
        ),
        migrations.AddField(
            model_name='sampleevaluation',
            name='fix_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Xác nhận đã sửa lúc'),
        ),
        migrations.AddField(
            model_name='sampleevaluation',
            name='fix_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampleevaluation',
            name='fix_done_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Kết quả sửa'),
        ),
        migrations.AddField(
            model_name='task',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='thiet_ke_sp.sampleevaluation'),
        ),
        migrations.AlterField(
            model_name='designversion',
            name='state',
            field=models.CharField(choices=[('draft', 'Đang soạn'), ('submitted', 'Đã gửi duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Yêu cầu chỉnh'), ('not_selected', 'Không chọn'), ('dropped', 'Đã bỏ')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.CharField(choices=[('proposer', 'Người đề xuất'), ('owner', 'Người phụ trách chính'), ('approver', 'Người duyệt'), ('designer', 'Thiết kế / R&D'), ('technician', 'Kỹ thuật / Tài liệu kỹ thuật'), ('sample_maker', 'May mẫu'), ('qa_user', 'QA/QC'), ('costing_user', 'Kế hoạch / Giá thành'), ('receiver', 'Bộ phận nhận bàn giao'), ('condition', 'Xử lý điều kiện duyệt'), ('fix_owner', 'Sửa lỗi mẫu')], max_length=20, verbose_name='Vai trò'),
        ),
    ]
