# Generated by Django 5.2.7 on 2026-10-08 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thiet_ke_sp', '0002_design_options_fix_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('reference', 'Tham khảo'), ('front', 'Ảnh mặt trước'), ('back', 'Ảnh mặt sau'), ('detail', 'Ảnh chi tiết'), ('design_source', 'File thiết kế gốc'), ('design_preview', 'File xem nhanh'), ('colorway', 'Ảnh colorway'), ('tech_spec', 'Bảng thông số / tài liệu kỹ thuật'), ('sample_photo', 'Ảnh mẫu thực tế'), ('evaluation', 'Biên bản đánh giá'), ('cost', 'Bảng giá thành'), ('product_photo', 'Ảnh sản phẩm'), ('other', 'Khác')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.CharField(choices=[('proposer', 'Người đề xuất'), ('owner', 'Người phụ trách chính'), ('approver', 'Người duyệt'), ('designer', 'Thiết kế / R&D'), ('technician', 'Kỹ thuật / Tài liệu kỹ thuật'), ('sample_maker', 'May mẫu'), ('qa_user', 'QA/QC'), ('costing_user', 'Kế hoạch / Giá thành'), ('receiver', 'Bộ phận nhận bàn giao'), ('condition', 'Xử lý điều kiện duyệt'), ('fix_owner', 'Sửa lỗi mẫu'), ('member', 'Thành viên hồ sơ')], max_length=20, verbose_name='Vai trò'),
        ),
        migrations.CreateModel(
            name='DossierMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('production', 'Sản xuất'), ('rnd', 'R&D'), ('planning', 'Kế hoạch SX'), ('director', 'Giám đốc')], max_length=20, verbose_name='Nhóm')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='thiet_ke_sp.productdevelopment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tksp_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Người')),
            ],
            options={
                'verbose_name': 'Thành viên hồ sơ',
                'verbose_name_plural': 'Thành viên hồ sơ',
                'ordering': ['group', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('dossier', 'user'), name='tksp_member_unique')],
            },
        ),
    ]
