# Generated by Django 5.2.7 on 2026-07-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zalo', '0002_password_reset_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='zalo_passwo_user_id_796b29_idx',
            old_name='zalo_passwo_user_id_7f2a1c_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='zalo_passwo_ip_addr_117bda_idx',
            old_name='zalo_passwo_ip_addr_9c4e2b_idx',
        ),
    ]
