# Generated by Django 5.2.7 on 2026-04-16 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': 'Chương học', 'verbose_name_plural': 'Chương học'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Khóa học', 'verbose_name_plural': 'Khóa học'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Danh mục khóa học', 'verbose_name_plural': 'Danh mục khóa học'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Ghi danh học tập', 'verbose_name_plural': 'Ghi danh học tập'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Bài học', 'verbose_name_plural': 'Bài học'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'Tiến độ bài học', 'verbose_name_plural': 'Tiến độ bài học'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='training.course', verbose_name='Khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_courses', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên được giao'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.coursecategory', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='training.course', verbose_name='Khóa học'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tham gia'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Đã hoàn thành'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='Tài liệu đính kèm'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='training.chapter', verbose_name='Chương'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video bài giảng'), ('pdf', 'Tài liệu PDF'), ('reading', 'Bài viết/Văn bản')], max_length=20, verbose_name='Loại bài học'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Đường dẫn Video (YouTube/Drive)'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần xem cuối'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Hoàn tất'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.lesson', verbose_name='Bài học'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên'),
        ),
    ]
