# Generated by Django 5.2.7 on 2026-04-16 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_chapter_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Nội dung bài học'),
        ),
    ]
