from django.urls import path
from . import views
from hrm import views as hrm_views
urlpatterns = [
     
    path('', views.home_portal, name='home_portal'), 
    path('exams/', views.exam_list, name='exam_list'),
    path('exams/<int:exam_id>/take/', views.take_exam, name='take_exam'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/exam/add/', views.exam_create, name='exam_create'),
    path('dashboard/exam/<int:pk>/edit/', views.exam_edit, name='exam_edit'),
    path('dashboard/exam/<int:pk>/delete/', views.exam_delete, name='exam_delete'),
    path('dashboard/exam/<int:exam_id>/question/add/', views.question_add, name='question_add'),
    path('dashboard/exam/<int:exam_id>/question/<int:question_id>/edit/', views.question_edit, name='question_edit_detail'),
    path('dashboard/exam/<int:exam_id>/question/<int:question_id>/remove/', views.question_remove, name='question_remove'),
    path('dashboard/results/', views.admin_results, name='admin_results'),
    path('dashboard/submission/<int:submission_id>/grade/', views.grade_submission, name='grade_submission'),
    path('dashboard/competency/add-ajax/', views.competency_add_ajax, name='competency_add_ajax'),
    path('dashboard/competency/delete/<int:pk>/', views.competency_delete_ajax, name='competency_delete_ajax'),
    path('dashboard/results/<int:exam_id>/', views.admin_results, name='admin_results'),
    
    path('dashboard/users/', hrm_views.user_list, name='user_list'),
    path('dashboard/users/add/', hrm_views.user_add, name='user_add'),
    path('dashboard/users/suggest-username/', hrm_views.user_suggest_username, name='user_suggest_username'),
    path('dashboard/users/edit/<int:user_id>/', hrm_views.user_edit, name='user_edit'),
    path(
        'dashboard/users/edit/<int:user_id>/concurrent-slot/save/',
        hrm_views.user_concurrent_slot_save,
        name='user_concurrent_slot_save',
    ),
    path('dashboard/users/<int:user_id>/nas-folders/', hrm_views.user_nas_folders, name='user_nas_folders'),
    path('dashboard/users/delete/<int:user_id>/', hrm_views.user_delete, name='user_delete'),
    path('dashboard/users/<int:user_id>/reset-password/', hrm_views.user_password_reset, name='user_password_reset'),
    path('dashboard/users/<int:user_id>/toggle-employed/', hrm_views.user_toggle_employed, name='user_toggle_employed'),
    path('dashboard/users/import/', hrm_views.user_import_excel, name='user_import_excel'),
    path('dashboard/users/export/', hrm_views.user_export_excel, name='user_export_excel'),
    path('dashboard/users/download-template/', hrm_views.user_download_template, name='user_download_template'),

    path('dashboard/org/', hrm_views.org_structure, name='org_structure'),
    path('dashboard/departments/', hrm_views.department_list, name='department_list'),
    path('dashboard/departments/add/', hrm_views.department_add, name='department_add'),
    path('dashboard/departments/edit/<int:pk>/', hrm_views.department_edit, name='department_edit'),
    path('dashboard/departments/<int:pk>/permissions/', hrm_views.department_permissions, name='department_permissions'),
    path('dashboard/permissions/', hrm_views.permission_config, name='permission_config'),
    path('dashboard/permissions/groups/add/', hrm_views.permission_group_add, name='permission_group_add'),
    path('dashboard/permissions/groups/<int:pk>/edit/', hrm_views.permission_group_edit, name='permission_group_edit'),
    path('dashboard/permissions/groups/<int:pk>/delete/', hrm_views.permission_group_delete, name='permission_group_delete'),
    path('dashboard/permissions/roles/<str:role>/', hrm_views.role_permission_edit, name='role_permission_edit'),
    path('dashboard/departments/delete/<int:pk>/', hrm_views.department_delete, name='department_delete'),
    path('dashboard/divisions/add/', hrm_views.division_add, name='division_add'),
    path('dashboard/divisions/edit/<int:pk>/', hrm_views.division_edit, name='division_edit'),
    path('dashboard/divisions/delete/<int:pk>/', hrm_views.division_delete, name='division_delete'),
    path('dashboard/org/positions/add/', hrm_views.org_position_add, name='org_position_add'),
    path('dashboard/org/positions/edit/<int:pk>/', hrm_views.org_position_edit, name='org_position_edit'),
    path('dashboard/org/positions/delete/<int:pk>/', hrm_views.org_position_delete, name='org_position_delete'),

    path('login-redirect/', views.login_redirect_view, name='login_redirect'),
]