# Generated by Django 5.2.7 on 2026-06-10 03:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Mã nhóm')),
                ('name', models.CharField(max_length=120, verbose_name='Tên nhóm')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Nhóm nguyên phụ liệu',
                'verbose_name_plural': 'Nhóm nguyên phụ liệu',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã NCC')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Điện thoại')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='Mã ĐVT')),
                ('name', models.CharField(max_length=40, verbose_name='Tên ĐVT')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Đơn vị tính',
                'verbose_name_plural': 'Đơn vị tính',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Mã vị trí')),
                ('name', models.CharField(max_length=120, verbose_name='Tên vị trí / kệ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
            ],
            options={
                'verbose_name': 'Vị trí kho',
                'verbose_name_plural': 'Vị trí kho',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Mã NPL')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nguyên phụ liệu')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='Màu sắc')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='Quy cách / khổ')),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tồn tối thiểu')),
                ('image', models.ImageField(blank=True, upload_to='npl/materials/', verbose_name='Hình ảnh')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='kho_npl.materialcategory', verbose_name='Nhóm')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='kho_npl.supplier', verbose_name='NCC chính')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='kho_npl.unit', verbose_name='Đơn vị tính')),
            ],
            options={
                'verbose_name': 'Nguyên phụ liệu',
                'verbose_name_plural': 'Nguyên phụ liệu',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Mã phiếu xuất')),
                ('issue_date', models.DateField(verbose_name='Ngày xuất')),
                ('issue_type', models.CharField(choices=[('production', 'Xuất cho sản xuất'), ('sample', 'Xuất làm mẫu'), ('waste', 'Xuất bù hao hụt'), ('return_supplier', 'Xuất trả nhà cung cấp'), ('scrap', 'Xuất hủy / hư hỏng'), ('transfer', 'Xuất điều chuyển kho')], default='production', max_length=30, verbose_name='Lý do xuất')),
                ('production_order', models.CharField(blank=True, max_length=60, verbose_name='Lệnh sản xuất')),
                ('product_code', models.CharField(blank=True, max_length=60, verbose_name='Mã sản phẩm')),
                ('recipient_department', models.CharField(blank=True, max_length=120, verbose_name='Bộ phận nhận')),
                ('recipient_name', models.CharField(blank=True, max_length=120, verbose_name='Người nhận')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã ghi sổ'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_issues_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_issues_issued', to=settings.AUTH_USER_MODEL, verbose_name='Người xuất')),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'verbose_name_plural': 'Phiếu xuất kho',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Mã phiếu nhập')),
                ('receipt_date', models.DateField(verbose_name='Ngày nhập')),
                ('po_number', models.CharField(blank=True, max_length=60, verbose_name='Số PO / đơn mua')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã ghi sổ'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_receipts_checked', to=settings.AUTH_USER_MODEL, verbose_name='Người kiểm')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_receipts_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_receipts_received', to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='kho_npl.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Mã kỳ kiểm kê')),
                ('name', models.CharField(max_length=200, verbose_name='Tên kỳ')),
                ('stocktake_date', models.DateField(verbose_name='Ngày kiểm kê')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('counting', 'Đang kiểm'), ('review', 'Chờ duyệt'), ('closed', 'Đã chốt')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_stocktakes_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Kỳ kiểm kê',
                'verbose_name_plural': 'Kỳ kiểm kê',
                'ordering': ['-stocktake_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Tồn hệ thống')),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='Tồn thực tế')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='kho_npl.material', verbose_name='Nguyên phụ liệu')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kho_npl.stocktake', verbose_name='Kỳ kiểm kê')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='kho_npl.warehouselocation', verbose_name='Vị trí')),
            ],
            options={
                'verbose_name': 'Dòng kiểm kê',
                'verbose_name_plural': 'Dòng kiểm kê',
            },
        ),
        migrations.CreateModel(
            name='StockReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SL đặt')),
                ('received_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SL nhập')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='kho_npl.material', verbose_name='Nguyên phụ liệu')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kho_npl.stockreceipt', verbose_name='Phiếu nhập')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='kho_npl.warehouselocation', verbose_name='Vị trí kho')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu nhập',
                'verbose_name_plural': 'Chi tiết phiếu nhập',
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_delta', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Biến động')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Tồn sau')),
                ('ref_type', models.CharField(max_length=20, verbose_name='Loại chứng từ')),
                ('ref_id', models.PositiveIntegerField(verbose_name='ID chứng từ')),
                ('ref_number', models.CharField(blank=True, max_length=30, verbose_name='Số chứng từ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='kho_npl.material', verbose_name='Nguyên phụ liệu')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='kho_npl.warehouselocation', verbose_name='Vị trí')),
            ],
            options={
                'verbose_name': 'Sổ kho',
                'verbose_name_plural': 'Sổ kho',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Số lượng')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kho_npl.stockissue', verbose_name='Phiếu xuất')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_lines', to='kho_npl.material', verbose_name='Nguyên phụ liệu')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_lines', to='kho_npl.warehouselocation', verbose_name='Vị trí kho')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu xuất',
                'verbose_name_plural': 'Chi tiết phiếu xuất',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Mã phiếu điều chỉnh')),
                ('adjust_date', models.DateField(verbose_name='Ngày điều chỉnh')),
                ('system_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Tồn hệ thống')),
                ('actual_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Tồn thực tế')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_adjustments_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='kho_npl.material', verbose_name='Nguyên phụ liệu')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npl_adjustments_proposed', to=settings.AUTH_USER_MODEL, verbose_name='Người đề xuất')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='kho_npl.warehouselocation', verbose_name='Vị trí')),
            ],
            options={
                'verbose_name': 'Phiếu điều chỉnh',
                'verbose_name_plural': 'Phiếu điều chỉnh',
                'ordering': ['-adjust_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Số lượng')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='kho_npl.material', verbose_name='Nguyên phụ liệu')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='kho_npl.warehouselocation', verbose_name='Vị trí')),
            ],
            options={
                'verbose_name': 'Tồn theo vị trí',
                'verbose_name_plural': 'Tồn theo vị trí',
                'unique_together': {('material', 'location')},
            },
        ),
    ]
