# Generated by Django 5.2.7 on 2026-06-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0004_scrap_warehouse_and_disposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='npl/adjustments/attachments/', verbose_name='Chứng từ / ảnh'),
        ),
        migrations.AddField(
            model_name='stockdisposal',
            name='attachment',
            field=models.FileField(blank=True, upload_to='npl/disposals/attachments/', verbose_name='Chứng từ / ảnh'),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='attachment',
            field=models.FileField(blank=True, upload_to='npl/issues/attachments/', verbose_name='Chứng từ / ảnh'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='attachment',
            field=models.FileField(blank=True, upload_to='npl/receipts/attachments/', verbose_name='Chứng từ / ảnh'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='attachment',
            field=models.FileField(blank=True, upload_to='npl/stocktakes/attachments/', verbose_name='Chứng từ / ảnh'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='attachment',
            field=models.FileField(blank=True, upload_to='npl/transfers/attachments/', verbose_name='Chứng từ / ảnh'),
        ),
    ]
