# Generated by Django 5.2.7 on 2026-06-11 01:31

import django.db.models.deletion
from django.db import migrations, models


def migrate_adjustments_to_lines(apps, schema_editor):
    StockAdjustment = apps.get_model('kho_npl', 'StockAdjustment')
    StockAdjustmentLine = apps.get_model('kho_npl', 'StockAdjustmentLine')
    lines = []
    for adj in StockAdjustment.objects.all().iterator():
        if adj.material_id is None:
            continue
        lines.append(StockAdjustmentLine(
            adjustment_id=adj.pk,
            material_id=adj.material_id,
            location_id=adj.location_id,
            system_qty=adj.system_qty,
            actual_qty=adj.actual_qty,
        ))
    if lines:
        StockAdjustmentLine.objects.bulk_create(lines)


def reverse_adjustment_lines(apps, schema_editor):
    StockAdjustment = apps.get_model('kho_npl', 'StockAdjustment')
    StockAdjustmentLine = apps.get_model('kho_npl', 'StockAdjustmentLine')
    for adj in StockAdjustment.objects.all().iterator():
        line = StockAdjustmentLine.objects.filter(adjustment_id=adj.pk).order_by('id').first()
        if not line:
            continue
        adj.material_id = line.material_id
        adj.location_id = line.location_id
        adj.system_qty = line.system_qty
        adj.actual_qty = line.actual_qty
        adj.save(update_fields=['material_id', 'location_id', 'system_qty', 'actual_qty'])
    StockAdjustmentLine.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0005_doc_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Tồn hệ thống')),
                ('actual_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Tồn thực tế')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kho_npl.stockadjustment', verbose_name='Phiếu điều chỉnh')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='kho_npl.warehouselocation', verbose_name='Vị trí')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='kho_npl.material', verbose_name='Nguyên phụ liệu')),
            ],
            options={
                'verbose_name': 'Dòng điều chỉnh',
                'verbose_name_plural': 'Dòng điều chỉnh',
            },
        ),
        migrations.RunPython(migrate_adjustments_to_lines, reverse_adjustment_lines),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='actual_qty',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='material',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='system_qty',
        ),
        migrations.AddConstraint(
            model_name='stockadjustmentline',
            constraint=models.UniqueConstraint(fields=('adjustment', 'material', 'location'), name='uniq_adjustment_material_location'),
        ),
    ]
