# Generated by Django 5.2.7 on 2026-06-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0010_material_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='kho_npl.materialcategory', verbose_name='Nhóm cấp 1'),
        ),
    ]
