# Generated by Django 5.2.7 on 2026-07-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0013_issue_type_free_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockissue',
            name='status',
            field=models.CharField(choices=[('draft', 'Đã tạo'), ('posted', 'Đã xuất kho'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Đã tạo'), ('posted', 'Đã nhập kho'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
