# Generated by Django 5.2.7 on 2026-07-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0020_npl_doc_attachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='npldocattachment',
            new_name='kho_npl_npl_content_8cd235_idx',
            old_name='kho_npl_npl_content_6a8f0d_idx',
        ),
    ]
