# Generated by Django 5.2.7 on 2026-07-15 01:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0021_rename_kho_npl_npl_content_6a8f0d_idx_kho_npl_npl_content_8cd235_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockissueline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá xuất'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Thành tiền'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá'),
        ),
        migrations.AddField(
            model_name='stockreceiptline',
            name='batch_code',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Mã lô'),
        ),
        migrations.AddField(
            model_name='stockreceiptline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá nhập'),
        ),
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, verbose_name='Mã lô')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá nhập')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Ngày nhập lô')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tồn lô')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='kho_npl.material', verbose_name='Nguyên phụ liệu')),
            ],
            options={
                'verbose_name': 'Lô hàng NPL',
                'verbose_name_plural': 'Lô hàng NPL',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='kho_npl.materialbatch', verbose_name='Lô hàng'),
        ),
        migrations.AddField(
            model_name='stockdisposalline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposal_lines', to='kho_npl.materialbatch', verbose_name='Lô hàng'),
        ),
        migrations.AddField(
            model_name='stockissueline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_lines', to='kho_npl.materialbatch', verbose_name='Lô hàng'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='kho_npl.materialbatch', verbose_name='Lô hàng'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='kho_npl.materialbatch', verbose_name='Lô hàng'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='kho_npl.materialbatch', verbose_name='Lô hàng'),
        ),
        migrations.AddConstraint(
            model_name='materialbatch',
            constraint=models.UniqueConstraint(fields=('material', 'code'), name='uniq_material_batch_code'),
        ),
    ]
