# Generated by Django 5.2.7 on 2026-07-15 03:34

from django.db import migrations, models


def backfill_variant_groups(apps, schema_editor):
    from kho_npl.variant_group import infer_variant_group_from_code, normalize_variant_group

    Material = apps.get_model('kho_npl', 'Material')
    for material in Material.objects.all().only('id', 'code', 'variant_group'):
        group = normalize_variant_group(material.variant_group)
        if not group:
            group = infer_variant_group_from_code(material.code)
        if group != (material.variant_group or ''):
            Material.objects.filter(pk=material.pk).update(variant_group=group)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0024_flatten_material_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='variant_group',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='Gom các mã cùng dòng hàng (màu/quy cách khác nhau). Ví dụ: SIEU, CR3, BICH.',
                max_length=80,
                verbose_name='Tên nhóm hàng',
            ),
        ),
        migrations.RunPython(backfill_variant_groups, noop_reverse),
    ]
