# Generated by Django 5.2.7 on 2026-07-15 06:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0025_material_variant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Dùng làm giá bình quân khi chưa có lô và gợi ý đơn giá phiếu nhập.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Giá cơ bản'),
        ),
    ]
