# Generated by Django 5.2.7 on 2026-07-17 02:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0026_material_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouselocation',
            name='location_kind',
            field=models.CharField(choices=[('stock', 'Kho thường'), ('staging_npl', 'Staging NVL chờ SX'), ('staging_wip', 'Staging BTP giữa chuyền'), ('scrap', 'Kho phế / hủy')], db_index=True, default='stock', max_length=20, verbose_name='Loại vị trí'),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SL giữ')),
                ('ref_type', models.CharField(choices=[('ycx', 'Yêu cầu xuất'), ('khnvl', 'Kế hoạch NPL'), ('mo', 'Lệnh SX')], db_index=True, max_length=10)),
                ('ref_code', models.CharField(db_index=True, max_length=60, verbose_name='Mã chứng từ')),
                ('production_order_code', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Đang giữ'), ('consumed', 'Đã xuất'), ('released', 'Đã hủy')], db_index=True, default='active', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='kho_npl.warehouselocation', verbose_name='Vị trí (tuỳ chọn)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='kho_npl.material', verbose_name='NVL')),
            ],
            options={
                'verbose_name': 'Giữ chỗ tồn',
                'verbose_name_plural': 'Giữ chỗ tồn',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['material', 'status'], name='kho_npl_sto_materia_6350d8_idx')],
            },
        ),
    ]
