# Generated by Django 5.2.7 on 2026-07-17 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0027_factory_ops_gaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreservation',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='kho_npl.material', verbose_name='Nguyên phụ liệu'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='ref_type',
            field=models.CharField(choices=[('ycx', 'Yêu cầu xuất'), ('khnvl', 'Kế hoạch nguyên phụ liệu'), ('mo', 'Lệnh sản xuất')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='location_kind',
            field=models.CharField(choices=[('stock', 'Kho thường'), ('staging_npl', 'Vùng chờ nguyên phụ liệu'), ('staging_wip', 'Vùng chờ bán thành phẩm'), ('scrap', 'Kho phế / hủy')], db_index=True, default='stock', max_length=20, verbose_name='Loại vị trí'),
        ),
    ]
