# Generated by Django 5.2.7 on 2026-08-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0028_thicken_ops_wip_ycx_hr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'ordering': ['-adjust_date', '-id'], 'verbose_name': 'Phiếu kiểm kê', 'verbose_name_plural': 'Phiếu kiểm kê'},
        ),
        migrations.AlterModelOptions(
            name='stockadjustmentline',
            options={'verbose_name': 'Dòng kiểm kê', 'verbose_name_plural': 'Dòng kiểm kê'},
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjust_date',
            field=models.DateField(verbose_name='Ngày kiểm kê'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Mã phiếu kiểm kê'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kho_npl.stockadjustment', verbose_name='Phiếu kiểm kê'),
        ),
    ]
