# Generated by Django 5.2.7 on 2026-09-08 04:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0030_material_primary_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentline',
            name='line_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kho_npl.unit', verbose_name='ĐVT kiểm kê'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='qty_base',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tồn thực tế theo ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Hệ số về ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stockdisposalline',
            name='line_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kho_npl.unit', verbose_name='ĐVT hủy'),
        ),
        migrations.AddField(
            model_name='stockdisposalline',
            name='qty_base',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SL theo ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stockdisposalline',
            name='uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Hệ số về ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stockissueline',
            name='line_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kho_npl.unit', verbose_name='ĐVT xuất'),
        ),
        migrations.AddField(
            model_name='stockissueline',
            name='qty_base',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SL theo ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stockissueline',
            name='uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Hệ số về ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stockreceiptline',
            name='line_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kho_npl.unit', verbose_name='ĐVT nhập'),
        ),
        migrations.AddField(
            model_name='stockreceiptline',
            name='qty_base',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SL theo ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stockreceiptline',
            name='uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Hệ số về ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='line_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kho_npl.unit', verbose_name='ĐVT kiểm kê'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='qty_base',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tồn thực tế theo ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Hệ số về ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='line_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kho_npl.unit', verbose_name='ĐVT chuyển'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='qty_base',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SL theo ĐVT lẻ'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='uom_factor',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Hệ số về ĐVT lẻ'),
        ),
        migrations.AlterField(
            model_name='material',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='kho_npl.materialspecification', verbose_name='Quy cách / khổ'),
        ),
        migrations.CreateModel(
            name='MaterialSpecificationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Cấp')),
                ('qty_in_next_lower', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Cấp 1 luôn bằng 1. Cấp trên nhập số đơn vị của cấp ngay dưới.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Số lượng cấp dưới')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='kho_npl.materialspecification', verbose_name='Quy cách')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification_levels', to='kho_npl.unit', verbose_name='Đơn vị tính')),
            ],
            options={
                'verbose_name': 'Cấp quy cách NPL',
                'verbose_name_plural': 'Cấp quy cách NPL',
                'ordering': ['level'],
                'constraints': [models.UniqueConstraint(fields=('specification', 'level'), name='uniq_npl_spec_level'), models.UniqueConstraint(fields=('specification', 'unit'), name='uniq_npl_spec_unit'), models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 3)), name='npl_spec_level_between_1_3')],
            },
        ),
    ]
