# Generated by Django 5.2.7 on 2026-09-08 05:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0032_backfill_multilevel_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbatch',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá nhập'),
        ),
        migrations.AlterField(
            model_name='stockissueline',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá xuất'),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='stockreceiptline',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Đơn giá nhập'),
        ),
    ]
