# Generated by Django 5.2.7 on 2026-09-19 02:28

from django.db import migrations, models

# Keep in sync with kho_npl.material_department.CATEGORY_DEPARTMENT_DEFAULTS
_CATEGORY_DEPARTMENT_DEFAULTS = {
    'vai': 'CẮT, TRẢI VẢI',
    'vai-phoi': 'CẮT, TRẢI VẢI',
    'giaylot': 'CẮT, TRẢI VẢI',
    'cat-print-tmp': 'CẮT, TRẢI VẢI',
    'bo-tay': 'MAY',
    'bo-co': 'MAY',
    'dayco': 'MAY',
    'dayxoquan': 'MAY',
    'thun': 'MAY',
    'day-khoa': 'MAY',
    'day-rut': 'MAY',
    'nut': 'MAY',
    'chi-may': 'MAY',
    'satin': 'MAY',
    'phulieu-may': 'MAY',
    'nhansize': 'MAY',
    'tem-nhan': 'MAY',
    'thebai': 'MAY',
    'tagdaybar': 'MAY',
    'decal': 'IN ÉP',
    'bao-bi': 'GẤP XẾP',
    'bich': 'GẤP XẾP',
    'chongam': 'GẤP XẾP',
    'phulieu-xep': 'GẤP XẾP',
    'vattu': 'CƠ ĐIỆN',
    'khac': 'MAY',
}
_FALLBACK = 'MAY'


def assign_default_departments(apps, schema_editor):
    Material = apps.get_model('kho_npl', 'Material')
    to_update = []
    for material in Material.objects.select_related('category').iterator(chunk_size=500):
        if (material.department or '').strip():
            continue
        code = (material.category.code if material.category_id else '') or ''
        label = _CATEGORY_DEPARTMENT_DEFAULTS.get(code.strip().lower(), _FALLBACK)
        material.department = label
        to_update.append(material)
        if len(to_update) >= 500:
            Material.objects.bulk_update(to_update, ['department'])
            to_update = []
    if to_update:
        Material.objects.bulk_update(to_update, ['department'])


def clear_default_departments(apps, schema_editor):
    Material = apps.get_model('kho_npl', 'Material')
    Material.objects.exclude(department='').update(department='')


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0036_ensure_scrap_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='department',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='Bộ phận SX / QLCL theo chuẩn Nhân sự (cùng danh mục hồ sơ sản phẩm).',
                max_length=100,
                verbose_name='Bộ phận',
            ),
        ),
        migrations.RunPython(assign_default_departments, clear_default_departments),
    ]
