# Generated by Django 5.2.7 on 2026-09-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0037_material_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='stockdisposal',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='warehouselocation',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='code',
            field=models.SlugField(max_length=40, verbose_name='Mã nhóm'),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='code',
            field=models.CharField(max_length=40, verbose_name='Mã vị trí'),
        ),
        migrations.AddConstraint(
            model_name='materialcategory',
            constraint=models.UniqueConstraint(fields=('stock_domain', 'code'), name='uniq_npl_category_domain_code'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(fields=('stock_domain', 'code'), name='uniq_npl_location_domain_code'),
        ),
    ]



class Migration(migrations.Migration):

    dependencies = [
        ('kho_npl', '0037_material_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='stockdisposal',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='stockreceipt',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AddField(
            model_name='warehouselocation',
            name='stock_domain',
            field=models.CharField(choices=[('npl', 'Kho nguyên phụ liệu'), ('vat_tu', 'Kho vật tư')], db_index=True, default='npl', max_length=20, verbose_name='Kho nghiệp vụ'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='code',
            field=models.SlugField(max_length=40, verbose_name='Mã nhóm'),
        ),
        migrations.AlterField(
            model_name='warehouselocation',
            name='code',
            field=models.CharField(max_length=40, verbose_name='Mã vị trí'),
        ),
        migrations.AddConstraint(
            model_name='materialcategory',
            constraint=models.UniqueConstraint(fields=('stock_domain', 'code'), name='uniq_npl_category_domain_code'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(fields=('stock_domain', 'code'), name='uniq_npl_location_domain_code'),
        ),
    ]
